### ISSUE TITLE
Fresh endpoints-guice deployment fails

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/java-docs-samples#1000]
I am following the endpoints-v2-guice README. I got all the way to deployment. When I run mvn appengine:deploy I get the following error:

"C:\Program Files\Java\jdk-9.0.4\bin\java" -Dmaven.multiModuleProjectDirectory=D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.3\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.3\lib\idea_rt.jar=4871:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2017.3.3 com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.example.echo:echo-guice-j8:war:1.0-SNAPSHOT
[WARNING] 'parent.relativePath' of POM com.example.echo:echo-guice-j8:1.0-SNAPSHOT (D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\pom.xml) points at com.google.cloud:appengine-java8-samples instead of com.google.cloud.samples:shared-configuration, please verify your project structure @ line 28, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building echo-guice-j8 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> appengine-maven-plugin:1.3.2:deploy (default-cli) > package @ echo-guice-j8 >>>
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ echo-guice-j8 ---
[INFO] argLine set to "-javaagent:C:\\Users\\Joseph Malicke\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=D:\\_dev\\_projects\\java-docs-samples\\appengine-java8\\endpoints-v2-guice\\target\\jacoco.exec"
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ echo-guice-j8 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:compile (default-compile) @ echo-guice-j8 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- versions-maven-plugin:2.3:display-dependency-updates (default) @ echo-guice-j8 ---
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   javax.servlet:javax.servlet-api ....................... 3.1.0 -> 4.0.0
[INFO] 
[INFO] 
[INFO] --- versions-maven-plugin:2.3:display-plugin-updates (default) @ echo-guice-j8 ---
[INFO] 
[INFO] The following plugin updates are available:
[INFO]   com.google.cloud.tools:endpoints-framework-maven-plugin  1.0.2 -> 1.0.3
[INFO] 
[WARNING] The following plugins do not have their version specified:
[WARNING]   maven-clean-plugin .......................... (from super-pom) 2.2
[WARNING]   maven-compiler-plugin ..................... (from super-pom) 2.0.2
[WARNING]   maven-deploy-plugin ......................... (from super-pom) 2.4
[WARNING]   maven-install-plugin ........................ (from super-pom) 2.2
[WARNING]   maven-resources-plugin ...................... (from super-pom) 2.2
[WARNING]   maven-site-plugin .................... (from super-pom) 2.0-beta-4
[WARNING]   maven-surefire-plugin ..................... (from super-pom) 2.4.2
[INFO] 
[WARNING] Project does not define minimum Maven version, default is: 2.0
[INFO] Plugins require minimum Maven version of: 3.0
[INFO] Note: the super-pom from Maven 3.3.9 defines some of the plugin
[INFO]       versions and may be influencing the plugins required minimum Maven
[INFO]       version.
[INFO] 
[ERROR] Project does not define required minimum version of Maven.
[ERROR] Update the pom.xml to contain
[ERROR]     <prerequisites>
[ERROR]       <maven>3.0</maven>
[ERROR]     </prerequisites>
[INFO] 
[INFO] Require Maven 2.0.1 to use the following plugin updates:
[INFO]   maven-war-plugin .............................................. 2.0.2
[INFO] 
[INFO] Require Maven 2.0.2 to use the following plugin updates:
[INFO]   maven-site-plugin ........................................ 2.0-beta-7
[INFO] 
[INFO] Require Maven 2.0.6 to use the following plugin updates:
[INFO]   maven-clean-plugin .............................................. 2.5
[INFO]   maven-deploy-plugin ........................................... 2.8.1
[INFO]   maven-install-plugin .......................................... 2.5.1
[INFO]   maven-resources-plugin .......................................... 2.6
[INFO]   maven-site-plugin ............................................. 2.0.1
[INFO]   maven-surefire-plugin ......................................... 2.4.3
[INFO]   maven-war-plugin ................................................ 2.4
[INFO] 
[INFO] Require Maven 2.0.9 to use the following plugin updates:
[INFO]   maven-compiler-plugin ........................................... 3.1
[INFO]   maven-surefire-plugin .......................................... 2.17
[INFO] 
[INFO] Require Maven 2.1.0 to use the following plugin updates:
[INFO]   maven-site-plugin ............................................. 2.1.1
[INFO] 
[INFO] Require Maven 2.2.0 to use the following plugin updates:
[INFO]   maven-site-plugin ............................................... 3.0
[INFO] 
[INFO] Require Maven 2.2.1 to use the following plugin updates:
[INFO]   maven-clean-plugin ............................................ 2.6.1
[INFO]   maven-compiler-plugin ........................................... 3.3
[INFO]   maven-deploy-plugin ........................................... 2.8.2
[INFO]   maven-install-plugin .......................................... 2.5.2
[INFO]   maven-resources-plugin .......................................... 2.7
[INFO]   maven-site-plugin ............................................... 3.4
[INFO]   maven-surefire-plugin .......................................... 2.20
[INFO]   maven-war-plugin ................................................ 2.6
[INFO]   org.codehaus.mojo:versions-maven-plugin ......................... 2.2
[INFO] 
[INFO] Require Maven 3.0 to use the following plugin updates:
[INFO]   maven-clean-plugin ............................................ 3.0.0
[INFO]   maven-compiler-plugin ......................................... 3.7.0
[INFO]   maven-resources-plugin ........................................ 3.0.2
[INFO]   maven-site-plugin ............................................... 3.7
[INFO]   maven-surefire-plugin ........................................ 2.20.1
[INFO]   maven-war-plugin .............................................. 3.2.0
[INFO]   org.codehaus.mojo:versions-maven-plugin ......................... 2.5
[INFO] 
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ echo-guice-j8 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:testCompile (default-testCompile) @ echo-guice-j8 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ echo-guice-j8 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ echo-guice-j8 ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] --- maven-war-plugin:2.6:war (default-war) @ echo-guice-j8 ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.converters.collections.TreeMapConverter (file:/C:/Users/Joseph%20Malicke/.m2/repository/com/thoughtworks/xstream/xstream/1.4.4/xstream-1.4.4.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.converters.collections.TreeMapConverter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Packaging webapp
[INFO] Assembling webapp [echo-guice-j8] in [D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\echo-guice-j8-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice/src/main/webapp/WEB-INF] to [D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\echo-guice-j8-1.0-SNAPSHOT]
[INFO] Copying webapp resources [D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\src\main\webapp]
[INFO] Webapp assembled in [999 msecs]
[INFO] Building war: D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\echo-guice-j8-1.0-SNAPSHOT.war
[INFO] 
[INFO] <<< appengine-maven-plugin:1.3.2:deploy (default-cli) < package @ echo-guice-j8 <<<
[INFO] 
[INFO] --- appengine-maven-plugin:1.3.2:deploy (default-cli) @ echo-guice-j8 ---
[INFO] Deleting the staging directory: D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\appengine-staging
[INFO] Staging the application to: D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\appengine-staging
[INFO] Detected App Engine standard environment application.
Jan 22, 2018 1:20:32 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: C:\Program Files\Java\jdk-9.0.4\bin\java.exe -cp C:\Users\Joseph Malicke\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --disable_update_check stage D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\echo-guice-j8-1.0-SNAPSHOT D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\appengine-staging
[INFO] GCLOUD: Reading application configuration data...
[INFO] GCLOUD: 
[INFO] GCLOUD: 
[INFO] GCLOUD: Beginning interaction for module default...
[INFO] GCLOUD: 0% Scanning for jsp files.
[INFO] GCLOUD: 0% Generated git repository information file.
[INFO] GCLOUD: Success.
[INFO] GCLOUD: Temporary staging for module default directory left in D:\_dev\_projects\java-docs-samples\appengine-java8\endpoints-v2-guice\target\appengine-staging
Jan 22, 2018 1:20:34 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: C:\Users\Joseph Malicke\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd app deploy
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) INTERNAL: Internal error encountered.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.759 s
[INFO] Finished at: 2018-01-22T13:21:07-05:00
[INFO] Final Memory: 28M/92M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy (default-cli) on project echo-guice-j8: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy failed: Non zero exit: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Process finished with exit code 1

**Comment by lesv** [comment]
@p-buse PTAL
@frankyn If you can suggest something???

**Comment by frankyn** [comment]
Hi @jmalsoftware!

Thanks for filing an issue. I tried to reproduce this error, but was not successful. 

I understand you're using Windows given the path in the maven logs and would like to verify a few things before trying this on a Windows machine. 

I'd like to verify the following:
1. You installed App engine tools for Java using `gcloud components install app-engine-java`
2. You updated the project-id in the [pom.xml](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java8/endpoints-v2-guice/pom.xml#L42) with an existing Google Cloud Platform project id.
3. You updated the project-id in the [appengine-web.xml](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java8/endpoints-v2-guice/src/main/java/com/example/echo/EchoEndpointModule.java#L40-L41) with an existing Google Cloud Platform project Id.

Thank you for your patience.

**Comment by frankyn** [comment]
Closing issue as it hasn't been updated in a year.
