### ISSUE TITLE
Wrong algorithm name using the KeyFactory

### ISSUE THREAD

**Issue by FlorianTim** [GoogleCloudPlatform/java-docs-samples#1010]
java-docs-samples\iot\api-client\manager\src\main\java\com\example\cloud\iot\examples\MqttExample.java

from: KeyFactory kf = KeyFactory.getInstance("ES256");
to: KeyFactory kf = KeyFactory.getInstance("EC");

EC is the right name for the Elliptic Curve algorithm.

https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#KeyFactory

**Comment by lesv** [comment]
@gguuss Can you comment?

**Comment by gguuss** [comment]
I believe the JWT-based ES256 is correct , I may actually have the readme / documentation wrong and should correct that.

**Comment by gguuss** [comment]
That said, the tests still pass and your pointer to the docs corroborates your point. I'll look into why the tests pass in both cases as we're testing adding EC and RSA devices.

**Comment by gguuss** [comment]
Tested end-to-end and working for me, approving.

**Comment by nnegrey** [comment]
This appears to have been resolved, closing the issue.
