### ISSUE TITLE
Datastore examples look outdated

### ISSUE THREAD

**Issue by ibalashov** [GoogleCloudPlatform/java-docs-samples#106]
E.g. there is no such element as `PropertyFilter.hasAncestor` in 
`"com.google.apis" % "google-api-services-datastore-protobuf" % "v1beta2-rev1-4.0.0"`

And it is not quite obvious from the API how to make ancestor queries.

**Comment by ajkannan** [comment]
Hi @ibalashov, thanks for creating this issue.

Are you referring to the Datastore examples listed in [java-docs-samples/datastore/](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/datastore/src/main/java/com/google/datastore/snippets/Concepts.java#L500), mirrored [here](https://cloud.google.com/datastore/docs/concepts/queries#ancestor_queries) in the cloud.google.com/datastore docs?  If yes, those samples actually using [gcloud-java's Datastore client](https://github.com/GoogleCloudPlatform/gcloud-java/tree/master/gcloud-java-datastore).  gcloud-java is a layer on top of the v1beta2 dependency that you listed above which intends to make some of the syntax simpler and more concise.

If you follow the instructions [here](https://github.com/GoogleCloudPlatform/gcloud-java/tree/master/gcloud-java-datastore#quickstart) to get the gcloud-java dependency and import the necessary classes, the snippet code that I linked above should work for you.  If you'd rather not go that route and continue to use `v1beta2-rev1-4.0.0` dependency, let me know and I can paste an example of an ancestor query using that library. 

I do think we can make this distinction between the two client libraries clearer on the cloud.google.com/datastore/docs page as well as in the README in java-docs-samples/datastore.

**Comment by ibalashov** [comment]
@ajkannan Thanks for the detailed response. I referred to [Concepts.java](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/datastore/src/main/java/com/google/datastore/snippets/Concepts.java), which is linked from [Queries](https://cloud.google.com/datastore/docs/concepts/queries).

Thanks for the suggestion, I will try to use gcloud-java's Datastore client.
