### ISSUE TITLE
 I am using Video Intelligence API testing with a local file of my machine following the example of github but it is not returning any type of information.

### ISSUE THREAD

**Issue by joaodematejr** [GoogleCloudPlatform/java-docs-samples#1102]
In which file did you encounter the issue?
Video Intelligence API

Did you change the file? If so, how?
no. running on wildfly 10 in java 1.8

Describe the issue
	// Call
	public String consult() throws Throwable {
                 //file link
		analyzeLabelsFile("C:\\Videos\\cat.mp4");
		return "analiseForenseVideos.xhtml";

	}
public static void analyzeLabelsFile(String filePath) throws Exception {
	try (VideoIntelligenceServiceClient client = VideoIntelligenceServiceClient.create()) {
			// Read file and encode into Base64
		Path path = Paths.get(filePath);
		byte[] data = Files.readAllBytes(path);
		byte[] encodedBytes = Base64.encodeBase64(data);
		
		AnnotateVideoRequest request = AnnotateVideoRequest.newBuilder()
		.setInputContent(ByteString.copyFrom(encodedBytes)).addFeatures(Feature.LABEL_DETECTION).build();

			// Create an operation that will contain the response when the operation
			// completes.
		OperationFuture<AnnotateVideoResponse, AnnotateVideoProgress> response = client.annotateVideoAsync(request);

		System.out.println("Waiting for operation to complete...");
		for (VideoAnnotationResults results : response.get().getAnnotationResultsList()) {
				// process video / segment level label annotations
			System.out.println("Locations: ");
			for (LabelAnnotation labelAnnotation : results.getSegmentLabelAnnotationsList()) {
				System.out.println("Video label: " + labelAnnotation.getEntity().getDescription());
					// categories
				for (Entity categoryEntity : labelAnnotation.getCategoryEntitiesList()) {
					System.out.println("Video label category: " + categoryEntity.getDescription());
				}
					// segments
				for (LabelSegment segment : labelAnnotation.getSegmentsList()) {
					double startTime = segment.getSegment().getStartTimeOffset().getSeconds()
					+ segment.getSegment().getStartTimeOffset().getNanos() / 1e9;
					double endTime = segment.getSegment().getEndTimeOffset().getSeconds()
					+ segment.getSegment().getEndTimeOffset().getNanos() / 1e9;
					System.out.printf("Segment location: %.3f:%.2f\n", startTime, endTime);
					System.out.println("Confidence: " + segment.getConfidence());
				}
			}

				// process shot label annotations
			for (LabelAnnotation labelAnnotation : results.getShotLabelAnnotationsList()) {
				System.out.println("Shot label: " + labelAnnotation.getEntity().getDescription());
					// categories
				for (Entity categoryEntity : labelAnnotation.getCategoryEntitiesList()) {
					System.out.println("Shot label category: " + categoryEntity.getDescription());
				}
					// segments
				for (LabelSegment segment : labelAnnotation.getSegmentsList()) {
					double startTime = segment.getSegment().getStartTimeOffset().getSeconds()
					+ segment.getSegment().getStartTimeOffset().getNanos() / 1e9;
					double endTime = segment.getSegment().getEndTimeOffset().getSeconds()
					+ segment.getSegment().getEndTimeOffset().getNanos() / 1e9;
					System.out.printf("Segment location: %.3f:%.2f\n", startTime, endTime);
					System.out.println("Confidence: " + segment.getConfidence());
				}
			}

				// process frame label annotations
			for (LabelAnnotation labelAnnotation : results.getFrameLabelAnnotationsList()) {
				System.out.println("Frame label: " + labelAnnotation.getEntity().getDescription());
					// categories
				for (Entity categoryEntity : labelAnnotation.getCategoryEntitiesList()) {
					System.out.println("Frame label category: " + categoryEntity.getDescription());
				}
					// segments
				for (LabelSegment segment : labelAnnotation.getSegmentsList()) {
					double startTime = segment.getSegment().getStartTimeOffset().getSeconds()
					+ segment.getSegment().getStartTimeOffset().getNanos() / 1e9;
					double endTime = segment.getSegment().getEndTimeOffset().getSeconds()
					+ segment.getSegment().getEndTimeOffset().getNanos() / 1e9;
					System.out.printf("Segment location: %.3f:%.2f\n", startTime, endTime);
					System.out.println("Confidence: " + segment.getConfidence());
				}
			}
		}
	}
}
}

what is returning on the console 

11:35:14,533 INFO  [stdout] (default task-12) Waiting for operation to complete...
11:52:12,493 INFO  [stdout] (default task-12) Locations:

**Comment by MounaBC** [comment]
I'm having the same issue. Did you find the solution please?

**Comment by joaodematejr** [comment]
No, the problem seems to be in the analyzeLabelsFile class in the Detect.java file, I am waiting for some update by google.

**Comment by nnegrey** [comment]
Does this issue also occur with the file located on GCS or just local files?

`mvn exec:java -DDetect -Dexec.args="labels gs://demomaker/cat.mp4"`

**Comment by MounaBC** [comment]
When I tested this about a month ago, I only had problems with local files. It worked fine on files from gcs. I dont know if any updates were made since then.

**Comment by nnegrey** [comment]
Looked into it. 

I was told that "binary data through gRPC is not supposed to be encode64 at all. Only JSON request needs that."

I've made a PR to fix that sample: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1216

Sorry about that. Let me know if there's anything else!

**Comment by joaodematejr** [comment]
The problem was only when I was going to send the file from the local machine, the tests done directly with the GCS file return the information.
