### ISSUE TITLE
 Google App Engine end point App V1 to V2 Migration issue

### ISSUE THREAD

**Issue by ptrarunprasath** [GoogleCloudPlatform/java-docs-samples#1113]
I have migrated my Google App Engine end point App. There is one jar and war file available in my V1 libs folder. But after I migrated, there is war file only available in my V2 libs folder. Without jar file I cannot proceed my work. Is anything I missed in the migration process ? 

I am follow this document.
https://cloud.google.com/endpoints/docs/frameworks/java/migrating-android

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 378 days. You may reopen this issue if it has been closed in error.
