### ISSUE TITLE
where is Speech-to-Text v1 Stream-recognize way with grpc?

### ISSUE THREAD

**Issue by dtwj03** [GoogleCloudPlatform/java-docs-samples#1116]
The [doc](https://cloud.google.com/speech-to-text/docs/streaming-recognize#speech-streaming-recognize-java) says :

> The Speech-to-Text v1 is officially released and is generally available from the https://speech.googleapis.com/v1/speech endpoint. The Client Libraries are released as Alpha and will likely be changed in backward-incompatible ways. The client libraries are currently not recommended for production use.

but the demo only show client way at com.google.cloud.speech.v1p1beta1 package.

so I want know where is the demo of speech-text with the stable gRPC way  ? 
where is the old version  code ?
or now the stream speech is  Alpha status ,only stand for this demo now?

thanks for answer .

**Comment by nnegrey** [comment]
Hi thanks for looking in. 

The samples as is should work for `v1` if you switch the imports.

We have a PR going on right now to fix this issue: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1212.

Let me know if that helps. :)
