### ISSUE TITLE
Time passed to startTimeOfDay must be UTC

### ISSUE THREAD

**Issue by almegeddon** [GoogleCloudPlatform/java-docs-samples#113]
Sample code from `AwsRequester.java` inaccurately prescribes Pacific Date/Time values here:

```
/**
 * Specify times below using US Pacific Time Zone.
 */
private static final String START_DATE = "YYYY-MM-DD";
private static final String START_TIME = "HH:MM:SS";
```

This bit us when setting up a transfer job recently. Browsing the Schedule source you can see UTC should be passed:

```
/**
 * The time in UTC at which the transfer will be scheduled to start in a day. Transfers may start
 * later than this time. If not specified, transfers are scheduled to start at midnight UTC.
 * @param startTimeOfDay startTimeOfDay or {@code null} for none
 */
public Schedule setStartTimeOfDay(TimeOfDay startTimeOfDay)
```

**Comment by tswast** [comment]
Thank you for your feedback. I'll look into this.

You are referring to the Storage sample at java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java correct?

**Comment by almegeddon** [comment]
Yes, you are correct. I mistakenly left the full package in my original issue.

**Comment by tswast** [comment]
Thanks again for the report. I fix this with https://github.com/GoogleCloudPlatform/java-docs-samples/pull/311

(Sorry it took 6 months, yikes!)
