### ISSUE TITLE
Could not find or load main class com.example.dlp.Inspect

### ISSUE THREAD

**Issue by pmchang** [GoogleCloudPlatform/java-docs-samples#1163]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/dlp

I'm trying to run the DLP inspect command on GCP Cloud shell as shown on the "example - Inspect a string" page:

I ran the following commands in this order:

mvn clean package (Build was successful)
java -cp target/dlp-samples-1.0-jar-with-dependencies.jar com.example.dlp.Inspect -s "My phone number is (123) 456-7890 and my email address is me@somedomain.com"

### Did you change the file? If so, how?
No

## Describe the issue
I keep getting the following error:

“Could not find or load main class com.example.dlp.Inspect”

Do I need to do any steps prior to running the command?

Thank you for your attention.  Any feedback would be greatly appreciated.
Paul

**Comment by averikitsch** [comment]
Hi Paul - Thanks for providing this information. If your build was successful there shouldn't be any additional steps. My first thought is make sure you are in the correct directory (`java-docs-samples/dlp`) or make sure you have correct the path to the file `target/dlp-samples-1.0-jar-with-dependencies.jar`.
