### ISSUE TITLE
not able to execute the DeIdentification file. Please show the correct way to execute it.

### ISSUE THREAD

**Issue by hemantpatil1001** [GoogleCloudPlatform/java-docs-samples#1167]
C:\Users\hemantp\Downloads\java-docs-samples-master\java-docs-samples-master\dlp>   java -cp target/dlp-samples-1.0-jar-with-dependencies.jar com.example.dlp.De
Identification -s "My phone number is (123) 456-7890 and my email address is me@somedomain.com"
Unrecognized option: -s
usage: com.example.dlp.DeIdentification
 -commonAlphabet <arg>
 -contextField <arg>
 -d,--date                 Deidentify dates in a CSV file.
 -dateFields <arg>
 -f,--fpe <arg>            Deidentify with format-preserving encryption.
 -infoTypes <arg>
 -inputCsvPath <arg>
 -keyName <arg>
 -lowerBoundDays <arg>
 -m,--mask <arg>           Deidentify with character masking.
 -maskingCharacter <arg>
 -numberToMask <arg>
 -outputCsvPath <arg>
 -projectId <arg>
 -r,--reid <arg>           Reidentify with format-preserving encryption.
 -surrogateType <arg>
 -upperBoundDays <arg>
 -wrappedKey <arg>

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 313 days. You may reopen this issue if it has been closed in error.
