### ISSUE TITLE
Make sure Travis passes for non-branch pull requests

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/java-docs-samples#117]
I did pull out integration tests already for the cloud-vision repository (though more work is needed https://github.com/GoogleCloudPlatform/cloud-vision/issues/50). It means that Travis can at least run the unit tests for pull requests from other repos, skipping the integration tests.
- [x] Ignore decryption failure.
- [x] Run build without the tests. `mvn verify -DskipTests=true
- [ ] Pull out integration tests (that need service account) and run all but those.

**Comment by tswast** [comment]
Example of failed build from external PR: https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/117868157

**Comment by lesv** [comment]
Obsolete.
