### ISSUE TITLE
Clean up Monitoring V3 sample.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/java-docs-samples#118]
Some minor edits needed for javadocs, also using Truth for some of the assertions would really help in the tests. See PR https://github.com/GoogleCloudPlatform/java-docs-samples/pull/116.

- [x] checkstyle needs to pass on the test classes. Fixed by https://github.com/GoogleCloudPlatform/java-docs-samples/pull/122.
- [x] use Truth for assertions in tests. Fixed by https://github.com/GoogleCloudPlatform/java-docs-samples/pull/122.
- [x] enable tests by default, so that they run in Travis. (Depends on whitelisting the `cloud-samples-tests` project.)
- [x] adjust line breaks to follow "the rectangle rule".
- [x] `<p>` tags in recommended line in javadocs.
- [x] make license headers regular comment, not javadocs.

**Comment by waprin** [comment]
Will circle back to this as soon as get through launch craziness.

**Comment by tswast** [comment]
Some test classes are currently failing checkstyle checks.

```
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ cloud-monitoring-v3-samples ---
[INFO] Starting audit...
/home/travis/build/GoogleCloudPlatform/java-docs-samples/monitoring/v3/src/test/java/CreateCustomMetricTest.java:19: error: 'org.apache.commons.lang3.RandomStringUtils' should be separated from previous import group.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/monitoring/v3/src/test/java/CreateCustomMetricTest.java:53: error: At-clause should have a non-empty description.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/monitoring/v3/src/test/java/CreateCustomMetricTest.java:66: error: At-clause should have a non-empty description.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/monitoring/v3/src/test/java/ListResourcesTest.java:19: error: 'junit.framework.Assert' should be separated from previous import group.
Audit done.
```

https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/116512174

I had planned to enable this check (applying checkstyles to test classes) in PR https://github.com/GoogleCloudPlatform/java-docs-samples/pull/115.
