### ISSUE TITLE
Can not import com.google.cloud.speech.v1p1beta1.SpeechClient

### ISSUE THREAD

**Issue by mmaaww** [GoogleCloudPlatform/java-docs-samples#1206]
I am trying Google Speech v1p1beta1, but encountered the following issue. 

com.google.cloud.speech.v1p1beta1.SpeechClient can not be imported. The rest of classes such as ReconizeConfig, RecognizeResponse are all fine. 

Here is the version that I am using. 
<dependency>
        <groupId>com.google.api.grpc</groupId>
        <artifactId>proto-google-cloud-speech-v1p1beta1</artifactId>
        <version>0.25.0</version>
    </dependency>

**Comment by nnegrey** [comment]
Are you using maven or gradle?
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-speech</artifactId>
    <version>0.62.0-beta</version>
</dependency>
```
