### ISSUE TITLE
cloud storage uploading issue

### ISSUE THREAD

**Issue by sridhar-newsdistill** [GoogleCloudPlatform/java-docs-samples#1214]
## In which file did you encounter the issue?
  google cloud storage image uploading using com.google.api.services.storage.Storage
package.

 java-docs-samples/storage/json-api/src/main/java/StorageSample.java 

## Describe the issue
Mentioned StorageFactory.getService()  unable to locate the method in StorageFactory class

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 267 days. You may reopen this issue if it has been closed in error.
