### ISSUE TITLE
[JAVA][SPEECH-API][DIARIZATION]

### ISSUE THREAD

**Issue by sanadhis** [GoogleCloudPlatform/java-docs-samples#1222]
## In which file did you encounter the issue?
Method transcribeDiarizationGcs in
src/main/java/com/example/speech/Recognize.java

### Did you change the file? If so, how?
I am printing all the words alongside with the corresponding speaker tags:

```java
+        int limit = alternative.getWordsCount();
         System.out.format(
-            "Speaker Tag %s:%s\n",
-            alternative.getWords((alternative.getWordsCount() - 1)).getSpeakerTag(),
+            "Transcript:%s\n",
             alternative.getTranscript());
+        for(int c=0; c < limit; c++){
+          System.out.format(
+            "Word: %s -> Tag: %s\n",
+            alternative.getWords(c),
+            alternative.getWords(c).getSpeakerTag());
+        }
```

## Describe the issue
I am hoping to see the correct values for the speaker tag when iterating through transcripts. But unfortunately i could not see them as I have when using curl command as written here:
https://cloud.google.com/speech-to-text/docs/multiple-voices#speech-diarization-protocol

Below are some samples from the output of the method:
word: "hi"
     -> Tag: 0
    Word: start_time {
      seconds: 1
    }
    end_time {
      seconds: 1
      nanos: 900000000
    }
    word: "I\'d"
     -> Tag: 0
    Word: start_time {
      seconds: 1
      nanos: 900000000
    }
    end_time {
      seconds: 2
      nanos: 100000000
    }

word: "certain"
     -> Tag: 0
    Word: start_time {
      seconds: 6
      nanos: 800000000
    }
    end_time {
      seconds: 6
      nanos: 900000000
    }
    word: "me"
     -> Tag: 0
    Word: start_time {
      seconds: 6
      nanos: 900000000
    }
    end_time {
      seconds: 7
      nanos: 300000000
    }
    word: "which"
     -> Tag: 0
    Word: start_time {
      seconds: 7
      nanos: 300000000
    }
    end_time {
      seconds: 7
      nanos: 500000000
    }

**Notice that all of them are tagged with 0**

**Comment by nnegrey** [comment]
Hi, 

What's your `RecognitionConfig` look like?

**Comment by sanadhis** [comment]
Basically I don't make any changes to the codes. I just pulled them and tried them, expecting the same result with the response from curl command.

```java
      // Configure request to enable enhanced models
      RecognitionConfig config =RecognitionConfig.newBuilder()
              .setEncoding(AudioEncoding.LINEAR16)
              .setLanguageCode("en-US")
              .setSampleRateHertz(8000)
              .setMetadata(metadata) // Add the metadata to the config
              .build();
```

**Comment by nnegrey** [comment]
Ah, I see. 

You also need to set these options in `RecognitionConfig`
```
.setEnableSpeakerDiarization(true)
.setDiarizationSpeakerCount(2)
```

Complete from the sample:
```
RecognitionConfig config =
          RecognitionConfig.newBuilder()
              .setEncoding(AudioEncoding.LINEAR16)
              .setLanguageCode("en-US")
              .setSampleRateHertz(8000)
              .setEnableSpeakerDiarization(true)
              .setDiarizationSpeakerCount(2)
              .build();
```

[Link to complete sample](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/beta/src/main/java/com/example/speech/Recognize.java#L142-L185)

Let me know if that helps! :)

**Comment by sanadhis** [comment]
Hi, sorry apparently I pasted wrong RecognitionConfig. That one was from transcribeFileWithMetadata()

I have exactly the same RecognitionConfig for both transcribeDiarization() and transcribeDiarizationGcs() --like the one you wrote.

I cloned the repository like 4 days ago and the commit was merged 11 days back from today.
I did not made any changes except the making it more verbose like I have mentioned when opening this issue.

Can you reproduce the correct result or making all tests in RecognitionIT passed?
