### ISSUE TITLE
Cannot find resources/config.properties directory

### ISSUE THREAD

**Issue by Shashankk99** [GoogleCloudPlatform/java-docs-samples#1226]
Hi, I am setting up my **pom.xml** file but cannot find the **resources/config.properties** directory in **Eclipse** which is meant for writing `sqlUrl=${sqlURL}`. This file relies on the resource filtering configured in pom.xml which I have already done. Following is the **screenshot** of my current directory where there is no resources/config.properties.

![screen shot 1940-07-16 at 4 17 13 pm](https://user-images.githubusercontent.com/42234824/46605286-a69fa700-cb16-11e8-9001-567d4717826a.png)

I am following official **Google Cloud** documentation https://cloud.google.com/appengine/docs/flexible/java/using-cloud-sql 

Thank you

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 245 days. You may reopen this issue if it has been closed in error.
