### ISSUE TITLE
Need Gradle example for Java samples

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/java-docs-samples#1234]
## Feature request of Java Gradle
I'm able to use the following Gradle file to build [the Java sample](https://cloud.google.com/firestore/docs/quickstart-servers). I should be able to submit a pull request that has the full directory structure of using Gradle with Intellij. Let me know if that interests you. Here's the build.gradle file:

```
version '1.0-SNAPSHOT'

apply plugin: 'java'

apply plugin: 'application'
mainClassName = 'com.dlinkddns.hli.main'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    // Firebase Java SDK
    compile 'com.google.firebase:firebase-admin:6.5.0'

    // Sundial Job Scheduler
    compile 'org.knowm:sundial:2.1.1'
}


```

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 237 days. You may reopen this issue if it has been closed in error.
