### ISSUE TITLE
QuickstartIT.java test works with Oracle JDK but not with Open JDK

### ISSUE THREAD

**Issue by gthar** [GoogleCloudPlatform/java-docs-samples#1266]
## In which file did you encounter the issue?

java-docs-samples/firestore/src/test/java/com/example/firestore/QuickstartIT.java

## Describe the issue

The build step (mvn clean package) works if Oracle JDK is installed (I had Java(TM) SE Runtime Environment (build 1.8.0_191-b12)). If the OpenJDK is used and the Oracle JDK is not installed, it fails to build (but works if the Oracle JDK is at least installed).
The build succeeds if the QuickstartIT.java file is removed.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 203 days. You may reopen this issue if it has been closed in error.
