### ISSUE TITLE
Evaluate coveralls-maven-plugin

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/java-docs-samples#13]
https://github.com/trautonen/coveralls-maven-plugin

**Comment by tswast** [comment]
I believe we are now using this plugin.
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/d5d8f2bb88d9d2a9ba0873bae44f5e4a08594cb8/java-repo-tools/pom.xml#L80

**Comment by tswast** [comment]
https://coveralls.io/github/GoogleCloudPlatform/java-docs-samples
