### ISSUE TITLE
InfiniteStreamRecognize example fails with  OUT_OF_RANGE

### ISSUE THREAD

**Issue by EminAgassi** [GoogleCloudPlatform/java-docs-samples#1302]
## In which file did you encounter the issue?

InfiniteStreamRecognize

### Did you change the file? If so, how?

I have a custom sample very similar to the InfiniteStreamRecognize example

## Describe the issue

when running using the an audio file with over 2.5 minutes of audio, I get the  following error:

com.google.api.gax.rpc.OutOfRangeException: io.grpc.StatusRuntimeException: OUT_OF_RANGE: Exceeded maximum allowed stream duration of 65 seconds.

**Comment by EminAgassi** [comment]
I am using the following Maven config:

<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>google-cloud-speech</artifactId>
	<version>0.70.0-beta</version>
 </dependency>

**Comment by nnegrey** [comment]
Hi, to test and verify your setup, does the sample work as is without modification?

**Comment by EminAgassi** [comment]
let me try and i will let you know
thanks

**Comment by EminAgassi** [comment]
Hi
I did test the sample as is and it does seem to work well over 3 minutes.
I am wondering what could be wrong with my implementation.
I am not streaming from the Mic instead I read the long audio and feed the byte chunks to the streaming api but I do keep the proper wait intervals so if i send 200 mills worth of audio I wait for 200 ms to simulate the real time streaming. My audio file is WAV 16 bit, 16000Hz, mono

**Comment by nnegrey** [comment]
Are you properly reseting the call after less than a minute?
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java#L154-L164

**Comment by EminAgassi** [comment]
Yes I found the problem.
thanks for help. I did not see the soft reset call
