### ISSUE TITLE
CANCELLED: The operation was cancelled.

### ISSUE THREAD

**Issue by 790666134** [GoogleCloudPlatform/java-docs-samples#1307]
在运行 streamingRecognizeFile 方法时出现该错误。请问如何解决？
This error occurred while running the streaming RecognizeFile method. How to solve this problem?

java.util.concurrent.ExecutionException: com.google.api.gax.rpc.CancelledException: io.grpc.StatusRuntimeException: CANCELLED: The operation was cancelled.

![image](https://user-images.githubusercontent.com/20120520/50441206-8bce1900-0934-11e9-962c-e97119ffa161.png)

![image](https://user-images.githubusercontent.com/20120520/50441168-5a554d80-0934-11e9-9978-db24007c518e.png)

![image](https://user-images.githubusercontent.com/20120520/50441181-6e00b400-0934-11e9-82a9-d20836c07e1b.png)

**Comment by nnegrey** [comment]
Hi, do you have any steps on how to reproduce this error?

**Comment by 790666134** [comment]
Currently I am in China, using vpn to debug errors locally.

**Comment by 790666134** [comment]
What is the cause of the error?

**Comment by nnegrey** [comment]
My guess is that there might be an issue with the VPN, beyond that I'm not sure.
