### ISSUE TITLE
Issue of "Non-resolvable parent POM for com.google.cloud:doc-samples:1.0.0: Could not transfer artifact com.google.cloud.samples:shared-configuration:pom:1.0.9" Is still exsisted

### ISSUE THREAD

**Issue by srikanth-padmanabhuni** [GoogleCloudPlatform/java-docs-samples#1309]
See the screen shot

![image](https://user-images.githubusercontent.com/43059655/50534396-fb751b80-0b61-11e9-92e5-503d7efff2a5.png)

After removing the parent tag in the  pom also it is throwing some exceptions

**Comment by nnegrey** [comment]
Hi, just to get a better understanding. :)

Did you clone the whole repo?
Doing a `git pull` on the master branch solve it?

What sample are you running / how are you running it?

**Comment by srikanth-padmanabhuni** [comment]
Yes, I have cloned  the Whole repository and tried my level best to build the Code

**Comment by nnegrey** [comment]
From that image, looks like you are running theses samples? 
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/vision/cloud-client

To build them, does this command work?
`mvn clean package`
