### ISSUE TITLE
Extending Runtime issues

### ISSUE THREAD

**Issue by AIMMOTH** [GoogleCloudPlatform/java-docs-samples#131]
Readme end incomplete "...you will have to edit the and properties in the pom.xml".

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/managed_vms/extending-runtime

There is also missing imports

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/managed_vms/extending-runtime/src/main/java/com/example/managedvms/extendingruntime/FortuneServlet.java

**Comment by lesv** [comment]
Yep - the README needs work.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 914 days. You may reopen this issue if it has been closed in error.
