### ISSUE TITLE
Misspelled System.out.println

### ISSUE THREAD

**Issue by austinfathman** [GoogleCloudPlatform/java-docs-samples#1312]
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/646cbc66252198a8e62616ad4ef0ff17a7de48e1/vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ModelApi.java#L200

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/646cbc66252198a8e62616ad4ef0ff17a7de48e1/vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ModelApi.java#L202

"Tranning" -> "Training"

**Comment by nnegrey** [comment]
@sirtorry or @andrewferlitsch can one of you take a look?

**Comment by nnegrey** [comment]
Solved in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1451. Closing.
