### ISSUE TITLE
Automl tutorial: flower_trainingdata.csv missing

### ISSUE THREAD

**Issue by charbull** [GoogleCloudPlatform/java-docs-samples#1313]
Hello,

Trying to do the following tutorial: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/vision/automl

It seems that this is not existant: **gs://java-docs-samples-testing/flower_traindata.csv**

Thank you

**Comment by nnegrey** [comment]
@sirtorry or @andrewferlitsch  can one of you take a look?

**Comment by nnegrey** [comment]
Solved in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1452
