### ISSUE TITLE
Non-resolvable parent POM

### ISSUE THREAD

**Issue by squm** [GoogleCloudPlatform/java-docs-samples#1316]
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/f1e9dd8c36d3591d461d857806706bcd6bb3ed90/pom.xml#L20

replace with `appengine-doc-samples` perhaps

**Comment by nnegrey** [comment]
Hi the parent pom ID is intended to be `docs-samples`

If there is an issue in the app-engine samples, please feel free to reopen.
