### ISSUE TITLE
AutoML jar file used from IntelliJ Java project - waiting forever for Prediction result (no Exception thrown)

### ISSUE THREAD

**Issue by ares2015** [GoogleCloudPlatform/java-docs-samples#1339]
Hi there,

I have trained my own language model on Google Cloud. I am able to do predictions on this model via Google Console. Then I was experimenting with this Java example:

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/language/automl/src/main/java/com/google/cloud/language/samples/PredictionApi.java

I built jar from com.google.cloud.language.samples. When I run the jar from Windows command line everything is fine. But when I want to use this jar as Maven dependency in my Java Intellij project and I call the jar from my Java code, nothing happens. I am waiting forever for prediction result and no exception is thrown. In other words, call is executed but something is happening under hood without any result. Both calling jar from Windows cmd and calling jar from Intelij happen on the same computer. Is there some additional configuration that I need to add to Java project that uses AutoML jar as dependency?

Thank you in advance for any hint

**Comment by nnegrey** [comment]
@sirtorry or @andrewferlitsch can one of you take a look?

**Comment by nnegrey** [comment]
The samples are expecting a few environment variables that might not be picked up by the jar. 

```
    String projectId = System.getenv("PROJECT_ID");
    String computeRegion = System.getenv("REGION_NAME");
```
