### ISSUE TITLE
Endpoints-frameworks-v2 deprecated java version makes it impossible to deploy

### ISSUE THREAD

**Issue by lopezvit** [GoogleCloudPlatform/java-docs-samples#1348]
## In which file did you encounter the issue?

`java-docs-samples/appengine/endpoints-frameworks-v2/backend/pom.xml`

`java-docs-samples/appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/appengine-web.xml`

### Did you change the file? If so, how?

Changed the java version in both files, in the pom, I changed

```
    <maven.compiler.target>1.7</maven.compiler.target>
    <maven.compiler.source>1.7</maven.compiler.source>
```

into 

```
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
```

in the appengine-web.xml I added:

```
    <runtime>java8</runtime>
```

## Describe the issue

Java 7 is deprecated and can't be deployed in current app engine.

**Comment by averikitsch** [comment]
Thank you for submitting this issue. The sample has been updated.
