### ISSUE TITLE
Necessary Enhancements for Test Automation 

### ISSUE THREAD

**Issue by ghadigaonkarnilesh** [GoogleCloudPlatform/java-docs-samples#1356]
## Describe the issue

Hi ,
I am Test Automation Engineer and we are using Google Vision in our framework. It is really intelligent for some operations but I would like to insist Google team to add below features to make it go to place for all paid users.

1.We need intelligent image comparision feature which can tell % of similarities. There are open java Api which does pixel to pixel comparision but it works if images are exactly same. Any deviation in size etc , it fails.
2. Add feature to interpret various graphs (bar,pie) which are shown as image. This is much awaited feature in Automation testing communities as none of the tool interpret graph. 
3. Add feature to get PDF images.

You guys have all ML intelligence,  I think only perspective from usabilitywise needs to be enhanced.  Together, Lets make vision better!!

Thanks,
Nilesh

**Comment by nnegrey** [comment]
Hi Nilesh, 

Thanks for the feedback, this repo is used to maintain the samples hosted on our docs pages, may I suggest adding Feature Requests here: https://cloud.google.com/support/docs/issue-trackers

On 3. Not sure if this is what you are looking for, but we have support for PDF files: https://cloud.google.com/vision/docs/pdf

Thanks!
Will close this, but feel free to reopen.
