### ISSUE TITLE
IMAGE API BUG - Rotated image is just shown on the original image not the scaled down ones

### ISSUE THREAD

**Issue by Mahdi-Roozbahani** [GoogleCloudPlatform/java-docs-samples#1384]
I rotate the image using:
```
BlobstoreService blobstoreService = BlobstoreServiceFactory.getBlobstoreService();
BlobKey blobKey = blobstoreService.createGsBlobKey("/gs/" + bucket + "/image.jpeg");
Image blobImage = ImagesServiceFactory.makeImageFromBlob(blobKey);
Transform rotate = ImagesServiceFactory.makeRotate(90);
Image rotatedImage = imagesService.applyTransform(rotate, blobImage);

// Write the transformed image back to a Cloud Storage object.
gcsService.createOrReplace(
    new GcsFilename(bucket, "rotatedImage.jpeg"),
    new GcsFileOptions.Builder().mimeType("image/jpeg").build(),
    ByteBuffer.wrap(rotatedImage.getImageData()));
```

When I get the serving url and try to use different scales like s1000 or s500, the result is the un-rotated 
 image not the rotated one. However, for s0, it shows the rotated version.

I wish somebody can answer this question.

**Comment by kurtisvg** [comment]
Hi @Mahdi-Roozbahani,

Are you still experiencing this issue? Is it a problem with a sample in this repository, or something you are trying to do on your own?

**Comment by Mahdi-Roozbahani** [comment]
Hi there,

Yes. It is not related to the repository example. I am sure it is a bug in image api using google cloud. It does not reflect rotated images in the scaled version of an image. I could overcome the problem using this hacky way for now. Please lookup my stackoverflow question (I answered that question myself)

https://stackoverflow.com/questions/55819381/using-images-api-just-the-original-image-gets-rotated-not-the-scaled-images

**Comment by kurtisvg** [comment]
Closing since it's not related to any sample in this directory. 

From the gist of your problem here and in SO, it seems like the AppEngine Image API is working correctly since the image is scaled at "s0". The problem may have been an issue with a cache somewhere, which was resolved when you started using different parameters for the url.
