### ISSUE TITLE
Is a latency between 1 and 2 seconds expected?

### ISSUE THREAD

**Issue by github-contenta** [GoogleCloudPlatform/java-docs-samples#1385]
I followed this tutorial:

https://cloud.google.com/endpoints/docs/frameworks/java/get-started-frameworks-java

Which uses code from this repo, and every call to "_ah/api/echo/v1/echo" is taking between 1 to 2 seconds to respond. Is that expected behavior? It seems really high for any production use.

**Comment by averikitsch** [comment]
To improve latency, you can use warmup requests similar to https://cloud.google.com/appengine/docs/standard/nodejs/configuring-warmup-requests.
