### ISSUE TITLE
Cloud Endpoint - Not accepting Multipart file

### ISSUE THREAD

**Issue by arindam-b** [GoogleCloudPlatform/java-docs-samples#1392]
## In which file did you encounter the issue? 

openapi.yaml 

### Did you change the file? If so, how?

I have more than 30 methods exposed using Cloud Endpoints. All works perfectly except 2 methods where I have following specification, **in short**

From yaml I have marked in bold the particular part where issue occurs. If I remove, file is properly parsed and deployed.

put:
      tags:
      - "Companies"
      description: "Edit a company by id"
      operationId: "editCompanyById"
      consumes:
        - multipart/form-data
      parameters:
      - in: "path"
        name: "id"
        description: "id of the company"
        required: true
        type: "integer"
     **- in: "formData"
        name: "file"
        description: "Company logo"
        type: "file"**
      - in: "formData"
        name: "address"
        description: "Company's address"
        type: "string"

## Describe the issue

So it means will I not be able to upload a file ?

Thanks for your valuable inputs.

**Comment by kurtisvg** [comment]
@arindam-b - Are you still experiencing troubles with this issue? If so, could you please let me know which sample is causing problems? 

If it isn't an issue with the sample, please ask your issue on StackOverflow instead. You can feel free to post a link to your issue on SO as well.

**Comment by arindam-b** [comment]
@kurtisvg  - Yes the issue still persists.

I am attaching the yml file. Please refer line 67 - 70 or 161 -164, which are commented, are meant for multipart file upload. Though I used a workaround to find a solution, it would be good if we can fix it here itself. 

[rcupopenapi.zip](https://github.com/GoogleCloudPlatform/java-docs-samples/files/3275441/rcupopenapi.zip)

**Comment by kurtisvg** [comment]
Closing this since it's not related to any samples in the repo.
