### ISSUE TITLE
Doesnt find StorageFactory.getService

### ISSUE THREAD

**Issue by AndresUrregoAngel** [GoogleCloudPlatform/java-docs-samples#1395]
## Describe the issue

I'm using Java 1.8  along with Maven 3, I have added this dependency: 
```
 <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-storage</artifactId>
            <version>v1-rev20181109-1.28.0</version>
            <exclusions>
                <exclusion> <!-- exclude an old version of Guava -->
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But when I try to perform :

Storage client = StorageFactory.getService();

The `getService` doesnt exist as an option from StorageFactory

**Comment by dzlier-gcp** [comment]
Hi Andres, please excuse the delay. 

I see the problem: StorageFactory is actually a utility class created in the sample, not native from the library. Please see [this class](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/storage/json-api/src/main/java/StorageFactory.java) for how to instantiate a Storage client in the meantime, and we will look into how to make this more clear in documentation.
