### ISSUE TITLE
Pubsub Client doesn't work with Service Account scoped to PubSub admin role

### ISSUE THREAD

**Issue by ankitsultana** [GoogleCloudPlatform/java-docs-samples#1419]
## In which file did you encounter the issue?

Any example under [pubsub/cloud-client/src/main/java/com/example/pubsub](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/pubsub/cloud-client/src/main/java/com/example/pubsub), if you service-account with permissions scoped to Pub/Sub Admin.

### Did you change the file? If so, how?

No

## Describe the issue

If you create a service-account with permissions scoped to "Pub/Sub Admin", then you won't be able to create a topic, create a subscription, publish or subscribe, and you will get a permission-denied error.

```
$ java -cp target/pubsub-google-cloud-samples-1.0.11-jar-with-dependencies.jar com.example.pubsub.CreateTopicExample "new-topic-z"
PERMISSION_DENIEDfalseTopic project-name:new-topic-z created.
```

I tried the same program with a service-account that has full-access to my GCP Project, and it ran successfully.

**Note:** There is a minor bug in the code in [L47 of CreateTopicExample](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java#L47), where it prints that the topic was created, irrespective of the exception that was thrown earlier. As an example, in my case the exception is thrown because of permission-denied, but it still prints that the topic is created.

**Comment by hongalex** [comment]
Hi @ankitsultana,

From some preliminary testing, I could not replicate this issue with a new account with a service account with "Pub/Sub Admin" permissions. Can you try creating a new service account and try to create a topic from that? Another thing to giving "Pub/Sub Editor" permissions to a new service account see if that fails too.

Thanks for pointing out the bug with printing success even on failure cases; we'll get that fixed soon.

**Comment by ankitsultana** [comment]
Weird, I tried it with a new service-account and it seems to work now. Closing this issue for now. If I encounter it again, I will ping here. Thanks for your reply!
