### ISSUE TITLE
Datastore 500 errors still cause frequent test flakes

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/java-docs-samples#144]
We often get errors like these, which are not caused by the way we are using Datastore, but the fact that Datastore calls can occasionally fail.

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.792 sec <<< FAILURE! - in com.google.appengine.sparkdemo.UserControllerTest
com.google.appengine.sparkdemo.UserControllerTest  Time elapsed: 0.792 sec  <<< ERROR!
com.google.gcloud.datastore.DatastoreException: 
Backend Error
```

I think ideally we would use the local emulator for Datastore unit tests, as this makes the tests faster and more hermetic.

It would also be nice for our tracking to have an "integration test" which *does* make the real call. We can ignore failures caused by the system, but would be good to track how often they fail versus pass.

**Comment by tswast** [comment]
Closing for now, as it seems to have settled down some. (Maybe due to a change in the gcloud-java retry logic)

**Comment by lesv** [comment]
I asked gcloud-java team to match the Datastore SLA in their retry logic.
