### ISSUE TITLE
Add examples for recording and providing speed to text from microphone

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/java-docs-samples#1457]
## Describe the issue

copied from https://github.com/googleapis/google-cloud-java/issues/4932:

> I am talking about google-cloud-speech
> 
> Even being an experienced Java Developer i am struggling a lot with this repository ... there are not many examples on how to use it ... if not any at all .
> 
> Add examples for recording and providing speed to text from microphone embedded to the > computer .
>
> Like i have done this but it's not working properly and it's very slow :
>
> goxr3plus/java-google-speech-api#4
>
> Add more examples on how to use the library please.

**Comment by nnegrey** [comment]
Checkout this sample on using a microphone for streaming!
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java
Hope this helps! 

Going to close this, but feel free to reopen if you need more help!

**Comment by goxr3plus** [comment]
@nnegrey  Thank you :) , although a senior Java develop the example for Microphone Streaming is gosh so complex.

I hope you simplify the library on next versions . With all that complexity i see i expect more power from this library but ... too complex.... too complex...
