### ISSUE TITLE
Broken IOT tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1482]
## Describe the issue

[Test Fusion 1](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/569be8a6-9318-4272-a25b-ad463abef9a4/1561316765710/build%20%2375/Targets?target=github%2Fjava-docs-samples%2Fiot%2Fapi-client%2Fend-to-end-example%2Ftarget%2Fsurefire-reports&drilldownTab=tests)

[Test Fusion 2](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/569be8a6-9318-4272-a25b-ad463abef9a4/1561316765710/build%20%2375/Targets?target=github%2Fjava-docs-samples%2Fiot%2Fapi-client%2Fmanager%2Ftarget%2Ffailsafe-reports&drilldownTab=tests)

**Comment by gguuss** [comment]
There is a limit of 100 registries and if the tests get rerun without cleaning up, we'll hit this limit. I'll see what can be done to clean them up before running the tests.

**Comment by gguuss** [comment]
Reopening until I've resolved the resource leak.

**Comment by gguuss** [comment]
Fixed in this PR https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1487
