### ISSUE TITLE
Broken AutoML tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1483]
## Describe the issue

[Test Fusion - Translate](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/569be8a6-9318-4272-a25b-ad463abef9a4/1561316765710/build%20%2375/Targets?target=github%2Fjava-docs-samples%2Ftranslate%2Fautoml%2Ftarget%2Ffailsafe-reports&drilldownTab=tests)

[Test Fusion - Language](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/569be8a6-9318-4272-a25b-ad463abef9a4/1561316765710/build%20%2375/Targets?target=github%2Fjava-docs-samples%2Flanguage%2Fautoml%2Ftarget%2Ffailsafe-reports&drilldownTab=tests)

**Comment by beccasaurus** [comment]
We're re-authoring (generating) these ~ will TAL

**Comment by czahedi** [comment]
Noah/Torry, how go the AutoML tests?

**Comment by nnegrey** [comment]
I think I can go delete those samples now that those are GA'd products and the samples have been updated. But let me check that tomorrow for docs dependencies and I'll create a CL to update them now that they are all merged.

**Comment by nnegrey** [comment]
Language I think I fixed in October. 
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1599

Translate in Nov:
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1606

Going to close.

**Comment by nnegrey** [comment]
Can't delete these snippets yet as too many different localization docs still rely on them.
