### ISSUE TITLE
Flaky Vision tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1485]
## In which file did you encounter the issue?

vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSearchIT.java

## Describe the issue

[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/569be8a6-9318-4272-a25b-ad463abef9a4/1561316765710/build%20%2375/Targets?target=github%2Fjava-docs-samples%2Fvision%2Fproduct-search%2Fcloud-client%2Ftarget%2Ffailsafe-reports&drilldownTab=tests)

**Comment by nnegrey** [comment]
It looks like the dataset I created somehow got deleted, I just added it again to the API. 

I've re-ran the tests multiple times, to make sure I didn't miss any code that deletes this. 

It shouldn't keep happening now that there is a permanent named dataset, but I could've missed a delete call somewhere, I don't think so though.
