### ISSUE TITLE
Broken Spanner tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1491]
## In which file did you encounter the issue?
Test file: `spanner/leaderboard/complete/src/test/java/com/google/codelabs/AppTest.java`

## Describe the issue

[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fcontinuous/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fcontinuous/KOKORO/092ee28c-7372-428d-adeb-bfbf76460b0a/1561474437114/build%20%2373/Targets?target=github%2Fjava-docs-samples%2Fspanner%2Fleaderboard%2Fcomplete%2Ftarget%2Fsurefire-reports&drilldownTab=tests)

**Comment by olavloite** [comment]
@averikitsch or @skuruppu Could one of you copy-paste the error from Fusion into this issue? I cannot access the build logs on Fusion.

**Comment by olavloite** [comment]
This problem was fixed in https://github.com/googleapis/google-cloud-java/pull/5952. That PR was merged on 2019-08-01 and this flaky failure occurred on 2019-06-25, so this should not happen anymore. If it does, then please re-open.
