### ISSUE TITLE
Update gcloud-java dependency to 0.17

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/java-docs-samples#150]
This includes some bug fixes that we care about, https://github.com/GoogleCloudPlatform/gcloud-java/issues/827

http://mvnrepository.com/artifact/com.google.gcloud/gcloud-java/0.1.7

I'll do the same for getting-started-java. I will look at what it takes to get a script to auto-run for this, too.

**Comment by tswast** [comment]
This script could come in handy. https://github.com/GoogleCloudPlatform/java-docs-samples/pull/130

**Comment by ajkannan** [comment]
Using a script to update the gcloud-java version seems fine to me as long as it's coupled with somebody reading the gcloud-java release notes to see if anything significant has changed pertaining to the code or javadoc in the sample.
