### ISSUE TITLE
Migrate App Engine standard environment Google Analytics sample here

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/java-docs-samples#151]
I see that the [App Engine documentation](https://cloud.google.com/appengine/docs/java/google-analytics) references [appengine-google-analytics-java](https://github.com/GoogleCloudPlatform/appengine-googleanalytics-java/blob/master/src/main/java/com/google/appengine/analytics/tracking/GoogleAnalyticsTracking.java) instead of the [analytics sample in this repository](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine/analytics/src/main/java/com/example/appengine/analytics/AnalyticsServlet.javahttps://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine/analytics/src/main/java/com/example/appengine/analytics/AnalyticsServlet.java).

It probably doesn't make sense to have two analytics samples that seem to serve the same purpose. While we're at it, it would be helpful to improve the documentation. Right now the code that is included looks out-of-place. It'd be better to break it up and talk about the different concepts separately.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 1161 days. You may reopen this issue if it has been closed in error.
