### ISSUE TITLE
speech cloud client sample: how to setup project Id?

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1514]
in the speech/cloud-client sample, either in local mode or cloud shell, I cannot run it, and get instead:

[ERROR] testRecognizeFile(com.example.speech.RecognizeIT)  Time elapsed: 0.158 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not suppo
rted by the speech.googleapis.com. We recommend that most server applications use service accounts instead. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/aut
hentication/.

There is no readme section on what to do or easy way to understand what to change in the sample to make it work...

**Comment by kurtisvg** [comment]
@nnegrey -- should these samples have a set up section?

**Comment by nnegrey** [comment]
Most definitely! 

I'll add a quick thing that links to this step. https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries#before-you-begin

@ludoch, you'll need to follow the "Before you begin" section on that link above. Sorry the README doesn't have any info on this. I'll add a Pre-Req step now. 

Let me know if you need anything else.
