### ISSUE TITLE
embedded server logging config problem (not sure if related)

### ISSUE THREAD

**Issue by peterweb2005** [GoogleCloudPlatform/java-docs-samples#1517]
thanks,

after migrate to java11 (may because of embedded server as packed jar),
the log message is hard to read in log viewer:
https://console.cloud.google.com/logs/viewer

previously is 1 message 1 line, but now 2 lines:
A 2019-07-18T11:01:30.682397Z Jul 18, 2019 11:01:30 AM test.HelloServlet doGet 
A 2019-07-18T11:01:30.682451Z INFO: doGet() 
it is only 1 of the results, i tried many config approaches

question is:
is it really jetty or spring logging problem? so that i can fix it by good logging config?
or
i CANT, because content of following links about logging have big diff from java11 to java8:
(java11)
https://cloud.google.com/appengine/docs/standard/java11/writing-application-logs
(java8)
https://cloud.google.com/appengine/docs/standard/java/logs/

thanks

**Comment by nnegrey** [comment]
@kurtisvg, I'm not super familiar with app engine. Is there someone better to reassign this to?

**Comment by kurtisvg** [comment]
Closing this since it doesn't seem to be related to any specific sample. 

Hi @peterweb2005,

Generally if you are using `java.util.logger`, you can either customize or replace the `SimpleFormatter` class to use whatever format you want. Take a look at the answers [from this SO post](https://stackoverflow.com/questions/7911186/how-do-i-suppress-the-date-line-from-2-line-java-util-logging-output) for examples.

**Comment by averikitsch** [comment]
@peterweb2005, I'm not sure what is causing this issue, but you can solve this with filtering.
* HTTP request logs are sent to Stackdriver Logging under the `request_log` log.
* All STDOUT and STDERR output is sent to Stackdriver Logging under `stdout` and `stderr`.

To filter your logs, in the console next to [basic selector (where you can choose your GAE app)](https://cloud.google.com/logging/docs/view/basic-filters), you can select what level of logging you want to view.

**Comment by peterweb2005** [comment]
may not 

> SimpleFormatter

not care console log, but the appengine log viewer
previous (jetty) console log 1 message in 2 lines, but appengine log viewer is 1 line (i guess the appengine (not embedded) jetty do the format, may decompile the lib and solve my problem)

**Comment by peterweb2005** [comment]
i found that config file can affect these (server) logger level:

```
#org.eclipse.jetty.LEVEL=WARN
org.eclipse.jetty.LEVEL=INFO
#org.eclipse.jetty.LEVEL=DEBUG
```

but not these (logger of application):
```
java.LEVEL=DEBUG
com.example.LEVEL=DEBUG
test.LEVEL=DEBUG
```

tried logger of slf4j, jul and "jetty util's StdErrLog or JavaUtilLog"
