### ISSUE TITLE
ClientSocket not a valid WebSocket

### ISSUE THREAD

**Issue by Haimonti** [GoogleCloudPlatform/java-docs-samples#1518]
I am trying to execute the code as is on the GCP. It builds successfully, but throws the following error on execution. Any help is really appreciated!

SendServlet doPost: Error sending message over socket: ClientSocket is not a valid WebSocket object.  Object must obey one of the following rules:  (SendServlet.java:52)
(1) class implements org.eclipse.jetty.websocket.api.WebSocketListener or 
(2) class is annotated with @org.eclipse.jetty.websocket.api.annotations.WebSocket

**Comment by lesv** [comment]
Please ask questions on StackOverflow, if you still need an answer, you may reopen this issue.
