### ISSUE TITLE
runtime java11 logging problem (not sure if related)

### ISSUE THREAD

**Issue by peterweb2005** [GoogleCloudPlatform/java-docs-samples#1519]
thanks

previously (java8, jetty not embedded) only 2 types of log: activity, request
and in the log viewer:
https://console.cloud.google.com/logs/viewer
clicked the request log, can see the "logs in the request", eg:
(java util logging style)
> 2019-07-19 18:45:21.456 HKT
"package & class name" process: process()

but now (java11, jetty embeded):
(logback style, even jul has the same problem)
>(request log)
A 2019-07-19T09:40:35.696266Z GET 200 92 B 7 ms Chrome 75 /test GET 200 92 B 7 ms Chrome 75 5d31901300ff0a9fcad64ef7ac0001737e70657465722d746573742d6669726562617365000131000100
>(stdout)
A 2019-07-19T09:40:35.701389Z 09:40:35.701 [qtp1538399081-17] INFO  com.example.test.TestServlet:21 - doGet() 

how can it use the java8 format? ie:
a: can click the request log and see the "logs in the request"
b: can i use logback and properly show the log level;
previous use jul because the log level can't properly integrate (mainly the color issue, red mean alert, but only jul log level can affect the appengine log viewer)

thanks

**Comment by nnegrey** [comment]
@peterweb2005 it sounds like all three of these issues are related to the same thing you are working on, is that correct?


https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1517
https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1517
https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1520

**Comment by peterweb2005** [comment]
1,2 are the same

summary, problems are:
1, is it any logic to organize app log to request log?
2, api call for memcache and datastore through the sdk seems failed

**Comment by peterweb2005** [comment]
seems need to create thread from jetty in custom way??

as in java8:
https://cloud.google.com/appengine/docs/standard/java/runtime

**Comment by peterweb2005** [comment]
may be close

i got it, the 2 questions are because java11 need gcloud not appengine
