### ISSUE TITLE
[env: standard] NullPointerException: No API environment is registered for this thread

### ISSUE THREAD

**Issue by peterweb2005** [GoogleCloudPlatform/java-docs-samples#1520]
thanks

still showing this is standard environment in version page, but error for flexible environment?

(datastore)
```
java.lang.NullPointerException: No API environment is registered for this thread. at com.google.appengine.api.datastore.DatastoreApiHelper.getCurrentAppId(DatastoreApiHelper.java:150) at com.google.appengine.api.datastore.DatastoreApiHelper.getCurrentAppIdNamespace(DatastoreApiHelper.java:166) at com.google.appengine.api.datastore.Key.<init>(Key.java:92) at com.google.appengine.api.datastore.Key.<init>(Key.java:82) at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:81) at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:74) at com.googlecode.objectify.Key.<init>(Key.java:97) at com.googlecode.objectify.Key.<init>(Key.java:86) at com.googlecode.objectify.Key.create(Key.java:34) at code.framework.gae.app.JdoApiBase1.get(JdoApiBase1.java:52) at 
```

also when getting data from memcache, but hard to consolidate the logs

thanks

**Comment by gguuss** [comment]
Do you have more context around what's going on here? Are you using a sample from the java-docs-samples repo?  What's the path to the sample that is not working?

**Comment by peterweb2005** [comment]
sorry, please close

seems java11 need gcloud api instead of appengine api

**Comment by kimhSirtrack** [comment]
Hi @peterweb2005 , I'm trying to migrate from Java8 to Java11 with OpenJDK and encoutnered same issue like yours. Can you guide me how can I set up gcloud api instead of appengine api through pom.xml?

**Comment by mhopkins-dynactive** [comment]
> Hi @peterweb2005 , I'm trying to migrate from Java8 to Java11 with OpenJDK and encoutnered same issue like yours. Can you guide me how can I set up gcloud api instead of appengine api through pom.xml?

SAME.
