### ISSUE TITLE
Detect Intent from audio file always return empty response

### ISSUE THREAD

**Issue by shaileshkulkarni** [GoogleCloudPlatform/java-docs-samples#1529]
Hello,

I have edited default welcome intent in the Dialogflow project to respond 'Welcome to ABC Inc'.

Tried the examples given in the following links
https://cloud.google.com/dialogflow/docs/detect-intent-audio#detect-intent-audio-java

https://cloud.google.com/dialogflow/docs/detect-intent-audio#detect-intent-audio-nodejs

In both cases it simply returns empty response. No intent is detected.
However in the Dialogflow History section also, it does not showup anything indicating that it got invoked from test client.

Also I have enabled webhook and trying to just put log message indicating it got called. But its not logging over there confirming that its not getting invoked.

The input audio file is in mp3 format only. I also tried with the opus file format with simple "Hello" audio for "en-US".

I tried to play mp3 and opus file and I could clearly hear "Hello", there was little background noise but that should not be an issue. I think, when its trying to so Speech to text its not able to get anything and hence its not getting invoked for dialogflow for detection. But thats my guess.

Can someone help what is missing over here?

Thanks,
Shailesh

**Comment by shaileshkulkarni** [comment]
This is the Java code.

package test;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.UUID;

import com.google.cloud.dialogflow.v2.AudioEncoding;
import com.google.cloud.dialogflow.v2.DetectIntentRequest;
import com.google.cloud.dialogflow.v2.DetectIntentResponse;
import com.google.cloud.dialogflow.v2.InputAudioConfig;
import com.google.cloud.dialogflow.v2.QueryInput;
import com.google.cloud.dialogflow.v2.QueryResult;
import com.google.cloud.dialogflow.v2.SessionName;
import com.google.cloud.dialogflow.v2.SessionsClient;
import com.google.protobuf.ByteString;

public class DetectFromAudio {
	public static void main(String[] args) {
		System.out.println("Google Dialogflow API Testing");
		
		/*
		 * for(Entry<String, String> env : System.getenv().entrySet()) {
		 * System.out.println(env.getKey() + " : " + env.getValue()); }
		 */
		
		
		String projectId = "testagent-265c0";
		String audioFilePath = "C:/DialogflowTest/hello.mp3";
		String sessionId = UUID.randomUUID().toString();
		String languageCode = "en-US";
		
		try {
			QueryResult queryResult = detectIntentAudio(projectId, audioFilePath, sessionId, languageCode);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}
	
	public static QueryResult detectIntentAudio(
		    String projectId,
		    String audioFilePath,
		    String sessionId,
		    String languageCode)
		    throws Exception {
		  // Instantiates a client
		  try (SessionsClient sessionsClient = SessionsClient.create()) {
		    // Set the session name using the sessionId (UUID) and projectID (my-project-id)
		    SessionName session = SessionName.of(projectId, sessionId);
		    System.out.println("Session Path: " + session.toString());

		    // Note: hard coding audioEncoding and sampleRateHertz for simplicity.
		    // Audio encoding of the audio content sent in the query request.
		    AudioEncoding audioEncoding = AudioEncoding.AUDIO_ENCODING_LINEAR_16;
		    int sampleRateHertz = 16000;

		    // Instructs the speech recognizer how to process the audio content.
		    InputAudioConfig inputAudioConfig = InputAudioConfig.newBuilder()
		        .setAudioEncoding(audioEncoding) // audioEncoding = AudioEncoding.AUDIO_ENCODING_LINEAR_16
		        .setLanguageCode(languageCode) // languageCode = "en-US"
		        .setSampleRateHertz(sampleRateHertz) // sampleRateHertz = 16000
		        .build();

		    // Build the query with the InputAudioConfig
		    QueryInput queryInput = QueryInput.newBuilder().setAudioConfig(inputAudioConfig).build();

		    // Read the bytes from the audio file
		    byte[] inputAudio = Files.readAllBytes(Paths.get(audioFilePath));

		    // Base 64 encoding
//		    inputAudio = Base64.getEncoder().encode(inputAudio);
		    
		    // Build the DetectIntentRequest
		    DetectIntentRequest request = DetectIntentRequest.newBuilder()
		        .setSession(session.toString())
		        .setQueryInput(queryInput)
		        .setInputAudio(ByteString.copyFrom(inputAudio))
		        .build();

		    // Performs the detect intent request
		    DetectIntentResponse response = sessionsClient.detectIntent(request);

		    // Display the query result
		    QueryResult queryResult = response.getQueryResult();
		    System.out.println("====================");
		    System.out.format("Query Text: '%s'\n", queryResult.getQueryText());
		    System.out.format("Detected Intent: %s (confidence: %f)\n",
		        queryResult.getIntent().getDisplayName(), queryResult.getIntentDetectionConfidence());
		    System.out.format("Fulfillment Text: '%s'\n", queryResult.getFulfillmentText());

		    return queryResult;
		  }
		}
}

**Comment by shaileshkulkarni** [comment]
Base64 encoding or not encoding does not matter in the output.

**Comment by gguuss** [comment]
Reassigning, I have not worked on DialogFlow.

**Comment by nnegrey** [comment]
Did you modify the `AudioEncoding` to MP3?

**Comment by manhaha** [comment]
Hi @nnegrey  ,

I have exactly the same question with a sample 'book-a-room.wav'. Tried many times with AudioEncoding.AUDIO_ENCODING_LINEAR_16/ AudioEncoding.AUDIO_ENCODING_FLAC / Unspecified, still getting null intent response. Anything I missed?

Or I need to enable Google Cloud Speech-To-Text service in order to use Dialogflow v2 detect intent?

Could you please give me some clue?
