### ISSUE TITLE
Cloud Pub/Sub example could result in message loss

### ISSUE THREAD

**Issue by kamalaboulhosn** [GoogleCloudPlatform/java-docs-samples#1531]
## In which file did you encounter the issue? 
java-docs-samples/pubsub/cloud-client/src/main/java/com/example/pubsub/SubscriberExample.java

### Did you change the file? 
No.

## Describe the issue

The example presented does not exhibit best practices for using Cloud Pub/Sub. The message is acknowledged as soon as it is added to the BlockingQueue. However, since the queue is not persistent, a crash of the task would result in message loss for any messages added to the queue that were not yet processed. I understand that it is a simple example, but we should make sure we are demonstrating best practices for using Pub/Sub.

**Comment by nnegrey** [comment]
@anguillanneuf, do you know who would be the right person to take a look at this?

**Comment by kamalaboulhosn** [comment]
I took a stab at it in #1534.

**Comment by anguillanneuf** [comment]
Thank you @kamalaboulhosn so much for reporting this.

**Comment by anguillanneuf** [comment]
Closing now as the PR has been merged. 

Message loss can be dealt by a blocking queue with `nack` logic and a processing timeout. One of Kamal's commits shows exactly how to do that in the PR.

**Comment by kamalaboulhosn** [comment]
@anguillanneuf You don't need a blocking queue to handle message loss. The only thing required to avoid message loss is that the ack needs to happen after all processing of the message is complete. In the example prior to this PR, ack was being called at a point that was potentially before the message had been processed after being added to the blocking queue.

**Comment by anguillanneuf** [comment]
Thanks for calling this out!
