### ISSUE TITLE
Broken Container Analysis Tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1532]
## In which file did you encounter the issue?

File: `container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java`
Test: `testPubSub`

## Describe the issue

[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/c3c8a9a4-b562-4f9b-8c97-d24d9ba1a042/1564945564751/build%20%23117/Targets?target=github%2Fjava-docs-samples%2Fcontainer-registry%2Fcontainer-analysis%2Ftarget%2Fsurefire-reports&drilldownTab=tests)

**Comment by DanSanche** [comment]
The PR I submitted should have fixed this
