### ISSUE TITLE
Create README file for App Engine Java 8 sample

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1539]
Nothing under
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/analytics

**Comment by kurtisvg** [comment]
@averikitsch - The sample in question looks like it's from 2015 and doesn't have any region tags. Should it have a README, or can it just be removed entirely?

**Comment by averikitsch** [comment]
Based on issue #151, it might be good to keep this sample and add it to the docs.
