### ISSUE TITLE
Need an updated Cloud Tasks v2 sample

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1544]

**Comment by ludoch** [comment]
See https://github.com/GoogleCloudPlatform/java-docs-samples/blob/b407ebfa5e53d35bbe290cda1ebb08f28eca06cd/tasks/src/main/java/com/example/task/CreateHttpTask.java#L22
Cloud Tasks is now v2.
Some api changes regarding httprequest needed...
Or maybe it was in a beta release, and never GA?
This is quite confusing...

**Comment by averikitsch** [comment]
Hi @ludoch, HTTP targets for Cloud Tasks is still in beta. The client libraries across all languages are using this format.
