### ISSUE TITLE
Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. 

### ISSUE THREAD

**Issue by hlguo** [GoogleCloudPlatform/java-docs-samples#1570]
## Describe the issue
I call the api as below:
```
curl -s -H "Content-Type: application/json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    https://speech.googleapis.com/v1p1beta1/speech:recognize \
    --data '{
    "config": {
        "encoding":"LINEAR16",
        "languageCode": "en-US",
        "alternativeLanguageCodes": ["fr-FR", "de-DE"],
        "model": "command_and_search"
    },
    "audio": {
        "uri":"gs://cloud-samples-tests/speech/commercial_mono.wav"
    }
}' > multi-language.txt
```
but I got the message as below:
```
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:764086051850'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/764086051850/apiui/credential"
          }
        ]
      }
    ]
  }
}
```
what's wrong?

**Comment by nnegrey** [comment]
Hi, it looks like you have possibly 2 different error messages? 

From your title it seems to be an IAM issue with auth. Worth making sure you completed all the steps on this page: https://cloud.google.com/speech-to-text/docs/quickstart-protocol

For the 2nd error in the body of your issue, a `RESOURCE_EXHAUSTED` / Quota exceeded error is potentially from calling the API too much and exceeding the quota, but that would have to mean you are sending more than 900 requests in a minute as described here: https://cloud.google.com/speech-to-text/quotas#request_limits

Are you calling that only once via the command line and which page or file are you using?

**Comment by hlguo** [comment]
yes, I completed all the steps as you suggested in the 1st, then get the error as the 2nd error. I only call once.  my google account have not bind a credit card, is this the root cause?
![image](https://user-images.githubusercontent.com/10663799/64061724-41aedd00-cc11-11e9-9650-70ce57613eac.png)

**Comment by hlguo** [comment]
> Hi, it looks like you have possibly 2 different error messages?
> 
> From your title it seems to be an IAM issue with auth. Worth making sure you completed all the steps on this page: https://cloud.google.com/speech-to-text/docs/quickstart-protocol
> 
> For the 2nd error in the body of your issue, a `RESOURCE_EXHAUSTED` / Quota exceeded error is potentially from calling the API too much and exceeding the quota, but that would have to mean you are sending more than 900 requests in a minute as described here: https://cloud.google.com/speech-to-text/quotas#request_limits
> 
> Are you calling that only once via the command line and which page or file are you using?
please help me!

**Comment by nnegrey** [comment]
Ah. So it looks like your gcloud is potentially trying to access a project you don't have access to. 

The link: https://console.developers.google.com/project/764086051850/apiui/credential

Is the wrong Project Id (as you noted). 

Can you verify your gcloud is on the right configuration?
`gcloud config configurations list`

Should output something like this:
```
NAME     IS_ACTIVE    ACCOUNT             PROJECT               DEFAULT_ZONE  DEFAULT_REGION
default  True         your_username       your_project_id
```

From your images, it looks like you created a `configuration` called: `testlanguage` can you verify that the `IS_ACTIVE` field is set to True?

If not, you can activate it with `gcloud config configurations activate testlanguage`

**Comment by hlguo** [comment]
the project is active as below:
![image](https://user-images.githubusercontent.com/10663799/64218124-f63b4e00-cef2-11e9-988d-30cef4b0dba7.png)

& the cloud as below:
![image](https://user-images.githubusercontent.com/10663799/64218661-31d71780-cef5-11e9-98d6-10713ed11910.png)

so it was very confused!

**Comment by nnegrey** [comment]
Can you run `gcloud auth application-default login` and make sure you have that set to the right project?

Also do you have `GOOGLE_APPLICATION_CREDENTIALS` set to anything?

**Comment by hlguo** [comment]
yes,many thanks, the speech:recognize work now.
