### ISSUE TITLE
How to call StreamingRecognize method in multi-thread, every thread with a different stream source.

### ISSUE THREAD

**Issue by hlguo** [GoogleCloudPlatform/java-docs-samples#1571]
## Describe the issue

If I call StreamingRecognize method in multi-threads,  the stream in every thread sent to StreamingRecognize method is from different client.  such as many Android devices send voice stream to CDN server, then CDN server send the stream to StreamingRecognize method at the same time, for StreamingRecognize method how to differentiate the stream from which Android device?  
![image](https://user-images.githubusercontent.com/10663799/64346397-a197f000-d024-11e9-9f2b-ee20c02814ed.png)

Is SpeechClient singleton or not? if not maybe I can create a SpeechClient instance in every thread to solve this problem?

**Comment by nnegrey** [comment]
Assuming they are coming from Android Devices (or multiple threads) as long as each one is using a different client, you should be able to send multiple different streams. 

The line highlighted above, is saying that before you start streaming data to the service, you must first send a config. 

As seen here: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/Recognize.java#L659-L673

The first message sent is the config, to tell the streaming service what to expect, then all subsequent requests are the actual data. 

Does that answer your question?
(I'm going to verify if you need separate clients or not)

**Comment by nnegrey** [comment]
Update: turns out I was wrong, one client should be able to open multiple streaming requests on different threads.

**Comment by hlguo** [comment]
> Update: turns out I was wrong, one client should be able to open multiple streaming requests on different threads.

OK, many many thanks!
