### ISSUE TITLE
Java11 samples should all listen to port $PORT and not 8080

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1593]
For example, the quikcstart sample used by our docs is java-docs-samples/appengine-java11/springboot-helloworld
and emit this nasty (I might make it nicer soon) message:

App is listening on port 8080, it should instead listen on the port defined by the PORT environment variable. As a consequence, nginx cannot be started. Performance may be degraded. Please listen on the port defined by the PORT environment variable.

**Comment by averikitsch** [comment]
Samples have been re-evaluated and updated.
