### ISSUE TITLE
java11 apps: entrypoints with -cp * should use -cp "*"

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1613]
It seems that https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java11/gaeinfo/src/main/appengine/app.yaml#L17

did not work for me.
I had to put "*" instead of * in the classpath... Maybe this is a regression with the Ubuntu OpenJDK?

See https://stackoverflow.com/questions/219585/including-all-the-jars-in-a-directory-within-the-java-classpath

I guess all java11 samples affected would need to be updated.

**Comment by averikitsch** [comment]
Thanks Ludo for finding this bug.
