### ISSUE TITLE
Google-cloud-speech “detecting language spoken automatically” feature detecting only one language

### ISSUE THREAD

**Issue by hlguo** [GoogleCloudPlatform/java-docs-samples#1630]
## Describe the issue

I am trying to use the beta version of google-cloud-speech speech-to-text feature with "Detecting language spoken automatically" feature. The problem is if I give 2 alternate languages (in my case "en-US", "zh"), then it always detect english speech as  cmn-hans-cn, how to solve this problem.?

my code is:
```
public void onResponse(StreamingRecognizeResponse response) {
   responses.add(response);
   if(!response.getResultsList().isEmpty()) {
      StreamingRecognitionResult result = response.getResultsList().get(0);
       if (result.getIsFinal()) {
          SpeechRecognitionAlternative alternative = result.getAlternativesList().get(0);
          System.out.printf("LanguageCode: %s, Transcript : %s\n", result.getLanguageCode(), 
                                         alternative.getTranscript());
       }
   }
}
```
the print are always as:
LanguageCode: cmn-hans-cn, Transcript : Good night
LanguageCode: cmn-hans-cn, Transcript : my spoken English is very bad
sometimes the print is right:
LanguageCode: en-us, Transcript : my spoken English is very five

**Comment by kurtisvg** [comment]
@nnegrey - PTAL

**Comment by hlguo** [comment]
> What does your `RecognitionConfig` object look like?

languageList.add("zh");
        RecognitionConfig recognitionConfig =
                RecognitionConfig.newBuilder()
                        .setEncoding(RecognitionConfig.AudioEncoding.LINEAR16)
                        .setLanguageCode("en-US")
                        .setSampleRateHertz(16000)
                        .addAllAlternativeLanguageCodes(languageList)
                        .build();

**Comment by nnegrey** [comment]
Do you get the same results if you don't use streaming?

**Comment by hlguo** [comment]
> Do you get the same results if you don't use streaming?

If I don't use streaming, I use the restful interface the result is right.

**Comment by hlguo** [comment]
Another problem, you can see I set languageList.add("zh"), but the result.getLanguageCode() is cmn-hans-cn, the two are the language code for chinese, but how can I know the result.getLanguageCode() for other languages?

**Comment by nnegrey** [comment]
Are you using the client library for non-streaming or making the rest call yourself?
The client libraries still use RPC.

**Comment by hlguo** [comment]
> Are you using the client library for non-streaming or making the rest call yourself?
> The client libraries still use RPC.

yes ,about 2 month ago, I test the spoken language detect effect using speechClient.recognize interface,  the result is good.  but it's decline in effect now.

**Comment by hlguo** [comment]
> Another problem, you can see I set languageList.add("zh"), but the result.getLanguageCode() is cmn-hans-cn, the two are the language code for chinese, but how can I know the result.getLanguageCode() for other languages?

Is there a language code list for result.getLanguageCode() output?

**Comment by nnegrey** [comment]
Could be the team made some changes on the backend if there was a quality drop in results. 
For that, it is probably best to file an issue against the API itself on this page: https://cloud.google.com/support/docs/issue-trackers

As we maintain the library and samples, but for the API itself, best to use the above link. 

Here's the language list page: https://cloud.google.com/speech-to-text/docs/languages
And the supported features by language page: https://cloud.google.com/speech-to-text/docs/supported-features-languages
