### ISSUE TITLE
Update the Java 11 samples to use the new Maven plugin 2.2.0

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1636]
The new plugin 2.2.0 release soon will simplify a lot the staging process to put dep jars in the staging dir automatically by parsing the main jar manifest entries...
Some cleanup will be needed in our pom.xml when we upgrade to 2.2.0.

**Comment by ludoch** [comment]
@saturnism @loosebazooka

**Comment by averikitsch** [comment]
Renovate bot has updated the plugin version. I have gone through all samples and made sure the pom.xml were clean as possible.

**Comment by loosebazooka** [comment]
@averikitsch is there some PR associated with that change?

**Comment by averikitsch** [comment]
No changes needed. The new plugin did not reduce the lines needed to get the samples working. I was unable to find any documentation to describe the updates. Do you disagree?

**Comment by loosebazooka** [comment]
I'm not sure I even know what I'm looking for here.

I think we can remove some lines from some samples? 

For instance: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java11/quarkus-helloworld/pom.xml#L83

We don't need quarkus to be copying files in like this anymore? appengine-maven-plugin "should" do the right thing. I have not tested this though.

**Comment by ludoch** [comment]
it works...I think...
On my initial repo, I had also a helidon sample which is using lib/ deps as
well

**Comment by averikitsch** [comment]
For the quarkus sample, it doesn't copy/create the correct jar file in the staging area without adding the configuration.

**Comment by averikitsch** [comment]
I can potentially add the artifact to the appengine maven plugin

**Comment by loosebazooka** [comment]
Sorry I should probably play around with the samples some more. Let me try them out tomorrow

**Comment by averikitsch** [comment]
Adding it as the artifact worked for quarkus. I think that is the only update, unless there is a solution for the copying over jar dependencies for running war servlets.
