### ISSUE TITLE
Page not found after deploying micronaut app to Java11

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/java-docs-samples#1649]
I have deployed micronaut-hello to Java11 runtime with no modifications other than (1) using my existing project, and (2) adding one line to app.yaml:

```
runtime: java11
instance_class: F1
service: hello

```
When I try to access this service in a browser, I get the following message, which seems like it's coming from micronaut:

{"_links":{"self":{"href":"/","templated":false}},"message":"Page Not Found"}

What may cause this?

The other services in this project work on Java8 as expected.

**Comment by volgin** [comment]
I have deployed vertx-helloworld example to the same project as a different service, and it worked as expected. So the issue is micronaut specific.

**Comment by nnegrey** [comment]
@averikitsch, are you the right person to take a look?

**Comment by averikitsch** [comment]
After investigating this issue, it seems like our `<parent>` in the `pom.xml` is causing issues with micronaut's annotations. Please try removing this from the POM and redeploying.

**Comment by averikitsch** [comment]
@kurtisvg would it be ok to remove the parent from this sample for the time being?

**Comment by kurtisvg** [comment]
@averikitsch Do we know what is causing the conflict? I'd prefer to just bump any dependencies in the parent and do a new release if that will solve the issue.

IIRC, removing the parent not only removes the style checks + errorprone compiling, but may also interferes with the maven return code which means this module would essentially becomes untested. If you do remove it, please make sure to file a bug to follow up.

**Comment by volgin** [comment]
Removing <parent> from the POM solves the problem.

**Comment by averikitsch** [comment]
@kurtisvg I believe there is conflict between the `annotationProcessorPaths` needed by the compiler plugin in the sample and the java-repo-tools.

**Comment by averikitsch** [comment]
Removing the error prone installation in the shared-configuration fixes the problem. Is there a way to exclude this or fix the compilation?

**Comment by kurtisvg** [comment]
@averikitsch Is `shared-configuration` using the most recent version of error-prone? is it java11 compatible?

**Comment by averikitsch** [comment]
@kurtisvg I believe there's a minor update but updating still didn't make it compile work. It compiles but when you try to run it, micronaut can't find any endpoints.

**Comment by kurtisvg** [comment]
@averikitsch Are we sure that ErrorProne is the issue? We should really turn renovate on the java-repo-tools to make sure everything is being updated

**Comment by averikitsch** [comment]
@kurtisvg it's most likely more of a micronaut using maven problem. I'm not sure how to dig into it more, but I believe it's a conflict with the [`annotationProcessorPaths`](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java11/micronaut-helloworld/pom.xml#L174) used with micronaut and error prone. Removing error-prone from the parent solves the problem.
