### ISSUE TITLE
JavaMail activation DataContentHandler error

### ISSUE THREAD

**Issue by FontanyLegall-Brandon** [GoogleCloudPlatform/java-docs-samples#1739]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java8/mail/src/main/java/com/example/appengine/mail/MailServlet.java

### Did you change the file? If so, how?

I didnt change the file

## Describe the issue
When i was trying to add JavaMail into my project, i get a NoClassDefFoundError, so i tryed to come to the java-docs-samples and there is the exact same error here.

When you launch the POST, you get a NoClassDefFoundError error that is :
```java
[INFO] GCLOUD: java.lang.NoClassDefFoundError: javax/activation/DataContentHandler
```

Tryed changing dependency with `javax.activation`, `com.sun.activation`,  `javax.xml.bind`, `com.sun.xml.bind`, `com.sun.xml.bind` without success 

Thanks in advance

**Comment by averikitsch** [comment]
Hi @FontanyLegall-Brandon, when I tried to recreate this issue, I received this error when my java version was incorrect. Can you confirm you are using Java 8?

**Comment by FontanyLegall-Brandon** [comment]
Hey @averikitsch and thanks for the reply, i find a solution but is pretty strange.

Like, when i use the Google SDK from the following link, it work correctly : https://cloud.google.com/appengine/docs/standard/java/download?hl=fr

But, from the follow link (+ `gcloud components install app-engine-java`) don't work : https://cloud.google.com/sdk/docs/downloads-interactive?hl=fr

So i needed to reinstall the SDK with the zip and not the curl, like, there is 2 different versions depending the link used ? 

Anyway, thanks for the reply, my problem is solved
