### ISSUE TITLE
Using Lambdas instead of Anonymous Class

### ISSUE THREAD

**Issue by Elgarni** [GoogleCloudPlatform/java-docs-samples#1752]
## Describe the issue

I wonder why Lambda expressions are not used in place of Antonymous Class where applicable. for instance, the following snippet from [firestore](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/firestore/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java#L382) :
```java
    final DocumentReference docRef = db.collection("cities").document("SF");
    ApiFuture<String> transaction =
        db.runTransaction(
            new Transaction.Function<String>() {
              @Override
              public String updateCallback(Transaction transaction) throws Exception {
                DocumentSnapshot snapshot = transaction.get(docRef).get();
                Long newPopulation = snapshot.getLong("population") + 1;
                // conditionally update based on current population
                if (newPopulation <= 1000000L) {
                  transaction.update(docRef, "population", newPopulation);
                  return "Population increased to " + newPopulation;
                } else {
                  throw new Exception("Sorry! Population is too big.");
                }
              }
            });
```
Can be converted into:
```java
    final DocumentReference docRef = db.collection("cities").document("SF");
    ApiFuture<String> transaction =
        db.runTransaction( transaction1 -> {
                  DocumentSnapshot snapshot = transaction1.get(docRef).get();
                  Long newPopulation = snapshot.getLong("population") + 1;
                  // conditionally update based on current population
                  if (newPopulation <= 1000000L) {
                    transaction1.update(docRef, "population", newPopulation);
                    return "Population increased to " + newPopulation;
                  } else {
                    throw new Exception("Sorry! Population is too big.");
                  }
                });
```
The code is now less verbose, and easier to read.

Is keeping the samples compliant with java7 needed?

**Comment by elharo** [comment]
Sometimes yes, Java 7 is needed. It depends on the product.

**Comment by kurtisvg** [comment]
So for this repo we currently target all the samples in Java 8 (unless it's a specific to a Java version like App Engine), but we also don't actively go back and update existing samples. This sample was likely written for Java 7. 

Feel free to PR changes if interested.

**Comment by Elgarni** [comment]
Sure. Will look into that, at least for the samples I came across.

**Comment by elharo** [comment]
FWIW in cases like this I think the most readable and clearest option is to use non-anonymous, non-lambda, outer classes. Both lambdas and inner classes prioritize writability over readability.

**Comment by Elgarni** [comment]
I see your point. I think since the goal of the samples is to showcase the usage of services, making the code in one block and keeping it short and concise is what users would usually want to get started.
