### ISSUE TITLE
Use com.google.cloud:libraries-bom for dependency management

### ISSUE THREAD

**Issue by chingor13** [GoogleCloudPlatform/java-docs-samples#1761]
Moving forward, we're encouraging users to import the `com.google.cloud:libraries-bom` in the `dependencyManagement` section of the user's `pom.xml` to resolve dependency compatibility. Users will no longer need to specify individual version numbers for google-cloud-x libraries.

**Comment by averikitsch** [comment]
@chingor13 can you add this to our sample format info? Also, is this an ask for updating existing samples?
