### ISSUE TITLE
google-cloud-kms dependency way out of date

### ISSUE THREAD

**Issue by chingor13** [GoogleCloudPlatform/java-docs-samples#1762]
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/kms/pom.xml#L28

The current version of google-cloud-kms is 1.35.0 (it's GA now)

**Comment by gguuss** [comment]
Reassigning to Dan as I believe he authored this sample.

**Comment by gguuss** [comment]
Dan, let me know if you can't get to this within SLO, happy to take a pass on it.

**Comment by kurtisvg** [comment]
It would be good to figure out why Renovate hasn't updated this.

**Comment by DanSanche** [comment]
I updated the version with no issues here https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1769. I'm not familiar enough with the repo to say why it's not being auto-updated though

**Comment by kurtisvg** [comment]
Fixed by #1769
