### ISSUE TITLE
Need documentation explaining how to run tests in KMS

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/java-docs-samples#1767]
Not immediately clear why. This is after setting the GOOGLE_APPLICATION_CREDENTIALS. It might be that there's some additional setup step needed to run these tests; perhaps something involving crypto providers to judge by the nature of the tests and the lines where it fails?

```
[INFO] Running com.example.CryptFileIT
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.635 s <<< FAILURE! - in com.example.CryptFileIT
[ERROR] com.example.CryptFileIT  Time elapsed: 1.634 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.CryptFileIT.setUpClass(CryptFileIT.java:53)

[ERROR] com.example.CryptFileIT  Time elapsed: 1.635 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.CryptFileIT.tearDownClass(CryptFileIT.java:68)

[INFO] Running com.example.QuickstartIT
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.example.QuickstartIT
[ERROR] com.example.QuickstartIT  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.QuickstartIT.setUpClass(QuickstartIT.java:53)

[ERROR] com.example.QuickstartIT  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.QuickstartIT.tearDownClass(QuickstartIT.java:68)

[INFO] Running com.example.AsymmetricIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.example.AsymmetricIT
[ERROR] com.example.AsymmetricIT  Time elapsed: 0 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.example.AsymmetricIT.<clinit>(AsymmetricIT.java:60)

[INFO] Running com.example.SnippetsIT
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.example.SnippetsIT
[ERROR] com.example.SnippetsIT  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.SnippetsIT.setUpClass(SnippetsIT.java:59)

[ERROR] com.example.SnippetsIT  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.SnippetsIT.tearDownClass(SnippetsIT.java:74)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AsymmetricIT.com.example.AsymmetricIT » ExceptionInInitializer
[ERROR] com.example.CryptFileIT.com.example.CryptFileIT
[ERROR]   Run 1: CryptFileIT.setUpClass:53 » NullPointer
[ERROR]   Run 2: CryptFileIT.tearDownClass:68 » NullPointer
[INFO] 
[ERROR] com.example.QuickstartIT.com.example.QuickstartIT
[ERROR]   Run 1: QuickstartIT.setUpClass:53 » NullPointer
[ERROR]   Run 2: QuickstartIT.tearDownClass:68 » NullPointer
[INFO] 
[ERROR] com.example.SnippetsIT.com.example.SnippetsIT
[ERROR]   Run 1: SnippetsIT.setUpClass:59 » NullPointer
[ERROR]   Run 2: SnippetsIT.tearDownClass:74 » NullPointer
[INFO] 
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
[INFO] 
[INFO] 
```

**Comment by elharo** [comment]
I notice the kokoro script sets up a lot of environment variables, installs the Cloud SDK, and perofrms other steps:

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/.kokoro/tests/run_tests.sh

It seems likely these are needed for the tests to pass and if so, the corresponding manual setup needs to be documented in CONTRIBUTING.md or some such.

**Comment by averikitsch** [comment]
Looks like there are a lot of [variables](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/kms/src/test/java/com/example/SnippetsIT.java#L46) you need to have set correctly.
Have you taken a look at the corresponding [docs](https://cloud.google.com/kms/docs/encrypt-decrypt)?

**Comment by elharo** [comment]
I think the docs we need for this repo are not written. The custom is a CONTRIBUTING.md file that lays out in detail all prerequisites for building and running tests. The docs you point to are for the KMS API and client libraries in general, not for this specific repo.

**Comment by averikitsch** [comment]
@DanSanche you were the last person to update these samples. Can you add or link to the correct set up steps or do you know who the right person would be? Thanks

**Comment by DanSanche** [comment]
Hmm I'm not seeing the same issue. I just cloned a fresh copy of the repo, and I'm getting a couple new checkstyle issues at the end, but no null pointer exceptions. 

It's possible you need to enable the API or something in your project. I'll do some digging

**Comment by elharo** [comment]
It's likely you have environment variables set that I don't. For instance, you talk about "your project" but there's nothing in the docs to suggest I need a project to run the tests. Looking in the test code I find:

```
  private static final String PROJECT_ID = System.getenv("GOOGLE_CLOUD_PROJECT");
```

This is the sort of thing we should document in CONTRIBUTING.md.

**Comment by DanSanche** [comment]
It looks like the GOOGLE_CLOUD_PROJECT environment variable is mentioned already in [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/CONTRIBUTING.md#other-testing-set-up) - although maybe not as clearly as it should be. Feel free to submit a PR. 

Were you having any other KMS-specific issues, or did it work after setting that one?

**Comment by DanSanche** [comment]
I tested this out on a new project, and it looks like the tests run after enabling the API and setting GOOGLE_CLOUD_PROJECT. Since it seems like there are no issues with the KMS samples specifically, I'm closing this bug.

I agree this samples repo could be more friendly to first-time contributors though, so feel free to open a new issue or PR to address that, or re-open this one if you're still having issues with the KMS sample

**Comment by elharo** [comment]
It sounds like we're still relying on local knowledge in developers' heads, not actual docs. For instance, you mention "enabling the API". Which API? How is that done? The details should be committed to the repo, probably in a CONTRIBUTING.md file in this directory since some of the steps will differ betweem different samples.

**Comment by DanSanche** [comment]
I'd argue most of this info should be put in this repo's root, since it should apply to all samples. Regardless, I opened a PR here to add this info to KMS's README as well. Let me know if you think it's missing anything

**Comment by elharo** [comment]
Got up to 

[ERROR] com.example.SnippetsIT  Time elapsed: 0.504 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Cloud Key Management Service (KMS) API has not been used in project 147197868884 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=147197868884 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

This took some guesswork to decipher. The real problem seems to be that GOOGLE_CLOUD_PROJECT was not set to the same project I'd st up auth credentials for.

**Comment by elharo** [comment]
Now I'm seeing error messages like:

[ERROR] com.example.CryptFileIT  Time elapsed: 1.279 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.destroy' denied on resource 'projects/debugging-for-downloads/locations/global/keyRings/test-key-ring-6c735595-2b3a-4af0-adb8-fad9bd885ffc/cryptoKeys/4b751bb2-48f6-4430-89c5-7a1255d13189/cryptoKeyVersions/1' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.destroy' denied on resource 'projects/debugging-for-downloads/locations/global/keyRings/test-key-ring-6c735595-2b3a-4af0-adb8-fad9bd885ffc/cryptoKeys/4b751bb2-48f6-4430-89c5-7a1255d13189/cryptoKeyVersions/1' (or it may not exist).

**Comment by DanSanche** [comment]
Try running it again. The tests need to set up keys, so sometimes the first run on a new project will fail as they are still being provisioned

**Comment by elharo** [comment]
I've tried multiple times. No change. :-(

**Comment by DanSanche** [comment]
Then it sounds like you likely don't have the right permissions to edit KMS resources. How are you authenticating gcloud? Assuming you're using a service account, what IAM roles were granted to it?

**Comment by elharo** [comment]
It's probably something like that. This is the sort of thing we need to be explicit about in CONTRIBUTING.md.

**Comment by elharo** [comment]
Looking in the cloud console it does seem that the test runs have created the keys:

![image](https://user-images.githubusercontent.com/1005544/70070643-f1ee0200-15c1-11ea-856d-5adae00db7de.png)

**Comment by DanSanche** [comment]
Ok, I added a mention of that to my README PR:

> ### Grant Permissions
> You must ensure that the [user account or service account](https://cloud.google.com/iam/docs/service-accounts#differences_between_a_service_account_and_a_user_account) you used to authorize your gcloud session has the proper permissions to edit KMS resources for your project. More information can be found in the [Google KMS Docs](https://cloud.google.com/kms/docs/reference/permissions-and-roles)

I think it's important to keep the intended audience of these docs in mind though - we follow strict processes for these samples, and don't expect many external contributions. We expect end users to interact with these samples primarily through [the docs](https://cloud.google.com/iam/docs/quickstart-client-libraries#client-libraries-install-java), which are much more through. We want to avoid duplicating too much of that content here
