### ISSUE TITLE
args4j in KMS

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/java-docs-samples#1771]
per CONTRIBUTING.md "Simple command-line samples with only positional arguments should use the args argument to main(String... args) directly. A command-line sample which has optional parameters should use the Apache Commons CLI library."

However KMS (and perhaps others) uses args4j: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/kms/pom.xml

**Comment by lesv** [comment]
We've revised our guidelines to prefer non-command line samples.  Unless you are asking for the sample to be rewritten, I'm going to close this.  If we reopen, it should probably be a feature request, P2 and not a cleanup as our cleanups appear to have no SLA's.
