### ISSUE TITLE
AnalyzeIT and AnalyzeBetaIT failing when upgrading to libraries-bom

### ISSUE THREAD

**Issue by kolea2** [GoogleCloudPlatform/java-docs-samples#1786]
While trying to upgrade to the libraries-bom, tests are failing. Not sure if this is the cause or not - opening an issue to track. See #1781

**Comment by averikitsch** [comment]
Going to close this since the PR was merged. Feel free to reopen.

**Comment by kolea2** [comment]
Hey @averikitsch, sorry for the confusion - this is still an issue and was not included in the above PR's changes. reopening for tracking

**Comment by averikitsch** [comment]
@nnegrey Do you know if there are issues with the library versions for this or why these [tests](https://fusion.corp.google.com/runanalysis/buildlogs/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/KOKORO/26a57e63-9e6f-442d-a6d7-6e9e5dc4fafc/1575398000837/build%20%231376/Targets) would be failing?

**Comment by nnegrey** [comment]
Um looks like whatever files the tests rely on are no longer there. 
Pushing a PR with the fix.

**Comment by nnegrey** [comment]
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1797
