### ISSUE TITLE
Tasks sample is confusing (tasks area)

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1801]
First of all, the pom.xml at https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/tasks/pom.xml#L21
uses war packaging, but the sample contains only 2 classes, not a Web App.

Then is no main to test it.
Then,  if I create a main to call the first sample, with correct ceated queue, project and region, I get an error like:
 java -cp tasks-samples-1.0-SNAPSHOT-jar-with-dependencies.jar com.example.task.NewMain
Dec 11, 2019 1:47:47 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
Exception in thread "main" com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:69)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)

so it is confusing to understand in which context this code has to run from or how to create a working configuration.

**Comment by averikitsch** [comment]
According to the [snippet definition](http://go/code-snippets-101#what-is-a-code-snippet), code samples do not have to be executable since that adds complexity to samples when added complexity is not wanted. We expect users to copy this code into a working environment. 

For executable code please see our [quickstart](https://cloud.google.com/tasks/docs/quickstart-appengine).

**Comment by ludoch** [comment]
So the war packaging is not an issue?
What about the README that could point to the quickstart documentation link to help simple people like me?  It seems the README is incomplete.

**Comment by averikitsch** [comment]
Oops, I shouldn't have closed this before adding PR #1805.
