### ISSUE TITLE
the cost is not right

### ISSUE THREAD

**Issue by hlguo** [GoogleCloudPlatform/java-docs-samples#1809]
## Describe the issue

I run https://speech.googleapis.com/v1p1beta1/speech:recognize API to detect the language in audio file, I setLanguageCode("ja-JP") & languageList.add("zh"); languageList.add("en-US"); the document says the price is 0.006$/15s, I run 30128 files (time less then 15s) to test, the cost should be 180$ or so, but the real cost is 336$, what's wrong?

**Comment by kurtisvg** [comment]
Hi hlguo@,

Issues on this repo should be related to the content of the repo itself. Please contact [Cloud Billing Support](https://cloud.google.com/support/billing/) to resolve your question.
