### ISSUE TITLE
Fix ignored test: FhirResourceTest.test_FhirResourcePatch()

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/java-docs-samples#1816]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java#L162

### Did you change the file? If so, how?

No

## Describe the issue

Test is currently ignored.

**Comment by lesv** [comment]
status?

**Comment by dzlier-gcp** [comment]
I will try removing the ignore on these and see if any of them pass.
