### ISSUE TITLE
Fix ignored test: FhirResourceTests.test_FhirResourceConditionalPatch()

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/java-docs-samples#1817]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java#L174

### Did you change the file? If so, how?

No

## Describe the issue

The test is ignored.

**Comment by lesv** [comment]
status?
