### ISSUE TITLE
Fix ignored test: FhirResourceTests.test_FhirResourceConditionalUpdate()

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/java-docs-samples#1818]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java#L188

### Did you change the file? If so, how?

No

## Describe the issue

The test is ignored.

**Comment by lesv** [comment]
Status?

**Comment by lesv** [comment]
This appears to have been fixed in #2456
