### ISSUE TITLE
Fix ignored test: AlertIT.testRestoreBackup()

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/java-docs-samples#1819]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/monitoring/v3/src/test/java/com/example/AlertIT.java#L84

### Did you change the file? If so, how?

No

## Describe the issue

The test is ignored.

**Comment by lesv** [comment]
Status?

**Comment by lesv** [comment]
ping

**Comment by lesv** [comment]
fixed by #2669
