### ISSUE TITLE
Fix ignored test: DeploymentTests.rolloutStartSetGetTargetCommitTests()

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/java-docs-samples#1821]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/DeploymentTests.java#L112

### Did you change the file? If so, how?

No

## Describe the issue

The test is ignored.

**Comment by lesv** [comment]
Resolved by #2272
