### ISSUE TITLE
GameService Tests are Flaky

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1825]
[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fcontinuous/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fcontinuous/KOKORO/64234397-84f2-40ae-acc1-2ed2bd555dbc/1576510520639/build%20%23243/Targets?target=github%2Fjava-docs-samples%2Fgameservices%2Fv1alpha%2Ftarget%2Fsurefire-reports&drilldownTab=tests)

**Comment by lesv** [comment]
Status?

**Comment by gguuss** [comment]
@dzlier-gcp May have an update.

**Comment by lesv** [comment]
ping

**Comment by lesv** [comment]
GameServices No longer appears in our repo.
