### ISSUE TITLE
Jobs Tests are Broken

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1827]
[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fcontinuous/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fcontinuous/KOKORO/64234397-84f2-40ae-acc1-2ed2bd555dbc/1576510520639/build%20%23243/Targets?target=github%2Fjava-docs-samples%2Fjobs%2Fv3%2Ftarget%2Fsurefire-reports&drilldownTab=tests)

**Comment by kurtisvg** [comment]
Lesv@ mentioned he would delete the v2 samples.

I think the v3 ones are also broken, so please assign to the SWE responsible.

**Comment by lesv** [comment]
@chenlei1216 PTAL

**Comment by lesv** [comment]
V2 was deleted.

**Comment by lesv** [comment]
Probably should have been closed w/ #2002
