### ISSUE TITLE
FHIR Server patient-everything issue

### ISSUE THREAD

**Issue by Rokshan2016** [GoogleCloudPlatform/java-docs-samples#1907]
Hi @hfwang 

I am trying to use this api 

https://healthcare.googleapis.com/v1beta1/projects/{{ project_name  }}/locations/{{ region  }}/datasets/{{ dataset_name  }}/fhirStores/fhir-store/fhir/Patient/988e6160-90e7-4f73-b049-27e69cc7fede/$everything

Getting the following error : 

{
  "issue": [
    {
      "code": "not-supported",
      "details": {
        "text": "bad_resource_type"
      },
      "diagnostics": "unsupported resource type",
      "severity": "error"
    }
  ],
  "resourceType": "OperationOutcome"
}

**Comment by lesv** [comment]
Ideally, questions are asked on StackOverflow.  Please reopen if you still require an answer.
