### ISSUE TITLE
Text to speech transcribe RTMP

### ISSUE THREAD

**Issue by jinyeng** [GoogleCloudPlatform/java-docs-samples#1934]
Sorry not an issue but wanted to check if there is any documentation to transcribe an rtmp stream. It is a real usage scenario for live streaming. Has been asked few times on SO.

https://stackoverflow.com/questions/16803621/how-to-capture-live-audio-via-rtmp-using-xuggler
https://stackoverflow.com/questions/38453805/speech-to-text-from-a-live-stream

**Comment by nnegrey** [comment]
Text-to-Speech or Speech-to-Text?

Streaming Docs page: https://cloud.google.com/speech-to-text/docs/streaming-recognize

Speech to text `StreamingRecognitionConfig` https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#streamingrecognitionconfig

Supported Audio Encodings: https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.RecognitionConfig.AudioEncoding
