### ISSUE TITLE
Vision sample - Label - using deprecated API - GoogleCredential

### ISSUE THREAD

**Issue by kolban-google** [GoogleCloudPlatform/java-docs-samples#1942]
In the following source ...

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/vision/label/src/main/java/com/google/cloud/vision/samples/label/LabelApp.java

There is the usage of a class that is now flagged as deprecated:

com.google.api.client.googleapis.auth.oauth2.GoogleCredential

A [StackOverflow](https://stackoverflow.com/questions/59710813/com-google-api-client-googleapis-auth-oauth2-googlecredential-is-now-deprecated) question has asked what is the alternative?

The purpose of this issue is to examine the sample and see if it can updated to use non-deprecated GCP API.

**Comment by kurtisvg** [comment]
@nnegrey - Can you take a look?

**Comment by nnegrey** [comment]
Looks like that sample got removed from our docs and I'm gonna propose deleting it. 

People should be using the updated samples on this docs page: https://cloud.google.com/vision/docs/labels#vision-label-detection-java

**Comment by nnegrey** [comment]
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1946

**Comment by nnegrey** [comment]
I've answered directly on the StackOverflow question and can followup there if there is more questions, but since the old code has now been removed, I'm gonna close this issue. 

Let me know if anything else is needed.
