### ISSUE TITLE
storage: separate each sample into a separate file

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/java-docs-samples#1945]
Each sample should be in a standalone file. This workitem is to track that work.

**Comment by crwilcox** [comment]
@JesseLovelace I believe you already are doing this as part of a broader effort.

**Comment by kurtisvg** [comment]
This could be expanded to more generally adjust samples to follow the [Sample Format Style Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md) , which includes guidance on separate files.
