### ISSUE TITLE
Continuous tests failed for Translate

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1950]
https://fusion.corp.google.com/runanalysis/buildlogs/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fcontinuous/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fcontinuous/KOKORO/7384cf77-2ce2-4d22-ae9a-a9673ad1ea8d/0/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fcontinuous/Targets

**Comment by nnegrey** [comment]
Quick note for myself, looks like a timeout issue and I can bump the timeout.

Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 19.999356603s.
