### ISSUE TITLE
iap sample readme has a bad link

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#2055]
In the README.md of
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/iap
there is a link in the Testing section "Deploy the demo app engine application. "
which is a 404 https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine/iap/README.md

I do not know what or were is the app engine application, so this is blocking my IAP investigation

**Comment by ludoch** [comment]
Via archeology research, it might be https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iap/app_engine_app ? Not sure.
Would be  nice to better document this in the README...
Bonus point, since this is a Java sample, it would be better to see a Java App Engine App to talk to, so that we do not confuse/distract developers.

**Comment by averikitsch** [comment]
It was deleted when all Java7 samples were deleted. Undoing this in #2057
