### ISSUE TITLE
Datacatalog Build Failing

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/java-docs-samples#2132]
GoogleCloudPlatform/java-docs-samples#2102

https://source.cloud.google.com/results/invocations/9479d637-f0f9-4e16-bc22-d0d28f83d079/targets

https://source.cloud.google.com/results/invocations/0eb0ea20-3c6d-4d29-b6f0-92bc7920ae29/targets

Reaching out to sample writer

**Comment by nnegrey** [comment]
@mesmacosta

**Comment by lesv** [comment]
@nnegrey what is the status of this issue?
