### ISSUE TITLE
Cloud Talent API: Java Histogram sample missing from source control (and others )

### ISSUE THREAD

**Issue by hilts-vaughan** [GoogleCloudPlatform/java-docs-samples#2145]
https://cloud.google.com/talent-solution/job-search/docs/histogram#job_search_histogram_search-java

## In which file did you encounter the issue?

jobs/v4/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchHistogramSearch.java

## Describe the issue
It existed on `talent-v4beta1-samples` but not on `master` now. The `talent-v4beta1-samples` branch is gone, though so many of them are missing.

Looks like like a bunch were migrated in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2033 -- were some left behind?

**Comment by hilts-vaughan** [comment]
I have a CL open to update the devsite; just need confirmation on the behaviour here / if we plan to support those samples / bring them back.

**Comment by nnegrey** [comment]
Branch deletion reverted.
