### ISSUE TITLE
Many samples somehow are bringing in xstream 1.3.1 through transitive dependencies.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2163]
This is incompatible w/ Java11 and has other issues as well.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/root/.m2/repository/com/thoughtworks/xstream/xstream/1.3.1/xstream-1.3.1.jar) to field java.util.Properties.defaults
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This is being brought in by some transitive thing.  We really should set a minimum version rather than a general acceptance in the pom.

Projects where this is an issue (gcp/J-D-S repo):
- appengine-java11/guestbook-cloud-firestore
- appengine-java11/helloworld-servlet
- appengine-java11/oauth2
- almost all appengine-java8 samples
- cloud-sql/mysql/servlet
- cloud-sql/postgres/servlet
- endpoints/getting-started
- endpoints/getting-started
- almost all flexible samples
- memorystore/redis

**Comment by elharo** [comment]
No idea where this is coming from. I don't see it in `mvn dependency:tree`

**Comment by lesv** [comment]
Appears to be fixed.
