### ISSUE TITLE
Unexpected exception reading PKCS#8 data 

### ISSUE THREAD

**Issue by Ankitappperfect** [GoogleCloudPlatform/java-docs-samples#2284]
I'm generating credentials for the service account in GCP using JAVA SDK and I'm getting error for reading private key. I've compared the private key generated from JAVA SDK and from GCP console and there is a variation of length and formatting of a key in both cases. I've tried to convert key received from SDK to key received from GCP console but couldn't succeed.

**Comment by kurtisvg** [comment]
Hi @Ankitappperfect,

This repo is for samples from our documentation. Is there a specific sample you were following that you believe it incorrect?

If not, please open an issue on the repo of the client you are user. It's also helpful to include information such as what version of the library, what version of java, and a sample of code to reproduce the issue.
