### ISSUE TITLE
Unable to assign role to service account

### ISSUE THREAD

**Issue by Ankitappperfect** [GoogleCloudPlatform/java-docs-samples#2293]
I'm able to create a service account but facing issues while assigning a role to the service account. Here is the approach I'm using
```
List<String> members = new ArrayList<>();
members.add("serviceAccount:" + serviceAccount.getEmail());

Binding binding = new Binding();
binding.setMembers(members);
binding.setRole("roles/editor");

List<Binding> bindings = new ArrayList<>();
bindings.add(binding);

Policy policy = new Policy();
policy.setBindings(bindings);

String resource = "projects/"+projectId + "/serviceAccounts/" + accountId;

SetIamPolicyRequest content = new SetIamPolicyRequest().setPolicy(policy);

service.projects().serviceAccounts().setIamPolicy(
        resource, content).buildHttpRequest().execute();
```

This code is not giving any error but also not setting a role for the provided service account.

**Comment by nnegrey** [comment]
I think the last line is wrong. But I'm not sure what your `service` object is. 
I think you want something like this:
```
CloudResourceManager service = createCloudResourceManagerService();
Policy response = service.projects().setIamPolicy(projectId, request).execute();
```

**Comment by Ankitappperfect** [comment]
I've created service object of Iam class

**Comment by nnegrey** [comment]
Could you try using the `CloudResourceManager`?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/iam/api-client/src/main/java/com/google/iam/snippets/SetPolicy.java
