### ISSUE TITLE
 vision/product-search/cloud-client - possibly flaky test.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2392]
Test appears flakey.  I'm unable to run this using GOOGLE_CLOUD_PROJECT=java-docs-samples-testing and the same Service account as Kokoro.  See #2170

**Comment by nnegrey** [comment]
Yea, I think I just need to switch it to UUIDs and rework the tests a bit. Did a bit of a fix earlier this week on some of them that were failing.
