### ISSUE TITLE
en-token.bin file not working apparantly.

### ISSUE THREAD

**Issue by DushyantShukla** [GoogleCloudPlatform/java-docs-samples#240]
Use of english token model (en-token.bin) downloaded from the given source resulted in  null pointer exception. Instead I downloaded the file from http://maven.tamingtext.com/opennlp-models/models-1.5/ to make the sample program run accordingly.

**Comment by tswast** [comment]
This is for the [Google Cloud Vision API Text Detection sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/vision/text), correct?

**Comment by DushyantShukla** [comment]
Yeah.

**Comment by gguuss** [comment]
I just tested this with the model referenced in the README and was unable to reproduce the issue, closing.
