### ISSUE TITLE
Google App Engine Java Error on Deploy. Cloud MySQL. Hikari Failed to initialize pool

### ISSUE THREAD

**Issue by oriolmanya** [GoogleCloudPlatform/java-docs-samples#2473]
I have an error on deploying a Java App on Google App Engine. It happens at the end of the deployment phase executed by mvn package appengine:deploy.

On local it all works perfectly.

It's all explained here:
https://stackoverflow.com/questions/60802941/google-app-engine-java-error-on-deploy-cloud-mysql-hikari-failed-to-initialize

I copied this file, to implement Hiraki as well:
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java

The only change I've made For testing, I've hardcoded the Database credentials like:
```
    private static final String CLOUD_SQL_CONNECTION_NAME = "id_project:europe-west2:database_name";
    private static final String DB_USER = "root";
    private static final String DB_PASS = "xxxxxxxxxxxxx";
    private static final String DB_NAME = "database_name";
```

The crash happens at the end of the deployment process -I know that is near the end because I've successfully deploy the app without the DDBB connection-. I attach all the Deploy trace, but summarized:
```
[INFO] GCLOUD: 
[INFO] GCLOUD: Updating service [default] (this may take several minutes)...
[INFO] GCLOUD: .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [9] 
[INFO] GCLOUD: Application startup error! Code: APP_CONTAINER_CRASHED
[INFO] GCLOUD: 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.setHostFailedWithoutProxy(AbstractConnectProtocol.java:1047)
[INFO] GCLOUD: 	at org.mariadb.jdbc.MariaDbConnection.setHostFailed(MariaDbConnection.java:1624)
[INFO] GCLOUD: 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:179)
[INFO] GCLOUD: 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
[INFO] GCLOUD: 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
[INFO] GCLOUD: 	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:516)
[INFO] GCLOUD: 	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:740)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:403)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
[INFO] GCLOUD: 	... 40 more
[INFO] GCLOUD: 
[INFO] GCLOUD: org.eclipse.jetty.deploy.DeploymentManager: Unable to reach node goal: started
[INFO] GCLOUD: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:589)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575)
[INFO] GCLOUD: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[INFO] GCLOUD: 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[INFO] GCLOUD: 	at es.ubiqua.compareme.infrastructure.MariaDbEntity.ConnectionPoolContextListener.createConnectionPool(ConnectionPoolContextListener.java:104)
[INFO] GCLOUD: 	at es.ubiqua.compareme.infrastructure.MariaDbEntity.ConnectionPoolContextListener.contextInitialized(ConnectionPoolContextListener.java:138)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:959)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:924)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
```
Thanks for the help
[stackoverflow.txt](https://github.com/GoogleCloudPlatform/java-docs-samples/files/4369321/stackoverflow.txt)

**Comment by oriolmanya** [comment]
hi @gguuss If you need any code or anything else, please, let me know

**Comment by gguuss** [comment]
I'm less familiar with this issue and was just auto-assigned, I'll find someone better to answer your question.

**Comment by gguuss** [comment]
@GabeWeiss

**Comment by GabeWeiss** [comment]
*wave* There's probably some permission/access pieces and/or networking issues at play here... have you read through this doc yet: https://cloud.google.com/sql/docs/mysql/connect-app-engine#configuring ?

That's the first stop for AppEngine + CloudSQL. I have not personally played extensively with Maven, but enough to be dangerous so I may be able to help there as well, but let's start with that doc I linked and make sure that at least those i's are dotted and t's crossed.

**Comment by oriolmanya** [comment]
Hi @GabeWeiss , thanks for the advice. I rechecked the permissions as well as I rechecked the DOC you provide. 
Anyway, I find strange that if it is a permissions problem, it crashes on the deploy process, I would presume it would give an error on execution while it tries to connect to the Cloud MySQL. Am I wrong?
Here I attach the screenshot of the IAM permissions related:
![Screenshot 2020-03-24 at 19 23 39](https://user-images.githubusercontent.com/19649147/77463130-6cf35680-6e05-11ea-85f3-1f4c31590069.png)

Any other advice / hint on what I should check? 
Here is the full deployment log from the terminal; the final part is the stacktrace with the error. Could you have a look at it in case you find something? Thanks a lot.
[stacktrace_deployment.txt](https://github.com/GoogleCloudPlatform/java-docs-samples/files/4377197/stacktrace_deployment.txt)

**Comment by GabeWeiss** [comment]
Absolutely, shouldn't be a crash on permission...but I've seen weirder for sure. :D Permissions seem fine to me, but could also be connectivity and timeouts causing a crash.

One thing to be sure of... on the connection piece of code, do you call:
config.setJdbcUrl(String.format("jdbc:mysql:///%s", DB_NAME));

I see in the SO question, you're calling:
config.addDataSourceProperty("socketFactory", "com.google.cloud.sql.mysql.SocketFactory");

But I think that's only a piece of the puzzle.

I'm also going to call in a bigger gun than I. @kurtisvg knows more about the Java side than I do. Kurtis, can you weigh in here?

**Comment by kurtisvg** [comment]
Not sure the direct problem, but there is some funkiness going on in your pom:
```
```

**Comment by kurtisvg** [comment]
Not sure of the direct problem, but there's funkiness in your pom that's probably causing issues:

You have the mysql-connector and jdbc-socket-factory here:
```
       <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.19</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>mysql-socket-factory-connector-j-8</artifactId>
            <version>1.0.15</version>
        </dependency>
```

And then you also have the mariadb connector here:
```
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.4.0</version>
        </dependency>
```

It looks like the mariadb connector is being used, but the Cloud SQL doesn't support mariadb (and neither does the java jdbc socket factory).

**Comment by oriolmanya** [comment]
Hi @kurtisvg, it worked! It was legacy code I didn't have under control. I cleared the -otherwise unused- references to MariaDb. Many thanks for the outstanding hint, you saved me, I was trying this for days.
