### ISSUE TITLE
automl/beta testTablesPredict failed

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#2494]
Test failed with BOM update PR #2484 
[Test Fusion](https://fusion.corp.google.com/runanalysis/buildlogs/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/KOKORO/9acde03e-5a5d-4af6-b333-1c14faee35d1/0/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/Targets)

**Comment by nnegrey** [comment]
Note to self:
Failures: 
1. testing video/beta
2. testing vision/automl

@averikitsch, I don't see that the `automl/beta` folder had tables tests failing, but I will check those tests. I did see the 2 old set of samples are failing and I will update the tests for those. Though I'd prefer to delete them, but can't quite yet. Did I just scroll past or not find the tables error?

**Comment by averikitsch** [comment]
Sorry, I think I copied this error from another PR I am working on. Also Video/beta is just a flaky resource limits. Closing this issue.

**Comment by nnegrey** [comment]
I'll go make a quota request increase on video.

**Comment by nnegrey** [comment]
Actually, the flakiness seems to be `INTERNAL: Internal error encountered.` but on a flaky issue I don't know what that could even be.
