### ISSUE TITLE
Error while Sends data on behalf of a bound device using the Gateway ?

### ISSUE THREAD

**Issue by tranthanhtung04101995** [GoogleCloudPlatform/java-docs-samples#2517]

**Comment by tranthanhtung04101995** [comment]
/java-docs-samples/blob/master/iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
mqtt ClientId - a wrong calculation led to an error
`    // Google Cloud IoT Core, it must be in the format below.
    final String mqttClientId =
        String.format(
            "projects/%s/locations/%s/registries/%s/devices/%s",
            projectId, cloudRegion, registryId, gatewayId);
`

**Comment by kurtisvg** [comment]
Hi @tranthanhtung04101995 - Can you please include more information about that the problem is and what you are trying to do?

**Comment by tranthanhtung04101995** [comment]
I am trying to send data from the device to Google IoT Core. How do I do that?

**Comment by gguuss** [comment]
@tranthanhtung04101995 The process is as follows:

Set up the gateway and device using [Cloud console](https://console.cloud.google.com/iot) / [Google Cloud SDK](https://cloud.google.com/sdk) / API
- Create Gateway 
- Create Device
- Bind Device to Gateway

Connect and send using MQTT
- Connect Gateway over MQTT 
- Attach Device to Gateway using MQTT
- Now you can publish to the device's topic which will send data to Google Cloud via PubSub

There's [more detailed documentation here](https://cloud.google.com/iot/docs/how-tos/gateways/mqtt-bridge).
