### ISSUE TITLE
GCF samples - move helloworld

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/java-docs-samples#2685]
Language-specific helloworld should go into `helloworld` directory.

GCS and product-specific samples should go to product directory. E.g., `hello-gcs` should go into `gcs` directory, `pubsub-retry` go into `pubsub` directory.

This is what we originally discussed and documented.

**Comment by ace-n** [comment]
I'm -1 on putting "product-specific samples" into a separate directory, as that makes them (IMO) less discoverable at a glance. I'll defer to @labtopia on this though.

RE `jvm-langs`: **I can put those into the `helloworld` directory** as we discussed previously.

**Comment by labtopia** [comment]
I take your point @ace-n , but I'm in favor of this change for a few reasons:
-- My understanding is that it would be more consistent with other Java repos.
-- It fits in better with the taxonomy we're using for our other samples. If I were a Kotlin/etc. developer, I do think it would occur to me to look in /helloworld for samples.
-- Having them where they are now doesn't scale, if we continue to expand on our sample set for these languages. We would want any new samples to go in the appropriate subdirectory, not in a jvm-branded directory.
-- Finally, I hope that the samples will be discoverable via the docs. But in any case, I just did a search for "kotlin" at the /functions level of our current setup. It took me right to the kotlin samples. So users should be able to find them.

**Comment by saturnism** [comment]
[App Engine 11 samples](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11) are also grouped more or less by products too, in addition to helloworld for different frameworks/jvm languages.

Moreover, in Function samples, there is [pubsub sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/functions/pubsub) and [hello/hello-pub-sub sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/functions/helloworld/hello-pub-sub) and, [concepts/retry-pub-sub sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/functions/concepts/retry-pub-sub) and [concepts/retry-timeout sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/functions/concepts/retry-timeout)

it's already difficult to find these pub/sub samples , and also hard to tell the difference between retry-timeout vs retry-pub-sub, or hello-pub-sub, vs pubsub/.  Is it pubsub or pub-sub?  I'm not following why grouping these under a single `pubsub` directory would make them harder to find.

E.g.,
```
pubsub/
  hello-pubsub/
  publish-to-topic/
  retry/
  retry-with-timeout/
```

**Comment by saturnism** [comment]
For logging, it already follows the proposed structure, and makes sense.

```
logging/
  log-hello-world/.  <- except this can be named consistently, e.g., hello-logging like hello-pubsub?
  retrieve-logs/
  stackdriver-logging/
```

**Comment by ace-n** [comment]
@labtopia duly noted; I'll create a PR accordingly.

@saturnism I suspect the samples you mentioned are best discussed in a separate issue. That said, I'll try to address your concerns here:

The `retry-pubsub` and `retry-timeout` examples are _conceptual examples_ focused around how to create "retriable functions", and are shown in [this doc](https://cloud.google.com/functions/docs/bestpractices/retries#set_an_end_condition_to_avoid_infinite_retry_loops). IMO, the "pubsub" factor here is ancillary - these particular samples could just as easily be based on (e.g.) Cloud Storage triggers.

**Comment by ace-n** [comment]
PR has been merged.

@saturnism @labtopia did you still want _product-specific_ directories instead of one large `helloworld` one (like the other languages use)?

**Comment by ace-n** [comment]
Update: @labtopia is ambivalent here. I'm still a bit -1 because of what the other products do - @saturnism if you think updating the other products to the same "per-product standard" is worth it though, I can do that here too.

**Comment by saturnism** [comment]
discussed online and this is good for now. bigger refactors can be deferred.

katie will open a new bug on renaming a couple of directories to follow convention, e.g. `pub-sub` -> `pubsub`, `hello-world` -> `helloworld`
