### ISSUE TITLE
tests in asset/cloud-client are inherently flaky

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2715]
Reviewing QuickstartIT, it:
* creates a bucket
* Writes a list of assets to the bucket
* wants to see that bucket in the list of assets
* deletes the bucket.

It should instead:
* Write to a well known bucket w/ gs:/well-known-bucket/UUID/my-assets.txt
* See if well-known-bucket is in my-assets.txt

This way there isn't a hysteresis problem on creating and knowing about buckets.

Related to #2551

**Comment by lesv** [comment]
FYI @peter-zheng-g @dzlier-gcp @kurtisvg

**Comment by elharo** [comment]
I don't follow why this test is flaky. The current flow seems like it should work?

**Comment by lesv** [comment]
It was creating a bucket, then immediatly dealing w/ it.  What was happening was that occasionally, the bucket wasn't yet available.  That's fixed now.
