### ISSUE TITLE
Spanner samples should use the libraries-bom

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2718]
As noted in #2644 we all client samples should be using the `com.google.cloud:libraries-bom:5.1.0`, not `google-cloud-bom`

@olavloite PTAL
@nnegrey FYI
@elharo FYI

**Comment by elharo** [comment]
They'll also need to remove explicit version setting of gRPC, Guava, protbuf and other covered libraries.
