### ISSUE TITLE
Functions integration tests: wait for FF process to start instead of retrying request

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/java-docs-samples#2763]
Per @kurtisvg, we should wait for the local FF process to start before sending it requests.

(Currently, we simply retry the requests themselves.)

**Comment by ace-n** [comment]
A few options:

#### Constant`sleep`s
Use a `sleep` function with a constant amount (e.g. 500 ms) to give the emulator time to start up.

*This is what we initially did with Node, but @grant and I decided against it in favor of dynamic request retries (in case the FF process starts faster).*

#### Initialization retries
Check for an "initialized" message in the FF process' `stdout`. Keep retrying until it exists; then run the test.

#### Test request retries
Start the FF process, and retry the test request itself until it successfully completes.

*This is what we have now.*

#### `mvn exec`
Start the FF process _outside the test itself_.

**Question: how would we get `stdout` from this?**

**Comment by kurtisvg** [comment]
The constant wait approach has the disadvantage of being potentially wasteful.

Wrapping the function test in a retry has the disadvantage that it hides potentially flakey behavior in the test itself, brings in additional dependencies, and encourages users retrying in tests (which, IMO, is a testing anti-pattern). 

`Process` has the option retrieve stdout from an InputStream, so it seem relatively simply to wrap that in something like Scanner and wait until the "startup is ready" (or equivalent is safer). And suffer from neither of these problems.

For ideas on testing from outside the test itself, you may just want to add a separate CI check and bind some tests to a different goal. Then we can do something like this in each folder:
```sh
mvn function:run &
pid=$!
mvn test:e2e
pkill $pid
```

That said, the best devx would be if the plugin came with a goal (e.g. `mvn function:test`) that would start up the emulator, run the tests, then exit with the correct return code.
