### ISSUE TITLE
StreamingRecognizeClien error

### ISSUE THREAD

**Issue by Saharati90** [GoogleCloudPlatform/java-docs-samples#277]
I'm using  bin/speech-sample-streaming.sh to transcribe a 6 minutes audio file. It works perfectly for recognizing the fist sentence but after few seconds, I get this message:

com.examples.cloud.speech.StreamingRecognizeClient$1 onError
WARNING: recognize failed: Status{code=INTERNAL, description=Received EOS on DATA frame, cause=null}

**Comment by puneith** [comment]
@Saharati90 Do you mind attaching the audio file here?

**Comment by Saharati90** [comment]
@puneith Sorry, I can't. It's a private dataset.

**Comment by puneith** [comment]
Do you think its possible for you to reproduce the problem with some similar type of audio which you can share?

**Comment by Saharati90** [comment]
Same problem with the attached file

[sample.raw.zip](https://github.com/GoogleCloudPlatform/java-docs-samples/files/387402/sample.raw.zip)

**Comment by puneith** [comment]
@Saharati90 Thanks for your patience. We are working on finalizing a PR and we will get back to you shortly.

**Comment by puneith** [comment]
@Saharati90 The file which you sent is 32KHz and so that parameter needs to be set when you run the code. We have added a fix as well and so please get the recent copy of the code and retry.

**Comment by puneith** [comment]
@Saharati90 Due to inactivity I am closing this issue. Feel free to re-open if you still encounter issues after our added fix. Thanks!
