### ISSUE TITLE
ComputeEngineSample.java uses deprecated APIs

### ISSUE THREAD

**Issue by rameshvenk** [GoogleCloudPlatform/java-docs-samples#2885]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/compute/cmdline/src/main/java/ComputeEngineSample.java

### Did you change the file? If so, how?

```
GoogleCredentials credential = GoogleCredentials.getApplicationDefault();

HttpRequestInitializer httpRequestInitializer =
                new HttpCredentialsAdapter(credential);

Compute compute =
          new Compute.Builder(httpTransport, JSON_FACTORY, httpRequestInitializer)
              .setApplicationName(APPLICATION_NAME)
              .build();
```

## Describe the issue

The code uses the `GoogleCredential` class, but the api docs have it marked deprecated. The [API reference page](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert) also has the same error. After some help via [StackOverflow](https://stackoverflow.com/questions/61783816/authenticating-with-google-api-library-for-java-to-google-cloud) I was able to get this to work.

It would be helpful to update these examples as I feel they are critical for someone trying to navigate the vast maze of the Google APIs. The java sdk is very nice to use, but the authentication part feels a bit hard.

**Comment by lesv** [comment]
@chingor13 FYI
@JustinBeckwith FYI

**Comment by lesv** [comment]
@tequilarista PTAL

**Comment by lesv** [comment]
@averikitsch Do you own this?

**Comment by averikitsch** [comment]
There are no DPEs currently supporting Compute Engine in my knowledge. It would probably be a good idea to know what the priority is of maintaining/supporting these samples (@JustinBeckwith @tequilarista).

**Comment by lesv** [comment]
[GoogleCredential](https://googleapis.dev/java/google-api-client/latest/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.html) is deprecated. Samples should be updates to use [GoogleCredentials](https://github.com/googleapis/google-auth-library-java).
See Issue #2885

[Search results](https://github.com/GoogleCloudPlatform/java-docs-samples/search?q=GoogleCredential&unscoped_q=GoogleCredential)

**Comment by averikitsch** [comment]
Removing myself so it can be picked up by someone during the FixIt
