### ISSUE TITLE
Question: App engine Java 11 example for deploying Helidon?

### ISSUE THREAD

**Issue by ksurendra** [GoogleCloudPlatform/java-docs-samples#2890]
## Describe the issue
Any projects in-progress or plans to create an example for [Helidon](https://helidon.io/) at https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11 ?

There was a mention of Helidon (as an example framework though) at https://cloud.google.com/blog/products/application-development/turn-it-up-to-eleven-java-11-runtime-comes-to-app-engine

**Comment by averikitsch** [comment]
Currently, there are no plans to provide a Helidon example. If the app packages as a jar, the only step you'll need to do is add an app.yaml file similar to the other framework examples ([Spring Boot](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11/springboot-helloworld/src/main/appengine), [Vert.x](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11/vertx-helloworld/src/main/appengine)).

**Comment by barchetta** [comment]
For reference here is an example for Helidon SE:

- https://github.com/barchetta/helidon-google-app-engine-example/tree/master/helidon-quickstart-se

A couple things to note:

1. Make sure your application obeys the PORT environment variable, and configures its server to use that port.
2. Make sure your app.yaml is in the same directory as your jar and defines a custom entry point. The example above uses:
```
runtime: java11
entrypoint: java -Xmx64m -jar helidon-quickstart-se.jar
```
Helidon uses "thin" jars and App Engine seems to handle this AOK as mentioned here: https://cloud.google.com/appengine/docs/standard/java11/runtime#application_startup

**Comment by ksurendra** [comment]
Another example i developed is at https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2967
