### ISSUE TITLE
Is there any possible way to config SpeechContext?

### ISSUE THREAD

**Issue by alanywlee** [GoogleCloudPlatform/java-docs-samples#290]
Dear Sir,

Regarding to https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#google.cloud.speech.v1beta1.SpeechContext , I tried to add SpeechContext to RecognitionConfig, but SpeechContext field seems not yet being available to be config in latest version.  I am not sure if there is any way to config SpeechContext using api like newFileScopedGeneratedExtension?

Best regards,

Alan

**Comment by puneith** [comment]
@alanywlee SpeechContext is infact available. Can you please send me your code snippet?

**Comment by alanywlee** [comment]
So sorry I didn't notice there is already a newer version available.
After I update the latest version on 20160817. com.google.cloud.speech.v1beta1.RecognitionConfig and com.google.cloud.speech.v1beta1.SpeechContext indeed has method to config SpeechContext.

Thanks for your help anyway.
