### ISSUE TITLE
storage/json-api: listBucket throws a null pointer exception when called upon an empty bucket

### ISSUE THREAD

**Issue by MarcHebert** [GoogleCloudPlatform/java-docs-samples#291]
In StorageSample.java calling listBucket on a bucket that is empty will throw a null pointer exception instead of returning an empty list or null. As a result, in the main method, bucketContents will never be null despite there being an intended check and warning logged to System.out.

**Comment by jabubake** [comment]
@MarcHebert please re-open this issue if you still have issues.
@frankyn FYI
