### ISSUE TITLE
Update sample to use GoogleCredentials

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#2931]
[GoogleCredential](https://googleapis.dev/java/google-api-client/latest/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.html) is deprecated. Samples should be updates to use [GoogleCredentials](https://github.com/googleapis/google-auth-library-java).
See Issue #2885 

[Search results.](https://github.com/GoogleCloudPlatform/java-docs-samples/search?q=GoogleCredential&unscoped_q=GoogleCredential)

**Comment by lesv** [comment]
This is a duplicate of #2885
