### ISSUE TITLE
Android app - v3 advanced Translation - No functional channel service provider found

### ISSUE THREAD

**Issue by eloisance** [GoogleCloudPlatform/java-docs-samples#2944]
Try to use v3 advanced Translate API in my android app, getting this error when I tried to use service account credentials :

**io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact**

Am I doing something wrong?

Gradle :

`implementation 'com.google.cloud:google-cloud-translate:1.94.5'`

My code :

```
val stream: InputStream = resources.openRawResource(com.example.R.raw.service_account)
val credentials = GoogleCredentials
    .fromStream(stream)
    .createScoped(Lists.newArrayList(Collections.singleton("https://www.googleapis.com/auth/cloud-platform")))

val translationServiceSettings = TranslationServiceSettings.newBuilder()
    .setCredentialsProvider(FixedCredentialsProvider.create(credentials))
    .build()

val client = TranslationServiceClient.create(translationServiceSettings)
val parent = LocationName.of("some_key", "global")

val request = TranslateTextRequest.newBuilder()
    .setParent(parent.toString())
    .setMimeType("text/plain")
    .setSourceLanguageCode("en")
    .setTargetLanguageCode("fr")
    .addContents(word)
    .build()

val response = client.translateText(request)
```

**Comment by lesv** [comment]
We don't normally support Android out of our repos.  You might wish to look at the Firebase documentation: https://firebase.google.com/docs/ml-kit/translation and I found a blog post, but I can't say how accurate it is.
https://medium.com/@yeksancansu/how-to-use-google-translate-api-in-android-studio-projects-7f09cae320c7

In general, if there is a Firebase or GMS Core (android) way, that is preferred to using our client libraries directly.

@JustinBeckwith FYI
