### ISSUE TITLE
App Engine samples - remove explict MaxRAM, ActiveProcessorCount, and mx configurations

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/java-docs-samples#2947]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java11/springboot-helloworld/src/main/appengine/app.yaml

There are probably more.

### Did you change the file? If so, how?

No

## Describe the issue

```
# Explicitly set the memory limit and maximum heap size ...
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
```

These were needed during beta due to lack of cgroup information. These are no longer required in App Engine Java 11 GA and should be removed.  Customers were finding this, using it, and asking about why this is needed; it can be completely removed..

**Comment by achuinard** [comment]
I still think these flags provide a benefit for my App Engine app. I ran some load tests against my production instance with and without these flags and without the flags my instances flaked a little bit (non-200 and requests taking 9-10 seconds) but when I added these flags for my F4 instance:

```JAVA_TOOL_OPTIONS: "-XX:MaxRAM=960m -XX:ActiveProcessorCount=2 -Xmx800m"```

It ran perfect with 0 failures and 4-5 second average latency.

**Comment by achuinard** [comment]
No one ever answered me, but this flag has been a tremendous performance boost for my application. I encourage anyone seeing latency issues to consider trying this, and wish there'd be more clarification from the GAE side as to why you decided this was no longer needed.
