### ISSUE TITLE
Some samples do not pass checkstyle

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/java-docs-samples#298]
`compute/error-reporting` did not have the parent pom defined.

Example: `ExceptionUtil.java:28: error: 'member def modifier' have incorrect indentat...`

Samples that need updating include:
- [ ] `compute/error-reporting`
- [ ] `compute/sendgrid`
- [ ] `appengine/taskqueue/pull`

**Comment by tswast** [comment]
Same for `compute/sendgrid`.

**Comment by tswast** [comment]
Tracking internally b/31241803

**Comment by tswast** [comment]
Also `appengine/taskqueue/pull`.

**Comment by lesv** [comment]
I think checkstyle passes everything now.
