### ISSUE TITLE
vision/AutoML should be updated to v1 (from v1beta1)

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#3003]

**Comment by stephaniewang526** [comment]
Please clarify the scope of this request -- check with product/tech writer on what needs to be updated on what pages.

**Comment by lesv** [comment]
Actually, I'm not on the appropiate team for that, you are.

**Comment by lesv** [comment]
Have you had a chance to ask your team what's up w/ this api?

**Comment by lesv** [comment]
ping

**Comment by munkhuushmgl** [comment]
@lesv I will ask from my team.

**Comment by stephaniewang526** [comment]
@munkhuushmgl PTAL

**Comment by munkhuushmgl** [comment]
@stephaniewang526 @lesv PTAL 

https://github.com/googleapis/java-automl/pull/385

**Comment by lesv** [comment]
approved
