### ISSUE TITLE
Missing classes in Maven Central artifact

### ISSUE THREAD

**Issue by spanishkangaroo** [GoogleCloudPlatform/java-docs-samples#3015]
In maven artifact

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-dialogflow</artifactId>
  <version>2.0.0</version>
</dependency>

A lot of classes are missing from version 1.0.0. Even in the docs, some classes such as com.google.cloud.dialogflow.v2beta1.SessionName are listed but are not actually included in the jar file or any other direct dependency.

**Comment by lesv** [comment]
@chingor13 Jeff - Not sure what's going on here, could you triage?

**Comment by lesv** [comment]
ping

**Comment by lesv** [comment]
I'm going to close, please reopen if the issue reapears.
