### ISSUE TITLE
dataproc Test Failed for Dep Update

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#3039]
PR #3030 
[Test Results](https://source.cloud.google.com/results/invocations/7b466546-861b-4fa1-80f7-88d732c56eb9/log)

**Comment by bradmiro** [comment]
Cause identified: [b/158098991](b/158098991)

**Comment by bradmiro** [comment]
0.122.2 fixes this. Closing.
