### ISSUE TITLE
scala-hello-pubsub - deprecations

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#3121]
```
------------------------------------------------------------
- testing functions/helloworld/scala-hello-pubsub
------------------------------------------------------------
/tmp/scala-maven-plugin-compiler-bridge-sources18122220553465268983/xsbt/DelegatingReporter.scala:187: warning: match may not be exhaustive.
It would fail on the following inputs: ERROR, INFO, WARNING
    sev match {
    ^
warning: 1 deprecation
warning: 4 deprecations (since 2.12.0)
warning: 4 deprecations (since 2.12.5)
warning: 2 deprecations (since 2.12.9)
warning: 2 deprecations (since 2.13)
warning: 7 deprecations (since 2.13.0)
warning: 20 deprecations in total; re-run with -deprecation for details
warning: 3 feature warnings; re-run with -feature for details
9 warnings

 Testing completed.
```

**Comment by lesv** [comment]
ping

**Comment by ace-n** [comment]
I was able to reproduce this, but only once. Perhaps it's a flaky build?

(If not, can you tell me which CLI flags I should use in `mvn clean verify` to display it consistently?)

**Comment by lesv** [comment]
@ace-n I installed scala `sdk install scala 2.13.3` using [sdkman](https://sdkman.io), using java 11.
```
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```
did `mvn clean package` and got:

```
/var/folders/_1/thsh_7h11wgfw3bg02x9gp180044fd/T/scala-maven-plugin-compiler-bridge-sources10636815793396786673/xsbt/DelegatingReporter.scala:187: warning: match may not be exhaustive.
It would fail on the following inputs: ERROR, INFO, WARNING
    sev match {
    ^
warning: 1 deprecation
warning: 4 deprecations (since 2.12.0)
warning: 4 deprecations (since 2.12.5)
warning: 2 deprecations (since 2.12.9)
warning: 2 deprecations (since 2.13)
warning: 7 deprecations (since 2.13.0)
warning: 2 deprecations (since 2.13.3)
warning: 22 deprecations in total; re-run with -deprecation for details
warning: 3 feature warnings; re-run with -feature for details
10 warnings
[INFO] Compiler bridge installed
[INFO] Compiling 2 Scala sources to /Users/lesv/github/java-docs-samples/functions/helloworld/scala-hello-pubsub/target/classes ...
[INFO] Done compiling.
[INFO] compile in 10.2 s
```

That said, It also said:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running functions.ScalaHelloPubSubTest
Jul 20, 2020 3:13:52 PM functions.ScalaHelloPubSub accept
INFO: Hello John!
Jul 20, 2020 3:13:52 PM functions.ScalaHelloPubSub accept
INFO: Hello world!
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.179 s - in functions.ScalaHelloPubSubTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```
and
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.622 s
[INFO] Finished at: 2020-07-20T15:13:53-07:00
[INFO] ------------------------------------------------------------------------
```

This is probably something that should be looked at, but I'm going to make it a P3.

**Comment by ace-n** [comment]
Thanks - tried that too (on my Mac), and still wasn't able to repro. 😕

*Maybe* it's mostly a Linux thing?

**Comment by lesv** [comment]
I did it on my Mac.

**Comment by ace-n** [comment]
I'm still not able to reproduce this, despite trying several options:
1) Add the following to `pom.xml`:
```
<args>
          <arg>-unchecked</arg>
          <arg>-deprecation</arg>
          <arg>-explaintypes</arg>
        </args>
```
2) Run `mvn clean package -DaddScalacArgs=-deprecation`
3) Remove all build-generated files (`*.iml` and `target/`) locally.

@lesv if you still think this should be fixed, can you schedule a VC with me so we can figure out how to repro this?

**Comment by lesv** [comment]
Looking at: https://g3c.corp.google.com/results/invocations/682329e3-c763-4fdb-baeb-695c41828b66/targets/cloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fcontinuous;config=default/log
From last night.  It still appears to happen.

------------------------------------------------------------
- testing functions/helloworld/scala-hello-pubsub
------------------------------------------------------------
/tmp/scala-maven-plugin-compiler-bridge-sources7389089759303673862/xsbt/DelegatingReporter.scala:187: warning: match may not be exhaustive.
It would fail on the following inputs: ERROR, INFO, WARNING
    sev match {
    ^
warning: 4 deprecations (since 2.12.0)
warning: 4 deprecations (since 2.12.5)
warning: 2 deprecations (since 2.12.9)
warning: 2 deprecations (since 2.13)
warning: 7 deprecations (since 2.13.0)
warning: 2 deprecations (since 2.13.3)
warning: 1 deprecation (since 2.13.4)
warning: 22 deprecations in total; re-run with -deprecation for details
warning: 3 feature warnings; re-run with -feature for details
10 warnings

 Testing completed.

The image comes from: https://github.com/googleapis/testing-infra-docker

You can use [sdkman](https://sdkman.io/) to easily switch between java & maven versions.

**Comment by lesv** [comment]
Ace and I have looked into this and it only happens upon downloading an artifact from Maven-Central.  While weird, it appears to be harmless.  CNR any other time.
