### ISSUE TITLE
dialogflow/cloud-client should be rewritten to support v2

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#3207]
In #3130 upgrading to `com.google.cloud:google-cloud-dialogflow:2.0.0` there are many changes that break, so the sample should be rewritten.

@stephaniewang526 Could you find someone to work on this?

**Comment by stephaniewang526** [comment]
Assigning to Steve until we get dialog flow funding.

**Comment by lesv** [comment]
Ping

**Comment by munkhuushmgl** [comment]
> Ping

Started on it today, keep you updated if I have a blocker on this.

**Comment by munkhuushmgl** [comment]
@lesv Since im making changes in most of the files, Should I move and migrate PR in java-dialogflow repo?

**Comment by lesv** [comment]
That's up to you.  If you do, the typical work flow is:

* Move the files with all history to the new repo
* Find and fix all references in the docs - have a TW submit.
* Delete the version here.

It's probably easier if you first submit here, then do the move if you choose to do it.
