### ISSUE TITLE
Speech sample build error

### ISSUE THREAD

**Issue by haruyama001** [GoogleCloudPlatform/java-docs-samples#330]
Build error is
[INFO] Scanning for projects...
[INFO] Downloading: https://repo.maven.apache.org/maven2/com/google/cloud/shared-configuration/1.0.0/shared-configuration-1.0.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.google.cloud.speech:grpc-sample:1.0: Could not transfer artifact com.google.cloud:shared-configuration:pom:1.0.0 from/to central (https://repo.maven.apache.org/maven2): connect timed out and 'parent.relativePath' points at wrong local POM @ line 29, column 11

I think
<parent>~</parent> on pom.xml doesn't indicate the effective url.
<artifactId>shared-configuration</artifactId> and ../../java-repo-tools don't exist.

**Comment by imfr95** [comment]
I am also getting the same error.

**Comment by haruyama001** [comment]
My build error has occurred on the Eclipse.
I hope a developer to correct a Speech Java Sample.
Is there anyone who could normally do a build?

**Comment by imfr95** [comment]
I am getting this error on Eclipse and I also tried compiling the source directly through terminal and got the same error.

**Comment by tswast** [comment]
What version of Maven are you using?

**Comment by imfr95** [comment]
I am using v3.3.9. [Here is a screenshot of the error.](https://puu.sh/r2i3R/08a176b05f.png)

**Comment by tswast** [comment]
Okay, it looks like you did not clone the entire repository. The sample is looking for the [`java-repo-tools`](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/java-repo-tools) directory, which defines some plugins used for style checking and testing.

If you do not wish to download that directory, you can remove the `<parent>...</parent>` element from `pom.xml` and try to build. It is our intention that all samples should work without the parent element.

**Comment by tswast** [comment]
Okay, it looks like you did not clone the entire repository. The sample is looking for the [`java-repo-tools`](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/java-repo-tools) directory, which defines some plugins used for style checking and testing.

If you do not wish to download that directory, you can remove the `<parent>...</parent>` element from `pom.xml` and try to build. It is our intention that all samples should work without the parent element.

**Comment by imfr95** [comment]
Yes, it compiled when I downloaded the whole repository. Thank you.

**Comment by srikanth-padmanabhuni** [comment]
No the issue was still Exsisted

You can see the errors below in screenshot
![image](https://user-images.githubusercontent.com/43059655/50534378-b51fbc80-0b61-11e9-85a8-88841c50ab79.png)

This is my pom
![image](https://user-images.githubusercontent.com/43059655/50534380-cbc61380-0b61-11e9-9099-b68d6d9cc5da.png)
