### ISSUE TITLE
Example for connecting from Cloud Run to Cloud Sql

### ISSUE THREAD

**Issue by safield** [GoogleCloudPlatform/java-docs-samples#3313]
It would be nice if there were an example of establishing a connection from a Cloud Run instance to a Cloud sql instance, where it clearly and explicitly describes how the connection url should be formed.

**Comment by shubha-rajan** [comment]
Hi @safield, we currently have documentation [here](https://cloud.google.com/sql/docs/postgres/connect-run#public-ip-default) for how to form the a connection URL when connecting with Cloud Run: . We recommend using the [Cloud SQL JDBC Socket Factory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory) along with the recommended JDBC driver for your database engine. You also have the option of connecting using a Private IP address (currently in beta), and the steps to configure your application to do that are [here](https://cloud.google.com/sql/docs/postgres/connect-run#private-ip). Examples for how to form a connection string given an IP address can be found in the documentation for your driver (for example, the connection info for Postgres is [here](https://jdbc.postgresql.org/documentation/head/connect.html)).

If there's any specific information that's missing in the links above that you're looking for, please reply and we can work on updating our samples.

**Comment by lesv** [comment]
I'm going to close this then, feel free to reopen.
