### ISSUE TITLE
I have checkout and try to use google cloud endpoint demo after following all the steps api is not listed in endpoint 

### ISSUE THREAD

**Issue by bhargavm-zymr** [GoogleCloudPlatform/java-docs-samples#339]
![issue github1](https://cloud.githubusercontent.com/assets/20836268/18576655/27ab04d2-7c01-11e6-8b5f-c3028c1f1d7d.PNG)

Hi i have follow all the instructions please guide me for creating endpoint.

**Comment by wmwong** [comment]
What is your API name? And could you link me to the instructions you were following?

**Comment by daughtry** [comment]
The screenshot you posted shows an endpoint listed.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 964 days. You may reopen this issue if it has been closed in error.
