### ISSUE TITLE
Dataflow templates mixing camelCase and snake_case

### ISSUE THREAD

**Issue by llamasoft** [GoogleCloudPlatform/java-docs-samples#3514]
The documentation on [traditional Dataflow templates](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#metadata-parameters)  has the `parameter` fields in "snake_case" style, but the [immediately proceeding example](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#example-metadata-file) uses camelCase for the field names, specifically `helpText`.

This applies to the following files in this repo:
- dataflow/flex-templates/kafka_to_bigquery/metadata.json
- dataflow/flex-templates/streaming_beam_sql/metadata.json

Both of the above also include the field `is_optional` in snake_case despite `helpText` being in camelCase form which contradicts the documentation.

Are both camelCase and snake_case allowed for these fields?  If so, the documentation should probably state as much.  Regardless, the style within a single file should remain consistent.

**Comment by davidcavazos** [comment]
I just asked, and it looks like both `camelCase` and `snake_case` are allowed. It's just a matter of style depending, usually `camelCase` for Java and `snake_case` for Python.

I'll update the docs and samples to reflect it.
