### ISSUE TITLE
Google Cloud Speech + App engine using java white listed gRPC channel builder

### ISSUE THREAD

**Issue by manjunaras** [GoogleCloudPlatform/java-docs-samples#356]
I am building java based google cloud speech streaming recognize service app in app engine so different applications consuming this service will send browser recording microphone streaming audio as PCM chunks to get response transcript and it works fine in standalone using socket.io (StreamingRecognize.java) when we create` servlet, Google channel API with the mashup code from StreamingRecognize.java and we deploy in app engine it throws white listed error while getting gRPC connection build in ManagedChannel. 

Is GAE have accessibility to run gRPC client with HTTP2 support?

@Override
    public void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
       GoogleCredentials creds = GoogleCredentials.getApplicationDefault();
    	creds = creds.createScoped(OAUTH2_SCOPES);
	  ManagedChannel	channel =  ManagedChannelBuilder
									.forAddress("speech.googleapis.com", 443)	
									.intercept(new ClientAuthInterceptor(creds, Executors.newSingleThreadExecutor()))
									.build();
.....

![image](https://cloud.githubusercontent.com/assets/22448665/19232577/20e3d380-8efe-11e6-9041-99cddf6df07c.png)

**Comment by lesv** [comment]
GAE Standard doesn't yet support gRPC - it's close.

**Comment by manjunaras** [comment]
@lesv : Thanks a lot. If GAE doesn't support, any other web server or VM servers supports gRPC with HTTP2? i tried with tomcat 8 and 9 but no ALPN configured yet.
Any solution to deploy is acceptable?

**Comment by lesv** [comment]
gRPC no longer requires ALPN, if your looking at code that still uses it, we should fix it.  I can easily make this stuff work w/ Jetty.  (GAE Flex)  You should be using [netty-borringssl-static](https://github.com/grpc/grpc-java/blob/master/SECURITY.md).  

I didn't need any special configuration to make that work for Jetty, so I don't think you'll need it for Tomcat.  If you can't make it work w/ that, ping, and I'll spend some time getting stuff to work w/ tomcat 9.

**Comment by lesv** [comment]
manjunaras and I have exchanged emails, he's going to move to GAE Flex using our Jetty images as a base image.  I'm going to close this.
