### ISSUE TITLE
Update Docs for Java 11?

### ISSUE THREAD

**Issue by dweekly** [GoogleCloudPlatform/java-docs-samples#3620]
It looks like this repository of samples hasn't been updated in two years.

Could I request sample docs for Java 11 environment?

**Comment by averikitsch** [comment]
Hi @dweekly, this repo is updated daily. Are looking for code samples for the App Engine Java 11 environment? You can find those: [appengine-java11](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11).

**Comment by dweekly** [comment]
Presto! I was looking at the wrong part. Thank you!
