### ISSUE TITLE
PMD errors in automl

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/java-docs-samples#3653]
#
# automl/cloud-client
#

     [java] JVM args ignored when same JVM is used.
[ERROR] Dead store to response in com.example.automl.BatchPredict.batchPredict(String, String, String, String) [com.example.automl.BatchPredict] At BatchPredict.java:[line 70] DLS_DEAD_LOCAL_STORE
[ERROR] Format string should use %n rather than \n in com.example.automl.DeleteDataset.deleteDataset(String, String) [com.example.automl.DeleteDataset] At DeleteDataset.java:[line 45] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ExportDataset.exportDataset(String, String, String) [com.example.automl.ExportDataset] At ExportDataset.java:[line 56] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.GetDataset.getDataset(String, String) appears to call the same method on the same object redundantly [com.example.automl.GetDataset] At GetDataset.java:[line 60] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 83] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 86] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 59] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 57] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 56] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 50] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 92] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 98] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 76] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 66] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetDataset.getDataset(String, String) [com.example.automl.GetDataset] At GetDataset.java:[line 71] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.GetModel.getModel(String, String) appears to call the same method on the same object redundantly [com.example.automl.GetModel] At GetModel.java:[line 55] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModel.getModel(String, String) [com.example.automl.GetModel] At GetModel.java:[line 55] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModel.getModel(String, String) [com.example.automl.GetModel] At GetModel.java:[line 54] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModel.getModel(String, String) [com.example.automl.GetModel] At GetModel.java:[line 56] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModel.getModel(String, String) [com.example.automl.GetModel] At GetModel.java:[line 52] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModel.getModel(String, String) [com.example.automl.GetModel] At GetModel.java:[line 51] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModel.getModel(String, String) [com.example.automl.GetModel] At GetModel.java:[line 45] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) appears to call the same method on the same object redundantly [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 59] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 58] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 80] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 67] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 55] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 93] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 73] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetModelEvaluation.getModelEvaluation(String, String, String) [com.example.automl.GetModelEvaluation] At GetModelEvaluation.java:[line 87] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetOperationStatus.getOperationStatus(String) [com.example.automl.GetOperationStatus] At GetOperationStatus.java:[line 51] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetOperationStatus.getOperationStatus(String) [com.example.automl.GetOperationStatus] At GetOperationStatus.java:[line 52] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetOperationStatus.getOperationStatus(String) [com.example.automl.GetOperationStatus] At GetOperationStatus.java:[line 45] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetOperationStatus.getOperationStatus(String) [com.example.automl.GetOperationStatus] At GetOperationStatus.java:[line 44] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetOperationStatus.getOperationStatus(String) [com.example.automl.GetOperationStatus] At GetOperationStatus.java:[line 43] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.GetOperationStatus.getOperationStatus(String) [com.example.automl.GetOperationStatus] At GetOperationStatus.java:[line 47] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionCreateDataset.createDataset(String, String) [com.example.automl.LanguageEntityExtractionCreateDataset] At LanguageEntityExtractionCreateDataset.java:[line 66] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionCreateDataset.createDataset(String, String) [com.example.automl.LanguageEntityExtractionCreateDataset] At LanguageEntityExtractionCreateDataset.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionCreateModel.createModel(String, String, String) [com.example.automl.LanguageEntityExtractionCreateModel] At LanguageEntityExtractionCreateModel.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.LanguageEntityExtractionPredict.predict(String, String, String) appears to call the same method on the same object redundantly [com.example.automl.LanguageEntityExtractionPredict] At LanguageEntityExtractionPredict.java:[line 64] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionPredict.predict(String, String, String) [com.example.automl.LanguageEntityExtractionPredict] At LanguageEntityExtractionPredict.java:[line 67] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionPredict.predict(String, String, String) [com.example.automl.LanguageEntityExtractionPredict] At LanguageEntityExtractionPredict.java:[line 65] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionPredict.predict(String, String, String) [com.example.automl.LanguageEntityExtractionPredict] At LanguageEntityExtractionPredict.java:[line 62] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionPredict.predict(String, String, String) [com.example.automl.LanguageEntityExtractionPredict] At LanguageEntityExtractionPredict.java:[line 66] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageEntityExtractionPredict.predict(String, String, String) [com.example.automl.LanguageEntityExtractionPredict] At LanguageEntityExtractionPredict.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageSentimentAnalysisCreateDataset.createDataset(String, String) [com.example.automl.LanguageSentimentAnalysisCreateDataset] At LanguageSentimentAnalysisCreateDataset.java:[line 69] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageSentimentAnalysisCreateDataset.createDataset(String, String) [com.example.automl.LanguageSentimentAnalysisCreateDataset] At LanguageSentimentAnalysisCreateDataset.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageSentimentAnalysisCreateModel.createModel(String, String, String) [com.example.automl.LanguageSentimentAnalysisCreateModel] At LanguageSentimentAnalysisCreateModel.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageSentimentAnalysisPredict.predict(String, String, String) [com.example.automl.LanguageSentimentAnalysisPredict] At LanguageSentimentAnalysisPredict.java:[line 61] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageSentimentAnalysisPredict.predict(String, String, String) [com.example.automl.LanguageSentimentAnalysisPredict] At LanguageSentimentAnalysisPredict.java:[line 62] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageTextClassificationCreateDataset.createDataset(String, String) [com.example.automl.LanguageTextClassificationCreateDataset] At LanguageTextClassificationCreateDataset.java:[line 78] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageTextClassificationCreateDataset.createDataset(String, String) [com.example.automl.LanguageTextClassificationCreateDataset] At LanguageTextClassificationCreateDataset.java:[line 72] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageTextClassificationCreateModel.createModel(String, String, String) [com.example.automl.LanguageTextClassificationCreateModel] At LanguageTextClassificationCreateModel.java:[line 65] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageTextClassificationPredict.predict(String, String, String) [com.example.automl.LanguageTextClassificationPredict] At LanguageTextClassificationPredict.java:[line 61] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.LanguageTextClassificationPredict.predict(String, String, String) [com.example.automl.LanguageTextClassificationPredict] At LanguageTextClassificationPredict.java:[line 62] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.ListDatasets.listDatasets(String) appears to call the same method on the same object redundantly [com.example.automl.ListDatasets] At ListDatasets.java:[line 64] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 87] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 90] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 64] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 61] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 96] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 102] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 80] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 70] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 75] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListDatasets.listDatasets(String) [com.example.automl.ListDatasets] At ListDatasets.java:[line 54] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) appears to call the same method on the same object redundantly [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 61] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 82] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 69] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 62] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 57] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 95] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 75] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModelEvaluations.listModelEvaluations(String, String) [com.example.automl.ListModelEvaluations] At ListModelEvaluations.java:[line 89] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Method com.example.automl.ListModels.listModels(String) appears to call the same method on the same object redundantly [com.example.automl.ListModels] At ListModels.java:[line 64] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModels.listModels(String) [com.example.automl.ListModels] At ListModels.java:[line 64] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModels.listModels(String) [com.example.automl.ListModels] At ListModels.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModels.listModels(String) [com.example.automl.ListModels] At ListModels.java:[line 65] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModels.listModels(String) [com.example.automl.ListModels] At ListModels.java:[line 61] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModels.listModels(String) [com.example.automl.ListModels] At ListModels.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListModels.listModels(String) [com.example.automl.ListModels] At ListModels.java:[line 54] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListOperationStatus.listOperationStatus(String) [com.example.automl.ListOperationStatus] At ListOperationStatus.java:[line 59] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListOperationStatus.listOperationStatus(String) [com.example.automl.ListOperationStatus] At ListOperationStatus.java:[line 60] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListOperationStatus.listOperationStatus(String) [com.example.automl.ListOperationStatus] At ListOperationStatus.java:[line 53] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListOperationStatus.listOperationStatus(String) [com.example.automl.ListOperationStatus] At ListOperationStatus.java:[line 52] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListOperationStatus.listOperationStatus(String) [com.example.automl.ListOperationStatus] At ListOperationStatus.java:[line 51] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.ListOperationStatus.listOperationStatus(String) [com.example.automl.ListOperationStatus] At ListOperationStatus.java:[line 55] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.TranslateCreateDataset.createDataset(String, String) [com.example.automl.TranslateCreateDataset] At TranslateCreateDataset.java:[line 72] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.TranslateCreateDataset.createDataset(String, String) [com.example.automl.TranslateCreateDataset] At TranslateCreateDataset.java:[line 66] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.TranslateCreateModel.createModel(String, String, String) [com.example.automl.TranslateCreateModel] At TranslateCreateModel.java:[line 65] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Found reliance on default encoding in com.example.automl.TranslatePredict.predict(String, String, String): new String(byte[]) [com.example.automl.TranslatePredict] At TranslatePredict.java:[line 48] DM_DEFAULT_ENCODING
[ERROR] Method com.example.automl.TranslatePredict.predict(String, String, String) encodes String bytes without specifying the character encoding [com.example.automl.TranslatePredict] At TranslatePredict.java:[line 48] MDM_STRING_BYTES_ENCODING
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.automl.TranslatePredict] At TranslatePredict.java:[line 48] PATH_TRAVERSAL_IN
[ERROR] Format string should use %n rather than \n in com.example.automl.TranslatePredict.predict(String, String, String) [com.example.automl.TranslatePredict] At TranslatePredict.java:[line 58] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionClassificationCreateDataset.createDataset(String, String) [com.example.automl.VisionClassificationCreateDataset] At VisionClassificationCreateDataset.java:[line 76] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionClassificationCreateDataset.createDataset(String, String) [com.example.automl.VisionClassificationCreateDataset] At VisionClassificationCreateDataset.java:[line 70] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionClassificationCreateModel.createModel(String, String, String) [com.example.automl.VisionClassificationCreateModel] At VisionClassificationCreateModel.java:[line 65] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.automl.VisionClassificationPredict] At VisionClassificationPredict.java:[line 49] PATH_TRAVERSAL_IN
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionClassificationPredict.predict(String, String, String) [com.example.automl.VisionClassificationPredict] At VisionClassificationPredict.java:[line 63] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionClassificationPredict.predict(String, String, String) [com.example.automl.VisionClassificationPredict] At VisionClassificationPredict.java:[line 64] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionObjectDetectionCreateDataset.createDataset(String, String) [com.example.automl.VisionObjectDetectionCreateDataset] At VisionObjectDetectionCreateDataset.java:[line 67] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionObjectDetectionCreateDataset.createDataset(String, String) [com.example.automl.VisionObjectDetectionCreateDataset] At VisionObjectDetectionCreateDataset.java:[line 61] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionObjectDetectionCreateModel.createModel(String, String, String) [com.example.automl.VisionObjectDetectionCreateModel] At VisionObjectDetectionCreateModel.java:[line 64] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.example.automl.VisionObjectDetectionPredict] At VisionObjectDetectionPredict.java:[line 51] PATH_TRAVERSAL_IN
[ERROR] Method com.example.automl.VisionObjectDetectionPredict.predict(String, String, String) appears to call the same method on the same object redundantly [com.example.automl.VisionObjectDetectionPredict] At VisionObjectDetectionPredict.java:[line 68] PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionObjectDetectionPredict.predict(String, String, String) [com.example.automl.VisionObjectDetectionPredict] At VisionObjectDetectionPredict.java:[line 71] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionObjectDetectionPredict.predict(String, String, String) [com.example.automl.VisionObjectDetectionPredict] At VisionObjectDetectionPredict.java:[line 64] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Format string should use %n rather than \n in com.example.automl.VisionObjectDetectionPredict.predict(String, String, String) [com.example.automl.VisionObjectDetectionPredict] At VisionObjectDetectionPredict.java:[line 65] VA_FORMAT_STRING_USES_NEWLINE
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.0.0:check (analyze-compile) on project automl-google-cloud-samples: failed with 113 bugs and 0 errors -> [Help 1]

**Comment by munkhuushmgl** [comment]
@lesv What does PMD stand for? Is that static error analyzer related?

**Comment by lesv** [comment]
Yes - it's one that's used everywhere.  https://pmd.github.io/

**Comment by elharo** [comment]
Most (not all) of these are " Format string should use %n rather than \n" which is I think actively wrong and bad advice here. We do not want platform dependenct line separators. Probably we should turn off this particular warning.

**Comment by lesv** [comment]
https://stackoverflow.com/questions/31981136/difference-between-n-and-n-for-printing-a-new-line-in-java
`%n` is suppoed to be the platform independant way of doing things.

**Comment by elharo** [comment]
Nope, that's not applicable here. In fact it's actively wrong. We want the same output on all platforms,  not different output on different platforms. %n makes the code platform dependent which is exactly what we don't want.

**Comment by lesv** [comment]
Because we are checking for it in code?  Or because we send all output to sponge?
Why is it what we don't want here?  We are running things on at least Mac's, Windows, and Linux machines.

**Comment by elharo** [comment]
It varies from case to case. In the case where we're just printing to System.out %n is OK. This is some of the warnings, though \n works just fine in that case too.

In cases where we're writing a file or a string or comparing output for a test or sending data across a network, we want byte per byte identical output. We don't want to change the line separators based on where the client code runs.

**Comment by lesv** [comment]
Totally agree with you.  I think that's a much less common operation in our samples than you might think, in which case there are comments / annotations to disable the check in PMD.
