### ISSUE TITLE
RenovateBot misses updates in some pom.xml

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/java-docs-samples#3654]
## Describe the issue

RenovateBot sometimes misses updating pom.xml files. For example, even after https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3633 is merged, `translate/cloud-client/pom.xml` has old version of 9.1.0:

```
suztomo-macbookpro44% find . -name pom.xml |xargs grep -A 3 '<artifactId>libraries-bom'
./video/beta/pom.xml:        <artifactId>libraries-bom</artifactId>
./video/beta/pom.xml-        <version>10.0.0</version>
...
--
./translate/cloud-client/pom.xml:        <artifactId>libraries-bom</artifactId>
./translate/cloud-client/pom.xml-        <version>9.1.0</version>
./translate/cloud-client/pom.xml-        <type>pom</type>
./translate/cloud-client/pom.xml-        <scope>import</scope>
--
...
./automl/cloud-client/pom.xml:        <artifactId>libraries-bom</artifactId>
./automl/cloud-client/pom.xml-        <version>7.0.2</version>
...
```

https://gist.github.com/suztomo/ed57585fc6d592a5851f3d3714e0e3d8

CC: @elharo

**Comment by suztomo** [comment]
@elharo For the pull request 3633, it was @lesv who excluded some pom.xml files from the upgrade, not RenovateBot:

- `./translate/cloud-client/pom.xml` was reverted in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3633/commits/8bdb0b77b89154528155fbc71417cbc54c6f7918 .
- `./automl/cloud-client/pom.xml` was reverted in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3633/commits/22f7df3b1ff25b1e278f23876cf3be6ce3b38c4e .

Does this information answer your question on sometimes samples are not updated to the latest libraries-bom?

We need to investigate why translate and automl cannot use the latest BOM.

**Comment by lesv** [comment]
Yep - when a very large PR like this doesn't pass, we revert things.  I used to put @elharo on the PR, but it wasn't his issue.

 I've written Issues like #3550 for both of those several times and they just don't get fixed.  Renovate is working in this case.

**Comment by lesv** [comment]
I'm going to close this as it's WAI.  Feel free to reopen if you disagree.  If you do please say what you'd like us to do about it.
