### ISSUE TITLE
Kokoro CI - Static analysis fails: "invalid target release: 11"

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/java-docs-samples#3672]
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3671 "Kokoro CI - Static analysis" fails. 

<img width="895" alt="Screen Shot 2020-09-08 at 16 26 36" src="https://user-images.githubusercontent.com/28604/92524415-1382b680-f1f0-11ea-9bd0-b074411707f6.png">

Even when the change is just adding an XML comment (https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3671/commits/395210c9154b4e8d540bed6ea164cb61b9e96cfe), the "Details" page shows `invalid target release: 11`.

```
#
# translate/cloud-client
#

[ERROR] COMPILATION ERROR :
[ERROR] javac: invalid target release: 11
Usage: javac <options> <source files>
use --help for a list of possible options

```

**Comment by lesv** [comment]
@suztomo Could you create this issue in GoogleCloudPlatform/java-repo-tools ??

**Comment by suztomo** [comment]
Done https://github.com/GoogleCloudPlatform/java-repo-tools/issues/175
