### ISSUE TITLE
Error while creating OperationsClient from operationsSetting 

### ISSUE THREAD

**Issue by ranjit5311** [GoogleCloudPlatform/java-docs-samples#3705]
**OperationsClient issue**

There is no example provide to create OperationClient from operationName (which is fetch after batch translation is submitted)

I have submitted google batchTranslation and got the operationId (projects/<projectId>/locations/us-central1/operations/<operations>).

now I want to check the status of this operation by pooling. Here I have used below  dependencies

 <dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>libraries-bom</artifactId>
      <version>9.1.0</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-translate</artifactId>
  </dependency>
</dependencies>
                
                
                Add below code in java class:
                //serviceKey is String containing service Account json file content as string 
                GoogleCredentials credentials = GoogleCredentials
                                                                                .fromStream(new ByteArrayInputStream(serviceKey.getBytes()))
                                                                                .createScoped(Lists.newArrayList("https://clicktime.symantec.com/3TWFMHceuuMgwf8KebwWinm7Vc?u=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2522%29%29%3B
                OperationsSettings operationsSettings =                OperationsSettings.newBuilder().setCredentialsProvider(FixedCredentialsProvider.create(credentials)).build();
                OperationsClient operationsClient = OperationsClient.create(operationsSettings);
                
                
But here I am getting **nullpointerException** when Trying to create OperationClient
java.lang.NullPointerException
                at com.google.longrunning.stub.OperationsStubSettings.createStub(OperationsStubSettings.java:107)
                at com.google.longrunning.OperationsClient.<init>(OperationsClient.java:143)
                at com.google.longrunning.OperationsClient.create(OperationsClient.java:125)

on further investigation found that OperationsSettings created have transportChannelProvider as null.

Please guide me am I missing something in creating OperationSettings/OperationClient.
Guide to get the best way to find the status of operation in java.

Thanks,
Ranjit Kumar

**Comment by munkhuushmgl** [comment]
@ranjit5311 Have you tried using this sample?
https://github.com/googleapis/java-automl/blob/master/samples/snippets/src/main/java/com/example/automl/GetOperationStatus.java
