### ISSUE TITLE
GCSEvent

### ISSUE THREAD

**Issue by kate-github-apps** [GoogleCloudPlatform/java-docs-samples#3761]
Is there a chance to include maven dependency  to my project with package containing definition of GCSEvent.java or I need to copy it?

**Comment by averikitsch** [comment]
At this time, you will need to copy the file. A library is in the process of being created, [Google CloudEvents](https://github.com/googleapis/google-cloudevents-java).

**Comment by averikitsch** [comment]
@grant

**Comment by grant** [comment]
@ace-n
