### ISSUE TITLE
spanner: update the code sample to set timeout at method level

### ISSUE THREAD

**Issue by hengfengli** [GoogleCloudPlatform/java-docs-samples#3805]
The current code sample of setting the custom timeout is based on the client level. We recently have added the ability to set the timeout at the method level: https://github.com/googleapis/java-spanner/pull/379. Are we able to update the existing code sample?

**Comment by olavloite** [comment]
@hengfengli The current sample shows how to set [both custom timeout and retry settings](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/69b9460f4922581317652bc5027e47827e17bd6e/spanner/cloud-client/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java#L53). The new feature that we added supports setting a timeout per method call, but not retry settings. So there are a couple of possible changes that we could do:
1. Change the sample to only set a custom timeout, and not custom retry settings.
1. Change the sample to set custom retry settings for the `ExecuteSql` method for __all calls__ (i.e. what the current sample does), and a custom timeout for a specific call.
1. Add a new sample that sets a custom timeout for a specific call.

My preference would be option 1, as it keeps the sample relatively simple and shows the most common use case. Setting a custom timeout is something many users might want to do, setting custom retry codes is not something many users would (should) do.

WDYT?

**Comment by hengfengli** [comment]
@olavloite Sorry for the late reply. Option 1 sounds okay to me. But the only issue is that now we have a public page for this code sample: https://cloud.google.com/spanner/docs/custom-timeout-and-retry. If we choose Option 1, then the code does not match the text.

**Comment by olavloite** [comment]
> @olavloite Sorry for the late reply. Option 1 sounds okay to me. But the only issue is that now we have a public page for this code sample: https://cloud.google.com/spanner/docs/custom-timeout-and-retry. If we choose Option 1, then the code does not match the text.

Hmm... Then I don't think we should use option 1, at least not for this specific sample. I would then suggest adding a separate sample for only setting a timeout for a specific call. That won't show up in the documentation page, but at least people could find it in the sample code.

**Comment by hengfengli** [comment]
The plan sounds good to me.

**Comment by lesv** [comment]
What's the status of this?

**Comment by olavloite** [comment]
> What's the status of this?

Thanks for the ping, this had unfortunately fallen of my radar. The Spanner samples are currently (also) in the `java-spanner` repository. I've added a [PR for this over there](https://github.com/googleapis/java-spanner/pull/707) now.

@thiagotnunes Do you know what the status is of the samples at the moment? Should we add them to both the repositories? Or should they only be added to `java-spanner`.

**Comment by thiagotnunes** [comment]
@olavloite only `java-spanner` should be sufficient.
