### ISSUE TITLE
Can developer use another logging framework other than jul? eg: logback

### ISSUE THREAD

**Issue by peterweb2005** [GoogleCloudPlatform/java-docs-samples#3858]
dear all,

logback can be some what used, but with poor format, as the example:

https://stackoverflow.com/questions/56907355/spring-boot-app-engine-logs-not-properly-formatted

ie:

1, the log time flow to right side (but can be fixed with formatter)

2, the log level NOT properly shown, 
eg: when log error (level), the heading icon always be "i", which means info, should be "e"

thanks

**Comment by Daniel-Sanche** [comment]
Yes, we maintain a library integrating logback with Cloud Logging here: https://github.com/googleapis/java-logging-logback
