### ISSUE TITLE
Update samples for Artifact Registry

### ISSUE THREAD

**Issue by donmccasland** [GoogleCloudPlatform/java-docs-samples#4042]
Samples should now include examples of also using an artifact registry style url along with the container registry url.

Example:
Container Registry URL: gcr.io/my-project/my-repo/my-image
Artifact Registry    URL:  LOCATION-docker.pkg.dev/my-project/my-repo/my-image

**Comment by lesv** [comment]
ping @donmccasland should I close this?

**Comment by iennae** [comment]
This looks like we still need to do this; the PR was closed because it's stale.
