### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [GoogleCloudPlatform/java-docs-samples#4148]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/ADC

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by averikitsch** [comment]
There is no README in the repo with that link.

**Comment by MrCull** [comment]
Hi @averikitsch.
Apologies the details were not clear.

This is in README.md  line 36

In the rendered relative link in the makeup this translates to:
<a href="/GoogleCloudPlatform/java-docs-samples/blob/master/ADC">Setting Up Authentication for Server to Server Production Applications</a>

This is the screenshot.
![image](https://user-images.githubusercontent.com/16634034/98211887-a616ac00-1f3a-11eb-88df-bef40ece48d6.png)



I have created a new issue in my repo based on your feedback and the information provided could be more helpful.

**Comment by averikitsch** [comment]
Thank you for the new information. It looks like a mistake in markdown not in the actual link.
