### ISSUE TITLE
Missing Tests and Readme

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/java-docs-samples#418]
The following list of samples are missing tests and some READMEs.

- flexible/analytics
- flexible/async-rest
- flexible/cloudsql
- flexible/cloudstorage
- flexible/cron
- flexible/datastore (Missing README)
- flexible/disk (Missing README)
- flexible/endpoints
- flexible/extending-runtime
- flexible/mailgun
- flexible/mailjet
- flexible/memcache (ignore for now)
- flexible/sendgrid
- flexible/sparkjava
- flexible/static-files (Also Missing README)
- flexible/twilio
- appengine/analytics (Also Missing README)
- appengine/channel (Also Missing README)
- appengine/cloudsql (Also Missing README)
- appengine/endpoints-framework-v2/backend
- appengine/firebase-event-proxy/gae-firebase-event-proxy
- appengine/firebase-event-proxy/gae-firebase-listener-python
- appengine/helloworld-new-plugins
- appengine/images/
- appengine/logs/
- appengine/mail
- appengine/mailgun
- appengine/mailjet
- appengine/memcache (Also Missing README)
- appengine/oauth2
- appengine/remote
- appengine/sendgrid
- appengine/static-files (Also Missing README)
- appengine/taskqueue/pull
- appengine/twilio
- appengine/urlfetch
- compute/cmdline
- compute/error-reporting
- compute/sendgrid

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 935 days. You may reopen this issue if it has been closed in error.
