### ISSUE TITLE
Live Streaming using Speech API

### ISSUE THREAD

**Issue by abhi007tyagi** [GoogleCloudPlatform/java-docs-samples#429]
Is live streaming supported using Speech API?
How can I connect my mic and test the streaming api

**Comment by gguuss** [comment]
@abhi007tyagi Check out the [GRPC sample for an example of streaming](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech/grpc#user-content-run-the-streaming-client).

**Comment by awesomegtrr** [comment]
The samples doesn't even work.

**Comment by nnegrey** [comment]
We've added a sample that demonstrates mic streaming: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/Recognize.java#L622
