### ISSUE TITLE
Instructions to deploy to Cloud Run don't work in Cloud SQL sample

### ISSUE THREAD

**Issue by shubha-rajan** [GoogleCloudPlatform/java-docs-samples#4337]
## In which file did you encounter the issue?

[cloud-sql/mysql/servlet/README.md](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/cloud-sql/mysql/servlet/README.md)

### Did you change the file? If so, how?

No changes.

## Describe the issue
I followed the steps described in the README to deploy the sample to Cloud Run. However, when the app was deployed, the vote counts weren't displaying and popup messages were displaying raw HTML. The network requests return 200, and there didn't seem to be any errors when checking logs for Cloud SQL or Cloud Run.

<img width="1377" alt="Screen Shot 2020-12-02 at 1 49 55 PM" src="https://user-images.githubusercontent.com/19631367/100943345-ea518980-34b1-11eb-93fb-25a9f7ead25a.png">

![image](https://user-images.githubusercontent.com/19631367/100943636-782d7480-34b2-11eb-93cc-9d411c97f7ba.png)

**Comment by averikitsch** [comment]
A few notes:
* This works locally
* The README can be updated to combine the deploy + update steps into 1 deploy step. This also would benefit from flags: platform, region, and allow-unauthenticated. 
* reverting to a known working version doesn't work 😕

Using the Cloud Code debugger there's an error in the `UnixNativeDispatcher.stat(...` which is in the callstack of HttpServlet. I'll keep looking into it but @kvg do you have any ideas.

**Comment by kurtisvg** [comment]
I was able to replicate, and also determined that the issue seems to be specific to the docker image.

**Comment by kurtisvg** [comment]
Resolved by updating samples to use Jib to build the containers.
