### ISSUE TITLE
Spark version used in sample has vulnerability

### ISSUE THREAD

**Issue by rmcloughlin** [GoogleCloudPlatform/java-docs-samples#434]
In `flexible/sparkjava/pom.xml` the version of `com.sparkjava:spark-core` being used is 2.5.  This version has a vulnerability and as such version 2.5.2 or higher should be used instead.  See http://sparkjava.com/news.html#spark25vulnerability for more info.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 919 days. You may reopen this issue if it has been closed in error.
