### ISSUE TITLE
iot/api-client/manager & com.sun.xml.bind:jaxb-core v3 issues

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#4354]
Found in #4278

Appears to be a poorly written test

**Comment by lesv** [comment]
Also found in #4308

The test don't appear to be cleaning up after themselves.

**Comment by lesv** [comment]
And #4330

**Comment by eaball35** [comment]
#4367 couldn't update google-cloud-pubsub version to 1.110.0 in java-docs-samples/iot/api-client/manager

![Screen Shot 2020-12-09 at 4 00 42 PM](https://user-images.githubusercontent.com/47503699/101706492-0e771280-3a3e-11eb-801b-54dbc5c8283f.png)

Referring to "DeviceRegistryExample.createDeviceWithRs256(deviceName, RSA_PATH, PROJECT_ID, CLOUD_REGION, REGISTRY_ID);" where deviceName = "rsa-device-mqtt-state"

**Comment by eaball35** [comment]
Same issue as above
#4406 could not update google-cloud-pubsub version to 1.110.1 in java-docs-samples/iot/api-client/manager

**Comment by lesv** [comment]
ping @attilagargyan @simoncsaba-g
