### ISSUE TITLE
FR: Compute / cmdline seems to miss the point on deployment

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#440]
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/compute/cmdline

I like the idea generally of `mvn exec:java` or `mvn exec:exec`, but this isn't how anyone would do it in production.  We really should have a production example here.

@jerjou I'm assigning to you as you were mentioned as the last assignee, feel free to unassign.

**Comment by jerjou** [comment]
Haha... yeah... this makes sense.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 914 days. You may reopen this issue if it has been closed in error.
