### ISSUE TITLE
Correctly restore stdout after tests

### ISSUE THREAD

**Issue by chingor13** [GoogleCloudPlatform/java-docs-samples#4423]
We have many tests that overwrite stdout with a custom output stream and we call `System.setOut(null)` to attempt to restore stdout.

We need to either:
* capture the original `System.out` and restore that same instance
* use [`StdOutCaptureRule`](https://github.com/googleapis/java-core/blob/master/google-cloud-core/src/test/java/com/google/cloud/testing/junit4/StdOutCaptureRule.java) provided by `com.google.cloud:google-cloud-core`'s `tests` classifier (jar)

**Comment by b-loved-dreamer** [comment]
@chingor13, thank you for pointing this out. [Here](https://github.com/googleapis/java-speech/blob/master/samples/snippets/src/test/java/com/example/speech/SpeechProfanityFilterTest.java) is the fix for this issue just in case somebody needs a reference.

**Comment by b-loved-dreamer** [comment]
Closing this issue. It's used for reference in fixing this specific problem.

**Comment by kurtisvg** [comment]
I think there are a few other samples that still do this incorrectly, so I'm going to reopen so we don't forget about it.

**Comment by lesv** [comment]
The next release of shared-config will have the rule setup.

**Comment by lesv** [comment]
I'm going to close this, and we'll deal with individual issues and PR's for any of these we find.
