### ISSUE TITLE
Update Java samples for google-cloud to use latest library versions

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/java-docs-samples#443]
We have updated all of our libraries to a new version: https://github.com/GoogleCloudPlatform/google-cloud-java/releases.

Especially important is that BigQuery, Storage, Datastore, and Logging are now at Beta and their version is 0.8.0-beta.

We should update all our samples to test against the latest library for each of these APIs (the Beta ones and the rest too).

**Comment by tswast** [comment]
Fixed by https://github.com/GoogleCloudPlatform/java-docs-samples/pull/446
