### ISSUE TITLE
Create / Start Instance with Machine Image

### ISSUE THREAD

**Issue by felixbello** [GoogleCloudPlatform/java-docs-samples#4431]
I'm trying to use the function "public static Operation startInstance" to start an Instance but with a "Machine Image", I don't find any Information how to do it.

## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/compute/cmdline/src/main/java/ComputeEngineSample.java

**Comment by lesv** [comment]
https://cloud.google.com/compute/docs/reference/rest/v1/instances/start
