### ISSUE TITLE
XML API example does not work

### ISSUE THREAD

**Issue by dave-r12** [GoogleCloudPlatform/java-docs-samples#45]
Hello, was following the instructions on this page, https://cloud.google.com/storage/docs/xml-api-java-samples but could not successfully build the project with mvn clean install. I kept receiving a 403. I believe this is happening because I don't have permission on the 'cloud-samples-tests' bucket

**Comment by jerjou** [comment]
Thanks for catching this - I forgot that `mvn install` runs the tests, which isn't required for the sample to work. Running `mvn compile` should be sufficient - I've updated the docs to reflect that.
