### ISSUE TITLE
endpoints-frameworks-v2/backend project ServiceConfigException 

### ISSUE THREAD

**Issue by meggieclub** [GoogleCloudPlatform/java-docs-samples#459]
I built and deployed the endpoints-frameworks-v2/backend sample project following instructions in the latest Readme. Build and deployment were successful. Received Bad Gateway 502 response with sample curl request. Cloud console error detail is 

 12/18/16, 7:07 PM ServiceConfigException: Failed to fetch service config (status code 400) GET 0.1.echo-152904.appspot.com/_ah/start 500 Internal Server Error View request logs
12/18/16, 7:07 PM ServiceConfigException: Failed to fetch service config (status code 400)
Request
GET 0.1.echo-152904.appspot.com/_ah/start (View request logs)  
Status
500 Internal Server Error 

Please advise.

**Comment by frankyn** [comment]
@meggieclub  are still seeing this issue? 
If so, could you please check if the current version of the sample now works?
