### ISSUE TITLE
FR: SQL (Standard / Flexible) samples should have Integration Testing...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#461]
Wanted to put in when I last updated the samples, but not quite enough infrastructure to support.  Last update should have fixed that.

**Comment by jabubake** [comment]
@kurtisvg is this complete ?

**Comment by jabubake** [comment]
Given the age of this ticket, can we close this and move it to an internal queue @lesv  ?

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for {days_inactive} days. You may reopen this issue if it has been closed in error.
