### ISSUE TITLE
Include a sample for Cloud Run with server sent events(SSE).

### ISSUE THREAD

**Issue by PojahnM** [GoogleCloudPlatform/java-docs-samples#4632]
On October 8 2020, Cloud Run officially SSE(https://cloud.google.com/blog/products/serverless/cloud-run-now-supports-http-grpc-server-streaming). A sample using Spring Boot and SSE would be very helpful!

**Comment by averikitsch** [comment]
We may not be able to get to this request, but Cloud Run does not need any special implementation of SSE. I have found these resources helpful and work when deployed to Cloud Run:
* https://dzone.com/articles/server-sent-events-using-spring
* https://www.baeldung.com/spring-mvc-sse-streams
