### ISSUE TITLE
i have spring boot application wanna deploy using below command but it showing me error

### ISSUE THREAD

**Issue by localsonu** [GoogleCloudPlatform/java-docs-samples#4728]
Execution default-cli of goal com.google.cloud.tools:appengine-m
aven-plugin:2.2.0:deploy failed: com.google.cloud.tools.appengine.AppEngineException: java.nio.file.NoSuchFileException: /home/shazaibraza533/bottle-online-2/src/main/appengine/app.yaml

**Comment by localsonu** [comment]
mvn clean package appengine:deploy 
 use above command to deploy

**Comment by averikitsch** [comment]
Hi @localsonu, Spring boot apps deploy as JARs. Please use the Cloud SDK to deploy: `gcloud app deploy`, or add the file [`src/main/appengine/app.yaml`](https://cloud.google.com/appengine/docs/standard/java11/configuring-your-app-with-app-yaml) to deploy using the Maven plugin.

For more info see [Deploying an executable JAR](https://cloud.google.com/appengine/docs/standard/java11/testing-and-deploying-your-app#other_deployment_options).

**Comment by localsonu** [comment]
> 
> 
> Hi @localsonu, Spring boot apps deploy as JARs. Please use the Cloud SDK to deploy: `gcloud app deploy`, or add the file [`src/main/appengine/app.yaml`](https://cloud.google.com/appengine/docs/standard/java11/configuring-your-app-with-app-yaml) to deploy using the Maven plugin.
> 
> For more info see [Deploying an executable JAR](https://cloud.google.com/appengine/docs/standard/java11/testing-and-deploying-your-app#other_deployment_options).

yes thanks for your reply i did it in the same way but now when i open link in the browser it shows me 
"Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."

**Comment by averikitsch** [comment]
In which sample did you encounter the issue? Did you change the file? If so, how?

**Comment by averikitsch** [comment]
Please reopen if you continue to experience this issue.
