### ISSUE TITLE
Unnecessary `null` assignment in BigQuery Java example

### ISSUE THREAD

**Issue by polleyg** [GoogleCloudPlatform/java-docs-samples#477]
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/bigquery/cloud-client/src/main/java/com/example/bigquery/QuickstartSample.java#L35

No need to assign `null` here. All objects are `null` by default after declaration.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. You may reopen this issue if it has been closed in error.
