### ISSUE TITLE
Root certificate attachment issue

### ISSUE THREAD

**Issue by debduttaVxplore** [GoogleCloudPlatform/java-docs-samples#4982]
Node.js and python samples show root certificate attachment, but why not this java sample is not doing the same.
Is it possible to connect and publish successfully without attaching the root certificate?

The python sample:
![image](https://user-images.githubusercontent.com/61016410/113685946-62d88900-96e4-11eb-8233-ecc4ed9c796f.png)

The node.js sample:
![image](https://user-images.githubusercontent.com/61016410/113686055-7e439400-96e4-11eb-8507-0b4c6120d45e.png)

**Comment by lesv** [comment]
@gcseh Ping
