### ISSUE TITLE
Using specific translation

### ISSUE THREAD

**Issue by mghildiy** [GoogleCloudPlatform/java-docs-samples#509]
Hi,

Is it possible to tell the translator that if source text contains a given word, then translate it to a specific word instead of what the database throws up. I want this as many times translated text uses words which are not in pure form.

**Comment by gguuss** [comment]
I'm not sure you are able to do this currently. If you haven't already, you might want to also [try using the new premium (NMT) model](https://cloud.google.com/translate/docs/premium) as it may give you more natural translations.

**Comment by nnegrey** [comment]
Closing issue as it is relatively old and never received a follow-up. Feel free to re-open.
