### ISSUE TITLE
Pub/Sub Lite I/O connector IT

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/java-docs-samples#5113]
Need to update the test in `/pubsublite/streaming-analytics` to use GCP instead of Beam's test suite. 

- ~need a permanent test topic with some messages published~ `pubsublite-streaming-analytics` in `us-east1-b`
- need to create a test subscription to the topic
- ~need a permanent bucket for output~ `pubsublite-it`
- start the pipeline
- check if files are written to the bucket
- for cleanup, delete the files for this test, delete the Dataflow pipeline (not sure how to find its name), delete the test subscription. 

A tricky thing is we may need to wait 5-10 minutes for the pipeline to start up and start writing files to Cloud Storage.

**Comment by averikitsch** [comment]
The best approach would create and clean up resources, such as the bucket and Pub/Sub topic and subscription. You can do this either via the client library or run a `gcloud` command to submit a Cloud Build to setup the resources ([Node.js Example](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/run/image-processing/test/system.test.js#L39)).  In the before section I would also create some Pub/Sub message, then I would run the sample. Does the sample run to completion? Then in the test I would poll the storage bucket for the expected files ([Node.js example](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/run/image-processing/test/system.test.js#L106)). After you should delete the bucket, topic, and subscription. 

Does the sample print to the console? Then you can do what a lot of the other samples do by running the sample and capturing the output. With this approach it would be ok to have your bucket, topic and subscription as a static resource, but you would still have to preload the pub/sub messages.

**Comment by anguillanneuf** [comment]
@averikitsch Got it. I think managing resources should be good.

I'm a little stuck at finding out how to call https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java from https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java. How do I pass in the pipeline options from another program?

**Comment by anguillanneuf** [comment]
Here is an example: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/6a4a2affe7ac69d445f5d72ed57cfa468c76354c/monitoring/v3/src/test/java/com/example/AlertIT.java#L99

Below worked: 
```java
    PubsubliteToGcs.main(new String[] {
        "--subscription="+subscriptionPath.toString(),
        "--output=gs://"+bucketName+"/samples/output",
        "--windowSize=1",
        "--runner=DataflowRunner",
        "--project="+projectId,
        "--region="+cloudRegion,
        "--tempLocation=gs://"+bucketName+"/temp"
    });
```
