### ISSUE TITLE
BUG: appengine local tests fails using deprecated feature...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#513]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/pull/508
testConfig(com.google.appengine.samples.OAuthTest) Time elapsed: 0.31 sec <<< ERROR!
com.google.appengine.api.oauth.OAuthRequestException: Two-legged OAuth1 is not supported any more

### Did you change the file? If so, how?
No - needs to be changed.

**Comment by ludoch** [comment]
See internal reference b/32288507
User effect now see this error message: "Two-legged OAuth1 is not supported any more"

**Comment by lesv** [comment]
Sample fixed in #536
