### ISSUE TITLE
PubSub Streaming Sample Issue.

### ISSUE THREAD

**Issue by AristoK3** [GoogleCloudPlatform/java-docs-samples#5429]
I am trying to run this sample on google cloud shell with maven version 3.6.3.
Following Issue.

`failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java`

Please help me.

**Comment by anguillanneuf** [comment]
@AristoK3 Thanks for flagging this! 

The command line args in our docs needed an update. I just tried the following in Cloud Console and it worked:

```
mvn compile exec:java \
  -Dexec.mainClass=com.examples.pubsub.streaming.PubSubToGcs \
  -Dexec.cleanupDaemonThreads=false \
  -Dexec.args="\
    --project=$PROJECT_NAME \
    --region=$REGION \
    --inputTopic=projects/$PROJECT_NAME/topics/cron-topic \
    --output=gs://$BUCKET_NAME/samples/output \
    --gcpTempLocation=gs://$BUCKET_NAME/temp \
    --runner=DataflowRunner \
    --windowSize=2"
```

A fix is coming!
