### ISSUE TITLE
browser microphone streaming throgh websocketin StreamingRecognizieClient.java

### ISSUE THREAD

**Issue by manjunaras** [GoogleCloudPlatform/java-docs-samples#556]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/grpc/src/main/java/com/examples/cloud/speech/StreamingRecognizeClient.java

### Did you change the file? If so, how?
No

## Describe the issue

In StreamingRecognizeClient.java need to replace getAudioInputLine() with audio stream PCM samples coming from browser microphone through websocket.

**Comment by jerjou** [comment]
Hello! Thanks for the feedback. We're trying to keep the samples in this repo as simple as practical to accomplish the task we're trying to teach (in this case, communicating with the Speech API with streaming audio). Adding websockets isn't applicable to all use cases, so probably not appropriate for this repo.

That said, we have a [codelab](https://codelabs.developers.google.com/codelabs/speaking-with-a-webpage/index.html) that covers this, which also has a corresponding [repo](https://github.com/googlecodelabs/speaking-with-a-webpage/) with a sample solution that implements what you describe. Specifically, see [TranscribeSocket.java](https://github.com/googlecodelabs/speaking-with-a-webpage/blob/master/04-speech/src/main/java/com/example/flexible/speak/TranscribeSocket.java#L43), which listens on a websocket for data, that it then forwards to the Speech API.
