### ISSUE TITLE
New GAE Std sample(s) that uses Veneer (GCS, and more)

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#558]
See GoogleCloudPlatform/google-cloud-java#1742

Also need GAE Flex, and GAE Std 8

**Comment by lesv** [comment]
@jabubake If you have cycles, could you add pubsub, spanner samples to appengine-java8

**Comment by jabubake** [comment]
Will do this week, in order of priority : pubsub, then spanner.

**Comment by jabubake** [comment]
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/pubsub
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/spanner
