### ISSUE TITLE
GAE quickstart tutorial uses different appengine plugin 

### ISSUE THREAD

**Issue by shinfan** [GoogleCloudPlatform/java-docs-samples#559]
In the GAE quick-start tutorial it uses:
```xml
<groupId>com.google.cloud.tools</groupId>
<artifactId>appengine-maven-plugin</artifactId>
<version>${appengine-maven-plugin-version}</version>
```

which is different from the one used by sample. We should switch either one of them to keep them consistent.

**Comment by shinfan** [comment]
@lesv

**Comment by jerjou** [comment]
@tswast Would you mind looking at this? I believe this is referring to the tutorial within the cloud console, that uses [this code](https://github.com/GoogleCloudPlatform/appengine-try-java/blob/master/pom.xml#L107). Let me know if you don't have bandwidth, and I can take a shot at it (I figure it might be easier for you, though, if you're familiar with how to modify cloud-console tutorials)

**Comment by lesv** [comment]
This is actually a problem in Neos -- it shouldn't be using the new plugin yet.  Not sure where that hides.

**Comment by tswast** [comment]
What plugin should it use? Previously it was using the `gcloud` plugin to do deploys to App Engine standard because the old plugin was never updated to support deploys from Cloud Shell. See internal bug 33192132 where I updated the sample to the new plugin.

**Comment by lesv** [comment]
This is for GAE Std, I think, and all GAE Std deploy should use the Java SDK plugin.  GAE Flex should all use the gcloud SDK plugin.

There used to be a Flex plugin called gcloud that is deprecated.  Confusing?  Yep.

**Comment by tswast** [comment]
Yeah, except we can't use the Java SDK plugin in Neos because it doesn't understand the Cloud Shell credentials.

**Comment by lesv** [comment]
@shinfan I'm going to close this in 24h, unless you object.
@ludoch FYI - you might wish to go through the new user experience customers go through. (you might also object)

**Comment by ludoch** [comment]
Did you try the flag --service_account_json_key_file=path in the GA plugin?

https://cloud.google.com/appengine/docs/standard/java/tools/appcfg-arguments

**Comment by tswast** [comment]
The cloud shell uses the metadata server for authentication. We should not
have to download a service account JSON file to deploy.

**Comment by tswast** [comment]
It would seem like the `--use_google_application_default_credentials` would work, but it does not. See internal bug 28788572.

**Comment by jerjou** [comment]
Okay - it sounds like this would be more trouble than it's worth. Consistency would be great, but I think the onus is on the maven plugin team to make their plugins consistent (as opposed to on the samples, that are just doing what works).
