### ISSUE TITLE
Rewrite Compute sample for new API

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#5599]
Found in #5582

Compute sample should use the new API.

**Comment by lesv** [comment]
@donmccasland Please confirm we own compute.

**Comment by lesv** [comment]
@danoscarmike - should have been ping'd Dan.  

I'm presuming this should also go to @rsamborski for vis and to loop in his Compute team and @Sita04

**Comment by rsamborski** [comment]
@Sita04 please take a look at this issue
