### ISSUE TITLE
appengine-java8/helloworld project is broken

### ISSUE THREAD

**Issue by angryziber** [GoogleCloudPlatform/java-docs-samples#5696]
Cannot run `./gradle appengineDeploy` as specified in the docs

1. gradle-wrapper.jar is missing
2. gradle version was upgraded to 7.1.1, but it doesn't support `compile` configuration anymore - it should be changed to `implementation` and docs should be updated

**Comment by averikitsch** [comment]
@mpeddada1 PTAL

**Comment by mpeddada1** [comment]
Thanks for filing the issue! And thanks for the mention @averikitsch, I believe this is related to updating the [sample app](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/helloworld) as opposed to the functioning of the plugin. 

cc @chanseokoh

**Comment by averikitsch** [comment]
@mpeddada1 Does your team have gradle expertise to look at the sample app?

**Comment by mpeddada1** [comment]
Sure, I can take a look at it.
