### ISSUE TITLE
Should managed VM samples be reorganized?

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/java-docs-samples#57]
Both the managedvms folder and appengine folders have managed VMs samples.  Shouldn't they be placed in the same folder?

**Comment by tswast** [comment]
The https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine/appidentity sample is including from the Java App Engine docs for App Identity. It actually runs on managed VMs or standard App Engine if you remove <vm>true</vm>.

My understanding was that new samples should be Managed VMs if possible, but I put it in the App Engine folder for the reason that it is used from https://cloud.google.com/appengine/docs/java/appidentity/

**Comment by tswast** [comment]
Possibly we should remove the managedvms folder. I just noticed that the README.md in https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine/appidentity talks about Managed VMs.

**Comment by lesv** [comment]
I think we've done the renames and now the docs all point to the right place.  I'm closing.
