### ISSUE TITLE
endpoints echo GetSwaggerDoc

### ISSUE THREAD

**Issue by BDash2014** [GoogleCloudPlatform/java-docs-samples#593]
When trying to run goal "exec:java -DGetSwaggerDoc" in appengine/endpoints-frameworks-v2/backend/pom.xml I'm getting error "Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project echo: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid".
Sample is not working from latest plugins updates (Google Cloud Tools and Google Account 17.2.2_2017) for IntelliJ IDEA. Before uptade it worked normally. I also tried to install whole environment with example from scratch on clean computer to avoid it can be my changes to files with the same result.

**Comment by frankyn** [comment]
Hi @BDash2014!

Are you still seeing this issue?

**Comment by BDash2014** [comment]
Hello,

nope, after last updates its working again 

Honza

**Comment by frankyn** [comment]
Thanks @BDash2014! I'll close this issue.
