### ISSUE TITLE
Spring boot +Spring MVC

### ISSUE THREAD

**Issue by magicomajid** [GoogleCloudPlatform/java-docs-samples#594]
I use Spring MVC. Please Create a project using Spring boot deploying in Appengine Flexible.
Thanks

**Comment by jabubake** [comment]
Hi @magicomajid , have you looked at https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/helloworld-springboot ?

**Comment by jabubake** [comment]
@magicomajid Please checkout the tutorial : https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/run-spring-petclinic-on-app-engine-cloudsql.
We hope to add more soon.
