### ISSUE TITLE
Discussion: do we want to delete this repository?

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/java-docs-samples#6]
This repository had a Java unittest snippet, which was supposed to link from a docs page, but that task has not done yet.

Now we decided to have appengine-local-testing-samples repo and now it has unittest snippet. Do we want to delete this repo or just delete the unittest directory and add other snippets later?

@oalami @elibixby WDYT?

**Comment by elibixby** [comment]
Yes, this sounds good. Also this follows language specific naming scheme.

**Comment by tmatsuo** [comment]
So do you want to delete this repository?
or do you want to keep using this repo for other java snippets?

**Comment by elibixby** [comment]
Will delete shortly.

**Comment by tmatsuo** [comment]
@elibixby 

Sorry, I'm basically asking "which do you prefer?", but you don't answer to that question, either way I'm fine though.

I still prefer having language specific repos with multiple usecases over having usecase specific repos containing multiple languages, but it's just my 2 cents. I really like you taking the initiative. So do whatever you want (and learn from it ;P).

**Comment by elibixby** [comment]
Honestly, the more I think about it the more I agree with you. I don't like the idea of just having like 7 repos for all docs samples, because I think that would be way too much for a developer to clone. However, maybe if we broke it down by large PA. e.g. storage-samples-java (samples for datastore, GCE, bigquery, in java), compute-samples-python (samples for appengine, GCE, GKE in python) etc etc it would make more sense? @GoogleCloudPlatform/devrel-samples

**Comment by waprin** [comment]
I was thinking about this exact same topic and I am in favor of less repos, and the repos to be more language-specific than product specific. Bunch of reasons:

1. There are more products than languages.
2. Developers identify more closely with languages than products.
3. It simplifies consistency in style, testing, coverage etc. With less repos we are less likely to let some get out of date, when we need to update a way of doings things all the places to change will be in one spot. We will have to write less Travis files, less tox files, but we can focus more on getting the ones we have right.
4. A few big repos are more likely to get starred
5. Putting multiple products into one repo serves as free marketing for the other products
6. Less OSS review required

**Comment by elibixby** [comment]
Closing due to conclusion offline.
