### ISSUE TITLE
Refactor IAM snippets to adhere to code snippets style

### ISSUE THREAD

**Issue by Sita04** [GoogleCloudPlatform/java-docs-samples#6091]
sounds good, can you please make a tracking issue?

_Originally posted by @kolea2 in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/6064#discussion_r716795622_

Code snippets style guide: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md

**Comment by averikitsch** [comment]
Can be found https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/iam/snippets
