### ISSUE TITLE
Speech fails when using 0.17.1-alpha google-cloud library

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#639]
If I upgrade to 0.17.1-alpha weird stuff happens.

@gguuss Is this something you did?  Very strange errors from gax.

Vision appears to have similar issues

**Comment by gguuss** [comment]
I didn't see anything similar, [in the PR I made last night / this morning](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/641), I'm not seeing any issues, all tests pass.
