### ISSUE TITLE
getLabelAnnotationsList is returing empty map

### ISSUE THREAD

**Issue by buddhapuneeth** [GoogleCloudPlatform/java-docs-samples#644]
## In which file did you encounter the issue?
java-docs-samples/vision/cloud-client/src/main/java/com/example/vision/QuickstartSample.java

### Did you change the file? If so, how?

no. running on Tomcat 7 in java 1.8

## Describe the issue

EntityAnnotation annotation : res.getLabelAnnotationsList() 
there are no items in that. It was working fine some time back, now stopped working. I'm using:
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-vision</artifactId>
			<version>0.17.1-beta</version>

**Comment by lesv** [comment]
@gguuss PTAL

**Comment by gguuss** [comment]
It's possible that the results returned from ML APIs change, meaning an image that returned labels before no longer returns labels. I'm very surprised that you are not seeing any labels returned though. For me, sending a transparent image with just a few pixels in it returns labels. 

Is the issue occurring with all images or just a specific one? Are you seeing any errors from the API?

**Comment by gguuss** [comment]
This looks related to [this issue](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2039).  @buddhapuneeth it may be helpful for the Google Cloud Client library team to have your input.

**Comment by buddhapuneeth** [comment]
@gguuss it was the same behavior for all the images, those images when uploaded in google vision API home page is showing labels correctly. Even actual response from the API is having labels. I took the raw response and passed it to my custom parser to bypass. 
One more issue with APIs is the raw response of APIs is different from REST response. For example, in one it has 'Joy_Likelihood' and other has 'joylikelihood'. I noticed this because of my custom parser. As ML libraries are not working in GAE environment, I replaced APIs with REST calls then my parser started giving issues.

**Comment by gguuss** [comment]
In short, the issue you're experiencing is that we do not have good support for Tomcat currently from the cloud client libraries (those in the com.google.cloud namespace). [The issue I linked](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2039) is collecting feedback on what behavior you're experiencing from the API so they can resolve those behaviors in a future release of the client library.

**Comment by nnegrey** [comment]
This appears to have been resolved. Please feel free to reopen if this is not true. :)
