### ISSUE TITLE
appengine-java8/images - should use google-cloud-storage instead of gcs api

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#653]

**Comment by mpoehler** [comment]
Do you mean **com.google.cloud.storage** instead of **com.google.appengine.tools.cloudstorage**?

What is the reason?

And can the blobstore part in the example also be removed?

**Comment by lesv** [comment]
Java8 can use standard networking and the Veneer's work there.  It lowers the support surface as well.

**Comment by lesv** [comment]
I'll look, I know that what I'd like to do is show some examples using the Java Image API's for J8 now that we no longer have restrictions on using them.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 699 days. You may reopen this issue if it has been closed in error.
