### ISSUE TITLE
Getting Extra parameter from pub/sub topic when i added in cloud run

### ISSUE THREAD

**Issue by gurutu** [GoogleCloudPlatform/java-docs-samples#6580]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/run/pubsub/src/main/java/com/example/cloudrun

###  Description

Hi
I am getting this json data from pub/sub
here i am getting two extra properties
1.message_id
2.publish_time

{
message=
{
data="hello ",
messageId=370575563700,
message_id=370575563700,
publishTime=2021-12-08T10:55:15.958Z,
publish_time=2021-12-08T10:55:15.958Z
},
subscription=projects/<project_id>/subscriptions/<Sub_name>

}

because of that i am getting deserialization error

**Comment by anguillanneuf** [comment]
@gurutu  Thanks for the question. The push messages from Pub/Sub should have all those fields as listed: https://cloud.google.com/pubsub/docs/push#receiving_messages

Would you be able to handle the extra properties in your application?

**Comment by anguillanneuf** [comment]
Closing this as WAI.
