### ISSUE TITLE
Fix appengine-java8 README Hello World section

### ISSUE THREAD

**Issue by 4d55397500** [GoogleCloudPlatform/java-docs-samples#685]
## In which file did you encounter the issue?
README in appengine-java8

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8
## Describe the issue
Hello World links in README are incorrect/missing

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 739 days. You may reopen this issue if it has been closed in error.
