### ISSUE TITLE
Code Doesnt work with proxy enabled 

### ISSUE THREAD

**Issue by arunts2003** [GoogleCloudPlatform/java-docs-samples#688]
Hi , 

I tried using the code and it seems this doesnt work with proxy enabled and **throws time out exception**  , and works fine in the public network , 

since am new to Google APIs , would need help to sort this issue while i continue investigation .

**Comment by lesv** [comment]
IAP?  Which code?  Which proxy?

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 732 days. You may reopen this issue if it has been closed in error.
