### ISSUE TITLE
fix renovate rules to prevent it from lumping hbase & spark together

### ISSUE THREAD

**Issue by igorbernstein2** [GoogleCloudPlatform/java-docs-samples#6881]
Renovate PR #6847 intended to only upgrade hbase in the bigtable/spark example. But it seems to have also accidentally upgraded spark as well. This caused the example to break since it bumped spark to a nonexistent version

**Comment by meredithslota** [comment]
It's not clear how the Renovate config caused this: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/renovate.json

**Comment by averikitsch** [comment]
This PR confirms this is no longer an issue https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7721/files
