### ISSUE TITLE
Java 8 Samples that use @WebServlet should probably have a comment about web.xml

### ISSUE THREAD

**Issue by ifigotin** [GoogleCloudPlatform/java-docs-samples#690]
The samples for Java8 Standard are mostly the same as for Java7, except for @WebServlet.
It may not be obvious to the reader that for Java8 one does not need web.xml when looking at the docs that point to these samples for java7/java8.

Perhaps we should add an additional comment to the samples, saying (in each servlet) that no web.xml is required?

**Comment by lesv** [comment]
Will add comments in the class files.

**Comment by lesv** [comment]
Fixed in #692
