### ISSUE TITLE
Renovate bot does not update Spring Boot dependencies 

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#6955]
Update are being manually submitted, ie https://github.com/GoogleCloudPlatform/java-docs-samples/pull/6954

**Comment by eaball35** [comment]
Related issue #4579

**Comment by averikitsch** [comment]
> Related issue #4579 - config should have just been for pubsub

The Pub/Sub sample has been updated, so it's not an issue any more. See #4579 for info.
