### ISSUE TITLE
SpeechAPI samples and docs do not show how to pass credentials

### ISSUE THREAD

**Issue by redserpent7** [GoogleCloudPlatform/java-docs-samples#697]
I am trying to do some test using the Google Speech API but from outside Google Cloud. In the older beta version I was able to specify a credentials file but now I am unable to find this option in the SpeechClient class.

How can I go about specifying the authentication keys using the Google Speech API Java library? I believe a sample code should be added to demonstrate this (both passing flat credentials and using a credentials file)

P.S I already asked the [same exact question on SO](https://stackoverflow.com/questions/44409570/google-speech-api-credentials) but 4 days later and still no one answered

**Comment by frankyn** [comment]
Hi @redserpent7,

Thanks for reaching out! 

You can authenticate using a service-account and setting the environment variable:
`export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json`

Instructions on creating a service account and setting the environment variable can be found at:
https://cloud.google.com/docs/authentication/getting-started

**Comment by frankyn** [comment]
@redserpent7 did this help?

**Comment by redserpent7** [comment]
@frankyn thanks but I am really interested in setting the credentials path as a configuration variable. Namely I want to do the exact same thing [described here](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) but in Java

**Comment by frankyn** [comment]
@gguuss do you know how to set credentials programmatically?

**Comment by frankyn** [comment]
@redserpent7, I was able to set credentials using the following flow. I'd still like your input @gguuss when you have a moment.

```java
CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(ServiceAccountCredentials.fromStream(new FileInputStream("/path/to/service-account.json")));

ChannelProvider channelProvider = SpeechSettings.defaultChannelProviderBuilder().setCredentialsProvider(credentialsProvider).build();

SpeechSettings settings = SpeechSettings.defaultBuilder().setChannelProvider(channelProvider).build();

// Instantiates a client
SpeechClient speech = SpeechClient.create(settings);
```

**Comment by gguuss** [comment]
@frankyn -- you're doing it correctly, in the builder you just provide an API key or service account credential. For the samples, we are using the Application default credentials because it's simpler and more secure configuration.

**Comment by frankyn** [comment]
Thanks @gguuss! @redserpent7 let us know if this worked for you.

-

**Comment by redserpent7** [comment]
@frankyn Perfect thank you so much. And I hope you update the documentation to show that

**Comment by frankyn** [comment]
Great! Let us know if anything else comes up! We will update the documentation with this information soon.

**Comment by frankyn** [comment]
I posted this answer to your [stackoverflow question](https://stackoverflow.com/questions/44409570/google-speech-api-credentials/44655735#44655735) as well.

**Comment by Solido** [comment]
Using Gax:grpc 0.21.1 I got .setCredentialsProvider marked as deprecated and my json auth that is working well when loaded with GoogleCredentials on gcloud storage throws 
`The Application Default Credentials are not available` using the previous snippet. 
Do I miss smth ?

**Comment by Charles92011** [comment]
@frankyn I'm trying your solution, but it doesn't work for me.
SpeechSettings.defaultChannelProviderBuilder is undefined
SpeechSettings.defaultBuilder is deprecated
and SpeechSettings.defaultBuilder,setChannelProvider is undefined.

Your solution is only a couple of months old, I can't image it's out of date.

**Comment by Charles92011** [comment]
@Solido I gleaned this from a comment inside of SpeechClient.Java, it works for me:

```
		FileInputStream credentialsStream = new FileInputStream(fileName);
		GoogleCredentials credentials = GoogleCredentials.fromStream(credentialsStream);
		FixedCredentialsProvider credentialsProvider = FixedCredentialsProvider.create(credentials);

		SpeechSettings speechSettings = 
				SpeechSettings.newBuilder()
					.setCredentialsProvider(credentialsProvider)
					.build();		

		SpeechClient speech = SpeechClient.create(speechSettings);		

```

**Comment by ihunzai-dev** [comment]
`export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json` is not working @frankyn 

I have already set env variable using the command, but client library is still throwing same Exception

**Comment by hua21best** [comment]
@redserpent7 @Charles92011 thanks,Very useful to me
