### ISSUE TITLE
Google App engine Image transforming Issue from local tomcat server

### ISSUE THREAD

**Issue by yasikmondal** [GoogleCloudPlatform/java-docs-samples#702]
Hi Team,

I am trying to transform images using BlobstoreServiceFactory.

The code is running perfectly on Google cloud app engine. But when I am running the code from local tomcat sever it's throwing the below.

I have set the service account json file in system environment variable. I can read the bucket content from eclipse but while transforming getting the below exception. Please help..

for (StorageObject object : bucketContents) {

// Error coming from this line:

BlobKey blobKey = blobstoreService.createGsBlobKey("/gs/" + bucket + "/" + object.getName());

Image blobImage = ImagesServiceFactory.makeImageFromBlob(blobKey);
Transform resize1 = ImagesServiceFactory.makeResize(width, height);
Image resizeImage1 = imagesService.applyTransform(resize1, blobImage);

}

//Exception Details:

com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call blobstore.CreateEncodedGoogleStorageKey in a thread that is neither the original request thread nor a thread created by ThreadManager.

**Comment by lesv** [comment]
These apis are meant to be called from App Engine or from the development environment.  For Image transformation on your own Tomcat server, you might wish to use a java image transform library.

**Comment by yasikmondal** [comment]
I am deploying my application on tomcat but getting the image object from google cloud storage bucket.

In that case which library I need to use in my application (in eclipse) java image transform library or Google Cloud App engine library ?

**Comment by lesv** [comment]
Since you are running your app on your machine you will want to use something like: https://stackoverflow.com/questions/5895829/resizing-image-in-java

**Comment by yasikmondal** [comment]
Thanks lesv.. but before that I have to get the image from cloud bucket and for that I am using this method which is not giving the actual image though I am trying to do object.getImageDate().

```
public static List<StorageObject> listBucket(String bucketName) throws IOException, GeneralSecurityException {
		Storage client = StorageFactory.getService();
		System.out.print(bucketName);
		Storage.Objects.List listRequest = client.objects().list(bucketName);
		System.out.print("******* " + listRequest+ "**********");
		List<StorageObject> results = new ArrayList<StorageObject>();
		Objects objects;

		// Iterate through each page of results, and add them to our results
		// list.
		do {
			objects = listRequest.execute();
			// Add the items in this page of results to the list we'll return.
			results.addAll(objects.getItems());

			// Get the next page, in the next iteration of this loop.
			listRequest.setPageToken(objects.getNextPageToken());
		} while (null != objects.getNextPageToken());

		return results;
	}
```

Can please let me know how to get the actual image from cloud bucket if I am not using app engine library.

**Comment by lesv** [comment]
You might wish to use some [older apis](https://github.com/GoogleCloudPlatform/appengine-gcs-client) [docs](https://cloud.google.com/appengine/docs/java/googlecloudstorageclient/) [example](https://github.com/GoogleCloudPlatform/appengine-gcs-client/blob/master/java/example/src/main/java/com/google/appengine/demos/PortOfFilesAPIGuestbookServlet.java)

**Comment by yasikmondal** [comment]
Lesv do we have any tutorial in java for object change notification. I am running my application on cloud app engine and need to add this feature as well. Please share some tutorial link so that I can check and implement.

**Comment by lesv** [comment]
Take a look at [Object-Change-Notifications](https://cloud.google.com/storage/docs/object-change-notification) -- There is a python example.  (of course, now there are [pub/sub notifications](https://cloud.google.com/storage/docs/pubsub-notifications))

As I remember, the key things about setting up object-change-notification is that you need to have the endpoint setup to respond to the requests before you create the request.

**Comment by yasikmondal** [comment]
@lesv : Do you have any example with source code (**in JAVA**). so that I can check.

**Comment by lesv** [comment]
On GAE standard, Flex, or somewhere else?  I'll add it to the todo list for next Q.

**Comment by yasikmondal** [comment]
@lesv I am running my code on GAE . Do you have any update for this Enhancement in Java?

**Comment by lesv** [comment]
With Tomcat, it's probably GAE Flexible, as GAE Standard uses Jetty as it's servlet container.  It's reasonable to have a sample, I'm still scheduling the Q, will know more later this week.

**Comment by yasikmondal** [comment]
@LesV any update on this ? do we have any sample..

**Comment by yasikmondal** [comment]
@lesv ny update or still scheduling the Q for that Object Change Notification in Java?

**Comment by lesv** [comment]
I'll be doing something this week for this.

**Comment by lesv** [comment]
Actually I'll be doing a GAE J8 sample that does image transformation using libraries.   Not sure I'll get to Object Change Notification, but I'll look.

**Comment by yasikmondal** [comment]
Any good news @lesv ? Still I am waiting for your action on this.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 652 days. You may reopen this issue if it has been closed in error.
