### ISSUE TITLE
Java8 Standard: replacing the old GAE Image APIs?

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#704]
Feature request: Java8 Standard: replacing the old GAE Image APIs
Now we can use AWT/Java2D API calls in Java8 Standard, we could write a migration tutorial and try to map the GAE APIs to open source (or Java Standard) APIs.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 726 days. You may reopen this issue if it has been closed in error.
