### ISSUE TITLE
/bigquery/rest tests use GOOGLE_CLOUD_PROJECT

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#708]
We should get rid of this and use something to automatically configure from GoogleDefaultAuth

**Comment by lesv** [comment]
/language/analysis/AnalyzeBetaIT uses projectID to get a bucket for stuff.

**Comment by lesv** [comment]
/monitoring/cloud-client uses both GOOGLE_CLOUD_PROJECT || GCLOUD_PROJECT

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for {days_inactive} days. You may reopen this issue if it has been closed in error.
