### ISSUE TITLE
Unable to run the sample application for google cloud platform

### ISSUE THREAD

**Issue by architsinha** [GoogleCloudPlatform/java-docs-samples#710]
I am just starting off on google-cloud-platform. I have created an account and a project on cloud console. I was trying to run some of the sample apps provided. I started with the sample app for cloud storage provided at:

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/storage/cloud-client

I have installed apache maven 3.5.0 on my PC. I followed the steps provided in the link, that is I gave the following commands:

`mvn clean package -DskipTests`
and then

`mvn exec:java -Dexec.mainClass=com.example.storage.QuickstartSample -Dexec.args="my-bucket-name"`
The first command succeeded. However, the second command failed. I got the following error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2017-06-15T18:27:55+05:30
[INFO] Final Memory: 15M/172M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project storage-google-cloud-samples: An exception occured while executing the Java class. connect timed out -> [Help 1]
```
Now, the computer where I was running this command on, is behind a proxy. However, my proxy settings have been set in the file conf/settings.xml, also when I ran the first command, it successfully downloaded some packages, so I'm not sure if it is due to some proxy issue, however to check, I tried it on another machine, which is not behind a proxy.

I gave the same two commands. The first one succeeded and the second failed again, with the following (different) error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2017-06-15T18:22:31+05:30
[INFO] Final Memory: 13M/32M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (d
efault-cli) on project storage-google-cloud-samples: An exception occured while
executing the Java class. 401 Unauthorized -> [Help 1]
```
So my queries are:

1. What could be the cause for the error in the first case? Is it something to do with proxy settings? If yes, then where/how should I specify the settings?
2. What could be the cause for the error in the second case where I am not behind any proxy?
3. Am i missing some step here?
4. Also , if you look at the source for this sample app, there is just a single file which basically creates a bucket. The bucket is passed as an argument from command line. Now, as per my understanding, first there needs to a project in the cloud console to create any resources. So where will this bucket be created? As in shouldn't we be specifying the project-ID where this bucket is to be created?

**Comment by lesv** [comment]
Have you done the following:

*  Install the [Cloud SDK](https://cloud.google.com/sdk/) followed by:
```bash
gcloud init
gcloud auth application-default login
```
It should pick up the projectID from gcloud.

**Comment by architsinha** [comment]
Thanks a lot, the issue is resolved.
I had installed the Cloud SDK and run the command 
`gcloud init `
However, the command 
`gcloud auth application-default login`
was missing.  After giving the command I was able to run the app from the PC which was not behind the proxy.
As regards to the other PC, which is behind the proxy, the issue got resolved after I added the proxy settings in the command, that is:
`mvn -DproxySet=true -DproxyHost=proxy.XXXX.com -DproxyPort=XXXX exec:java -Dexec.mainClass=com.example.storage.QuickstartSample -Dexec.args="my-bucket-name"`

**Comment by architsinha** [comment]
I have an additional query regarding this. I am able to build and run from the command line after following the steps mentioned above.
However when I try to import and build the project in eclipse (I import it as a maven project), I get the following error in the pom.xml : 

`Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (execution: default-compile, phase: compile)    pom.xml /datastore-google-cloud-samples line 23 Maven Project Build Lifecycle Mapping Problem`

The details of eclipse I am using are: 
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

I looked at the following answer: How to solve "Plugin execution not covered by lifecycle configuration" for Spring Data Maven Builds and added the pluginManagement tag in my pom.xml, however I still got the same error.

Is there any step which I am missing here?
Is there any particular setting which needs to be done in eclipse to use it with maven and/or google cloud?
Is there any modification needed in pom.xml for building with eclipse?
Has anyone else observed this issue?

**Comment by lesv** [comment]
Are you using Spring?

Have you changed the pom?

Are you importing to use w/o maven?  (if so, I'm not likely to know the answer), [Google Eclipse Plugin](https://developers.google.com/eclipse/)

My quick guess is that you removed the parent pom, and some of our samples can't yet run standalone.  You might need to add something from one of the parents.

**Comment by jabubake** [comment]
Can you paste your `pluginManagement` section here ?

**Comment by jabubake** [comment]
@architsinha Please re-open if you are still running into issues
