### ISSUE TITLE
sendgrid

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#717]
appengine/
appengine-java8/
flexible/

Sendgrid has jumped two major versions - samples need to be rewritten

**Comment by lesv** [comment]
Also, compute-sendgrid/

**Comment by lesv** [comment]
Undo the sendgrid lockout in rules.xml (java repo tools) when this is fixed
https://github.com/GoogleCloudPlatform/java-repo-tools/pull/72

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 722 days. You may reopen this issue if it has been closed in error.
