### ISSUE TITLE
500 server Internal error for appengine/cloudsql sample app

### ISSUE THREAD

**Issue by architsinha** [GoogleCloudPlatform/java-docs-samples#722]
I was trying to build and run the following sample app for appengine and cloudsql:
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine/cloudsql

I did the following steps before running the app:
1. gcloud sql instances create $instanceName --tier=D2
 
2. gcloud sql users set-password root % --instance $instanceName --password $myPassword

3. Created a databased $myDatabase using cloud console as mentioned in the following link: https://cloud.google.com/sql/docs/mysql/create-manage-databases#creating_a_database

I updated the following in pom.xml:
INSTANCE_CONNECTION_NAME --- The connection name got from the command 
`gcloud sql instances describe $instanceName | grep connectionName`
user --- root
password  --- $myPassword
database ---  $myDatabase

Then I built the project using:
mvn clean appengine:update

When I open the web page http://$PROJECT-ID/appspot.com, I get **500 Server Error** with the following message:

```
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```
Also I noticed that the appengine-web.xml file for this project does not have the application and version  tags. I added them before building
How will it work without that?

**Comment by lesv** [comment]
Are you using a SQLv1 or SQLv2 instance?

**Comment by lesv** [comment]
I just did it with:

mvn clean appengine:update -Dappengine.appId=MYPROJECT -Dappengine.version=44 -DINSTANCE_CONNECTION_NAME=MYPROJECT:us-central1:bookshelf

**Comment by jabubake** [comment]
@architsinha please re-open if you are still running into the same issue.
