### ISSUE TITLE
Update org.hibernate:hibernate-core to v6

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#7318]
Update spanner sample to work with [org.hibernate:hibernate-core](https://hibernate.org/orm) to v6.
(Based on PR #6967)

**Comment by JoeWang1127** [comment]
Blocked by a [hibernate issue](https://hibernate.atlassian.net/browse/HHH-15573).

**Comment by JoeWang1127** [comment]
[This issue](https://hibernate.atlassian.net/browse/HHH-15573) is fixed thus remove the blockage.
