### ISSUE TITLE
PubSub example PubsubMessage instead of custom Message class

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/java-docs-samples#7325]
Hi,

why do you use a custom Message class in your PubSub example instead of using the existing PubsubMessage class from the client library. It even has a parse method.

`PubsubMessage.parseFrom()`

However, the parse method does not work on my json data (sensitive data replaced) encoded to an ByteArray.

Payload:
```
  {
    "message": {
      "publishTime": "2022-09-25T07:57:44.387Z",
      "data": "...",
      "attributes": {
        "objectGeneration": "1664092664057682",
        "eventType": "OBJECT_FINALIZE",
        "notificationConfig": "...",
        "eventTime": "2022-09-25T07:57:44.123614Z",
        "bucketId": "....appspot.com",
        "payloadFormat": "JSON_API_V1",
        "objectId": " "..."
      },
      "publish_time": "2022-09-25T07:57:44.387Z",
      "message_id": "5755354085772689",
      "messageId": "5755354085772689"
    },
    "subscription": " "..."
  }
```

**Comment by anguillanneuf** [comment]
@Burtan Thanks for the question. Could you provide a link to the example you're looking at?

**Comment by anguillanneuf** [comment]
Please look at the Java protobuf example here: https://cloud.google.com/pubsub/docs/pull#schemas

https://github.com/googleapis/java-pubsub/blob/2b9c2e8af4f83dd8d51272a0539c7ade05041a68/samples/snippets/src/main/java/pubsub/SubscribeWithProtoSchemaExample.java#L61
