### ISSUE TITLE
SQL (my / postgre) samples should use Apache Connection Pooling

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#739]
(optional/future) instead of DriverManager.getConnection,
connection pooling with commons-bcp : https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2

**Comment by jabubake** [comment]
@lesv : @kurtisvg is planning to address this in the coming quarters, but might be looking into hikari instead for Java.
