### ISSUE TITLE
retail: add comments to interactive tutorials

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/java-docs-samples#7429]
**Product:** [retail](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/retail)
**Sample:** [interactive-tutorials](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/retail/interactive-tutorials)

**NOTE:** 
- This issue was migrated from the [java-retail](https://github.com/googleapis/java-retail) repository as part of the mono-repo migration process. 
- See original issue here: https://github.com/googleapis/java-retail/issues/515
---

**Reporter:** @alicejli 

**Description:**
There currently are no comments in any of the files in the `retail/interactive-tutorials/src/main/java/events/setup/` directory. It would be helpful to add comments to the files or a **README** into the directory to understand what these files are for. 

First highlighted in this PR: https://github.com/googleapis/java-retail/pull/494

**Comment by kweinmeister** [comment]
@chenlei1216 Can we get help from the Retail team to add comments or update the README as described? Thanks!

**Comment by kweinmeister** [comment]
Issue has been open for over a year. Let's reopen if/when we want to take care of this.
