### ISSUE TITLE
Cloud Run Filesystem sample is not cleaning up services

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/java-docs-samples#7565]
In the java-docs-samples-testing project, new `filesystem<UUID>` services are being created daily.

They appear to be coming from [ApplicationTests.java](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java#L63), which does have a [cleanup step](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/2734187ea2214bb3e13f95923d25e89cde61d2f4/run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java#L123).

**Comment by averikitsch** [comment]
I removed the extra services using command:
```
for i in $(gcloud run services list --format json | jq -r '.[].metadata.name'); do
   gcloud run services delete $i --region us-central1 --quiet
done
```
