### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by trishav96** [GoogleCloudPlatform/java-docs-samples#763]
## In which file did you encounter the issue?
I'm trying to run the QuicksampleStart file. I did it on Eclipse. it gives these errors:

## Describe the issue

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	SpeechClient cannot be resolved to a type
	SpeechClient cannot be resolved
	ByteString cannot be resolved to a type
	ByteString cannot be resolved
	RecognitionConfig cannot be resolved to a type
	RecognitionConfig cannot be resolved
	AudioEncoding cannot be resolved to a variable
	RecognitionAudio cannot be resolved to a type
	RecognitionAudio cannot be resolved
	RecognizeResponse cannot be resolved to a type
	SpeechRecognitionResult cannot be resolved to a type
	SpeechRecognitionResult cannot be resolved to a type
	SpeechRecognitionAlternative cannot be resolved to a type
	SpeechRecognitionAlternative cannot be resolved to a type

	at speechTest.QuickstartSample.main(QuickstartSample.java:25)

**Comment by gguuss** [comment]
How are you installing the dependencies, e.g. are you running the following command:

    mvn clean compile assembly:single

and

    export GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/service.json
    export GCLOUD_PROJECT=

Before running
    
    mvn integration-test

I recommend you try building / running from the command line using the instructions in `README.MD` to get to a working state before trying to configure your IDE for execution.

**Comment by trishav96** [comment]
I didn't do any of that

**Comment by gguuss** [comment]
@trishav96 Please try [following the instructions for building the sample using Maven](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech/cloud-client).  If you must build the sample using Eclipse, the following settings will help:

* Edit your maven build configurations by clicking the Green Run button
![Run menu](http://wheresgus.com/buildrun.png)

* Add a configuration for building
![Build configuration](http://wheresgus.com/buildconfig.png)

* Add a configuration for running
![Run configuration](http://wheresgus.com/runconfig.png)

Note that for the Maven extension to work, you must have Eclipse configured to find the JAVA_HOME environment variable as appropriate.

**Comment by nnegrey** [comment]
This appears to have been resolved. Please feel free to reopen if this is not true. :)
