### ISSUE TITLE
Unable to build docs and language application #2

### ISSUE THREAD

**Issue by disbrain** [GoogleCloudPlatform/java-docs-samples#767]
user@hostname ~/java-docs-samples $ mvn clean compile package assembly:single
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.google.cloud.language.samples:language-entities:jar:1.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.auth:google-auth-library-oauth2-http:jar -> duplicate declaration of version 0.7.1 @ line 52, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
...
[INFO] Reactor Summary:
[INFO] 
[INFO] doc-samples ........................................ FAILURE [  0.628 s]

...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.335 s
[INFO] Finished at: 2017-07-24T14:33:42+02:00
[INFO] Final Memory: 28M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (default-cli) on project doc-samples: Error reading assemblies: No assembly descriptors found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lesv** [comment]
What version of Maven are you using?

**Comment by nnegrey** [comment]
Hi, It looks like this issue never had a followup, if you're still having an issue, please feel free to reopen this. Thanks! :)

**Comment by evfimivs** [comment]
Hey Noah,
Yes, I still do have this error
