### ISSUE TITLE
Add e2e tests for appengine flex projects for java 11 and 17

### ISSUE THREAD

**Issue by kappratiksha** [GoogleCloudPlatform/java-docs-samples#7733]
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7717 needs additional tests

**Comment by averikitsch** [comment]
@kappratiksha this was suppose to be a fast follow up. It has now been over a month. Please address this issue.

**Comment by jinglundong** [comment]
@averikitsch Do you know if we have any E2E tests for GAE applications that we could use as examples in this repo? From my previous experience working with the python-docs-samples repo, setting up the initial E2E tests made follow-up E2E tests quite straightforward.

**Comment by averikitsch** [comment]
We have an example for Cloud Run, see https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/run/jobs/src/test/java/com/example/JobsIntegrationTests.java. It uses Cloud Build to deploy the app and tear it down, so we can test requests to the service.

**Comment by kappratiksha** [comment]
We won't be fixing this.
