### ISSUE TITLE
Remove duplicated Flex samples

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#7753]
GAE flex samples were duplicated in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7717. @kappratiksha is there a timeline for updating the docs and removing these samples?

**Comment by kappratiksha** [comment]
The doc update is in progress. We don't have an ETA but I am hoping it should not take more than 2-3 weeks

**Comment by kappratiksha** [comment]
Fixed: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8256
