### ISSUE TITLE
chore: remove iot samples folder given deprecation of Cloud IoT Core

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/java-docs-samples#7833]
#### Description
- Google Cloud has [announced the deprecation of Cloud IoT Core](https://cloud.google.com/iot/docs/release-notes#:~:text=Cloud%20IoT%20Core%20will%20be%20retired%20on%20August%2016%2C%202023.) come this August.
- In light of this, should we also remove the [iot samples](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/iot) from this repo.

**Comment by kweinmeister** [comment]
FYI https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9498
