### ISSUE TITLE
ci: lint presubmit scans entire repo (not filtered for the PR)

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/java-docs-samples#7882]
The `lint` presubmit job seems to be checking all code sample directories even if they're not part of the PR.

I recently saw a failure on a [Bigtable PR](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7878) due to a GAE lint issue.

**Comment by averikitsch** [comment]
More context: It looks like this changed three days ago starting with build https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fjava%2Fjava-docs-samples%2Flint%2Fpresubmit/activity/b527e351-8134-4f77-981a-1eed92efe69f/log. This coincides with an update with an update to the test container https://pantheon.corp.google.com/gcr/images/cloud-devrel-kokoro-resources/global/java11, but that seems unrelated.

**Comment by averikitsch** [comment]
This problem should be fixed now, see lint runs in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7890
