### ISSUE TITLE
failure in the push test

### ISSUE THREAD

**Issue by dexterchan** [GoogleCloudPlatform/java-docs-samples#789]
## In which file did you encounter the issue?
when testing
curl -H "Content-Type: application/json" -i --data @sample_message.json "localhost:8080/pubsub/push?token=dextest"

## Describe the issue
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /pubsub/push. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NoClassDefFoundError: com/google/auth/ServiceAccountSigner
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467

**Comment by lesv** [comment]
Which sample?  /pubsub/client ??  Something else?
What environment? (GAE Standard, GAE Flex, GCP, GKE, something else?)

**Comment by dexterchan** [comment]
SOrry, after changing pom.xml.... it works again.... 
I was testing in GAE flexible locally.

**Comment by jabubake** [comment]
@dexterchan : closing issue, please re-open if issue persists.
