### ISSUE TITLE
datalabeling/ missing pom.xml

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/java-docs-samples#7893]
The pom.xml (and any other needed files) are missing from the `datalabeling` snippets. So, they are not currently being tested.

**Comment by lesv** [comment]
@nirupa-kumar  PTAL
@averikitsch PTAL
@athakor PTAL

Doesn't look like it was ever there. :(

**Comment by kweinmeister** [comment]
This [commit](https://github.com/GoogleCloudPlatform/java-docs-samples/commit/16b511454e12cae998cd349bc7fe6ff5eadd4fd8) may have deleted more than it needed to?
