### ISSUE TITLE
Resolution issue while transforming the image through Blobkey.

### ISSUE THREAD

**Issue by yasikmondal** [GoogleCloudPlatform/java-docs-samples#790]
I am facing some resolution issue while transforming the image through Blobkey. 

The resolution of transformed images are getting poor. Can you please let me know if there is any option or parameter which needs to be set to maintain the same resolution as original image. Below are the code snippet  for resizing and transforming. I am running my app from Google Cloud App Engine.

```
Creating BlobKey: 

BlobstoreService blobstoreService = BlobstoreServiceFactory.getBlobstoreService();
BlobKey blobKey = blobstoreService.createGsBlobKey("/gs/" + bucket + "/" + object.getName());

Creating Image from Blobkey:

Image blobImage = ImagesServiceFactory.makeImageFromBlob(blobKey);

Transforming and resizing Image with custom height and width:

Transform resize = ImagesServiceFactory.makeResize(width, height);
Image resizeImage = imagesService.applyTransform(resize, blobImage);
```

**Comment by lesv** [comment]
Are you increasing or decreasing size?

With Java 8 on GAE standard you can use any Java Image library.

**Comment by yasikmondal** [comment]
Yes I am resizing those image like below format.
125X75 , 188X113 , 300X250 , 450X375 , 90X90 , 135X135 , 350X175 , 525X265

What will do in that case?

**Comment by lesv** [comment]
Make sure that you always start with the best image (initial one).  Ideally it should be larger than all your target images.  You might wish to crop it first (to an appropriate (same ratio as dest) rectangle) before resizing - to reduce distortion.

**Comment by yasikmondal** [comment]
resizing the image which is less format compare to originial image. for example orginal image dimension 1500x1500 and I am trying to resize to 300x250. Still resolution quality is getting poor.

**Comment by lesv** [comment]
You should crop  before you resize - ie. 1500x1500 -> 300x250 should be cropped to 1500x1250 before the resize. (ie. 5x reduction in both dimensions, rather than 5x width x 6x length, you are currently doing)

**Comment by yasikmondal** [comment]
If I am cropping the image which means we are cutting some part of the image. Requirement is, it should not cut any content of original image only resize. Without cropping is there any option @lesv ?

**Comment by lesv** [comment]
Resize to a different aspect ratio will always distort the image.  That's just reality and math.  Cropping allows you to use a new aspect ratio that you can preserve on resize.

This is no longer a topic for this repo, however, I would suggest you look at StackOverflow for image libraries and techniques.
