### ISSUE TITLE
Incorrect example in DeIdentifyTextWithFpe

### ISSUE THREAD

**Issue by chitara-01** [GoogleCloudPlatform/java-docs-samples#7952]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTextWithFpe.java

## Did you change the file? If so, how?

Updated the variables under TODO(developer) section in the same file.

## Describe the issue

The example given in textToDeIdentify doesn't contain any information related to InfoType PHONE_NUMBER which is to be encrypted using the given code sample.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by Shabirmean** [comment]
@GoogleCloudPlatform/googleapis-dlp @imadethis - Can you TAL at this?
There is also a PR https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7953
