### ISSUE TITLE
[java-containeranalysis] There is no sample code for this library

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/java-docs-samples#7984]
Copying from https://github.com/googleapis/java-containeranalysis/issues/729

@Alos wrote:
The https://github.com/googleapis/java-containeranalysis/tree/main/samples directory contains no sample code to use. They are just empty Java projects. Is this intentional?

As per @averikitsch : We currently are working on the generation of these samples.

**Comment by averikitsch** [comment]
Samples can be found https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/container-registry/container-analysis/src/main/java/com/example/containeranalysis
