### ISSUE TITLE
gaeinfo sample does not deploy (flexible, flexible/java-8)

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/java-docs-samples#8028]
To reproduce,
`mvn clean package deploy:appengine` 

Results:
`Unable to stage app: GAE Flex compat applications need to depend on the GAE API jar, but it was not found in the WEB-INF/lib directory.`

Expected:
Deploy to GAE

Scope:
* AppEngine flex samples in `flexible` and `flexible/java-8` do not deploy.
* Standard sample in `appengine/java-8` was able to successfully deploy.

**Comment by averikitsch** [comment]
Note: There is an open issue for adding E2E tests #7733

**Comment by kappratiksha** [comment]
We no longer support flex compat runtimes. we need to delete these samples

**Comment by iennae** [comment]
fixed via #8160; is there anything else that needs to be cleaned out?

**Comment by averikitsch** [comment]
I reviewed our sample set and this bug should be complete.
