### ISSUE TITLE
JUnit tests are skipped in modules that use spring-boot-starter-test

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/java-docs-samples#8135]
Explanation on [StackOverflow](https://stackoverflow.com/questions/70892138/junit-4-12-is-not-executing-after-spring-boot-2-6-2-migration).

Every `pom.xml` that contains `spring-boot-starter-test` should add `junit-vintage-engine`, until the tests are migrated to Junit 5.
```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <scope>test</scope>
   </dependency>
```
cc: @averikitsch

**Comment by kweinmeister** [comment]
Thanks for flagging this.

It looks like we can also exclude `org.junit.jupiter:junit-jupiter` to run Junit 4 tests.
```
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-test</artifactId>
     <scope>test</scope>
     <exclusions>
         <exclusion>
             <groupId>org.junit.jupiter</groupId>
             <artifactId>junit-jupiter</artifactId>
         </exclusion>
     </exclusions>
 </dependency>
 ```

Any preferences?

**Comment by meltsufin** [comment]
Yes, that's another option. I slightly prefer the first option based on experience of sometimes playing whack-a-mole with the exclusions.
