### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/protobuf/ByteString

### ISSUE THREAD

**Issue by samirissa00** [GoogleCloudPlatform/java-docs-samples#814]
## In which file did you encounter the issue?
NONE

### Did you change the file? If so, how?
POM.xml remove de PARENT tag

## Describe the issue
when i try the execute get that ERROR

usr/jdk64/jdk1.8.0_60/bin/java -cp target/vision-google-cloud-samples-1.0-SNAPSHOT.jar com.example.vision.Detect labels "/root/Downloads/safe_image.php.jpeg"
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/ByteString
	at com.example.vision.Detect.detectLabels(Detect.java:254)
	at com.example.vision.Detect.argsHelper(Detect.java:95)
	at com.example.vision.Detect.main(Detect.java:59)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.ByteString
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

**Comment by samirissa00** [comment]
My POM.xml

`
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.vision</groupId>
  <artifactId>vision-google-cloud-samples</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-vision</artifactId>
      <version>0.21.1-beta</version>
    </dependency>
    

    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-oauth2-http</artifactId>
      <version>0.7.1</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.0</version>
    </dependency>
    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.google.truth</groupId>
      <artifactId>truth</artifactId>
      <version>0.34</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>com.example.vision.Detect</mainClass>
            </manifest>
          </archive>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
    </plugins>
  </build>
    <name>vision-google-cloud-samples</name>
</project>
`

**Comment by samirissa00** [comment]
> 
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.vision</groupId>
  <artifactId>vision-google-cloud-samples</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-vision</artifactId>
      <version>0.21.1-beta</version>
    </dependency>
    

    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-oauth2-http</artifactId>
      <version>0.7.1</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.0</version>
    </dependency>
    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.google.truth</groupId>
      <artifactId>truth</artifactId>
      <version>0.34</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>com.example.vision.Detect</mainClass>
            </manifest>
          </archive>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
    </plugins>
  </build>
    <name>vision-google-cloud-samples</name>
</project>
>

**Comment by samirissa00** [comment]
`
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.vision</groupId>
  <artifactId>vision-google-cloud-samples</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-vision</artifactId>
      <version>0.21.1-beta</version>
    </dependency>
    

    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-oauth2-http</artifactId>
      <version>0.7.1</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.0</version>
    </dependency>
    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.google.truth</groupId>
      <artifactId>truth</artifactId>
      <version>0.34</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>com.example.vision.Detect</mainClass>
            </manifest>
          </archive>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
    </plugins>
  </build>
    <name>vision-google-cloud-samples</name>
</project>
`

**Comment by samirissa00** [comment]
[pom.zip](https://github.com/GoogleCloudPlatform/java-docs-samples/files/1232074/pom.zip)

**Comment by jabubake** [comment]
@samirissa00 , please compile into a jar with dependencies using
```
mvn clean compile assembly:single
```
You should then be able to run it as 
```
/usr/jdk64/jdk1.8.0_60/bin/java -cp target/vision-google-cloud-samples-1.0-jar-with-dependencies.jar com.example.vision.Detect labels "/root/Downloads/safe_image.php.jpeg"
```

**Comment by samirissa00** [comment]
HO , Ok compile with dependencies

**Comment by evfimivs** [comment]
> You should then be able to run it as
I still get the same error
