### ISSUE TITLE
Cloud endpoints V2: WARNING: storagePath only applies to Dev Appserver v2 and will be ignored by Dev Appserver v1

### ISSUE THREAD

**Issue by darshanlbangre** [GoogleCloudPlatform/java-docs-samples#827]
After migrating to endpoints v2 as per the documentation (https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference). On adding <devserver.storagePath> to appengine-maven-plugin I see a warning "storagePath only applies to Dev Appserver v2 and will be ignored by Dev Appserver v1" and the data store path is ignored.

**Comment by frankyn** [comment]
Hi @darshanlbangre!

Thanks for filing this issue. @loosebazooka have you seen this issue before?

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 651 days. You may reopen this issue if it has been closed in error.
