### ISSUE TITLE
GoogleCloudPlatform/cloud-asset-platform-team has no members

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#8288]
[GoogleCloudPlatform/cloud-asset-platform-team](https://github.com/orgs/GoogleCloudPlatform/teams/cloud-asset-platform-team) has no members. In Codeowners and blunderbuss it is double listed with team [cloud-asset-analysis-team](https://github.com/orgs/GoogleCloudPlatform/teams/cloud-asset-analysis-team). We should confirm if both are needed or if we should clean up the config files.

**Comment by rsamborski** [comment]
Both teams are needed. I am working with @angieshen-google to make sure team members have properly configured a link between their GitHub and internal Google accounts to make sure this team is correctly propagated.

**Comment by iennae** [comment]
we've removed the platform team as of https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9515 as the team was still empty. If and when the team manages their memberships we can add it back.
