### ISSUE TITLE
Firewall rules need clean up

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#8321]
1. There are many firewall rules that need to be cleaned up in the test project, for example: https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fperiodic/activity/d6cf8580-3f2a-4a5a-a5b3-4037524454b4/invocations/d6cf8580-3f2a-4a5a-a5b3-4037524454b4/targets/github%2Fjava-docs-samples%2Fcompute%2Fcloud-client%2Ftarget%2Fsurefire-reports/tests
2. We need to ensure that the test resources are properly cleaned up in `compute/cloud-client/src/test/java/compute/windows/windowsinstances/CreatingManagingWindowsInstancesIT.java`

**Comment by rsamborski** [comment]
Changing type to cleanup. @Sita04 is there any additional work that you're planning to do in scope of this task?

**Comment by Sita04** [comment]
@rsamborski It's safe to close this issue as it's not anymore related to the repository. The firewall rules created are from other repositories that use the project.
