### ISSUE TITLE
Proxy Authentication for Google Speech Api Credential

### ISSUE THREAD

**Issue by swapp1990** [GoogleCloudPlatform/java-docs-samples#833]
I am trying to configure google speech api to work in my project within the company's firewall. I have configured the SpeechSettings as following:

```
InputStream is = this.getClass().getResourceAsStream("/my-service-account.json");           
CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(ServiceAccountCredentials.fromStream(is));
SpeechSettings.Builder builder = SpeechSettings.newBuilder();
builder.setTransportProvider(SpeechSettings.defaultTransportProvider());
builder.setCredentialsProvider(credentialsProvider);
SpeechSettings settings =  builder.build();
SpeechClient.create(settings);
```

## Describe the issue
 Using this works outside proxy network correctly and starts a speech recognize session. But it fails to transcribe anything under a proxy authenticated network and times out without giving any error. Is it possible to authenticate with the proxy settings while creating the speech client session? Thanks.

**Comment by swapp1990** [comment]
Yes, I have tried that solution but that didn't work for me. 
The only solution that worked with the proxy issue was setting environment variable: GRPC_PROXY_EXP="<hostname>:<port>" in the $PATH.

**Comment by zchking** [comment]
> Yes, I have tried that solution but that didn't work for me.
> The only solution that worked with the proxy issue was setting environment variable: GRPC_PROXY_EXP="hostname:port" in the $PATH.

this solve my problem， thank you

**Comment by nnegrey** [comment]
This issue appears to have been resolved, if that is not the case. Please feel free to reopen. Thanks! :)
