### ISSUE TITLE
Don't split declaration and initialization

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/java-docs-samples#839]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/storage/json-api/src/main/java/StorageSample.java

### Did you change the file? If so, how?
Change

```
    Objects objects;

    // Iterate through each page of results, and add them to our results list.
    do {
      objects = listRequest.execute();
```

to

```

    // Iterate through each page of results, and add them to our results list.
    do {
      Objects objects = listRequest.execute();
```

**Comment by jabubake** [comment]
The split seems required in this particular instance of the do-while loop, so that `while` can reference the object
