### ISSUE TITLE
App Engine Java 11 sample for Endpoints V2?

### ISSUE THREAD

**Issue by waterdrake** [GoogleCloudPlatform/java-docs-samples#8435]
In the Getting started with Cloud Endpoints Frameworks for Java documentation [here](https://cloud.google.com/endpoints/docs/frameworks/java/get-started-frameworks-java) it says to use the sample project at java-docs-samples/appengine-java8/endpoints-v2-backend. However, app engine with Java 8 is marked for deprecation.

Will there be a Java 11 sample for endpoints v2?

**Comment by averikitsch** [comment]
At this time, Cloud Endpoints is only available for Java 8, see https://cloud.google.com/endpoints/docs/frameworks/about-cloud-endpoints-frameworks#limitations.
