### ISSUE TITLE
endpoints-framework-maven-plugin should use 1.0.1

### ISSUE THREAD

**Issue by coollog** [GoogleCloudPlatform/java-docs-samples#847]
## In which file did you encounter the issue?

[appengine/endpoints-frameworks-v2/backend/pom.xml](../blob/master/appengine/endpoints-frameworks-v2/backend/pom.xml)
[Line 88](../blob/master/appengine/endpoints-frameworks-v2/backend/pom.xml#L88) should be changed from `<version>1.0.0</version>` to `<version>1.0.1</version>`.

### Did you change the file? If so, how?

N/A

## Describe the issue

Version 1.0.0 of `endpoints-framework-maven-plugin` breaks `mvn endpoints-framework:openApiDocs` when running from `appengine/endpoints-frameworks-v2/backend/`. Version 1.0.1 works.

https://github.com/GoogleCloudPlatform/endpoints-framework-maven-plugin
@loosebazooka

**Comment by frankyn** [comment]
I'll fix this asap. Thanks @coollog
