### ISSUE TITLE
Adding samples for calling the Cloud Support API

### ISSUE THREAD

**Issue by veliebm** [GoogleCloudPlatform/java-docs-samples#8473]
## Is your feature request related to a problem? Please describe.

Yes. Users of my team's API, the Cloud Support API, need examples of how to call it with Java.

## Describe the solution you'd like.

We'd like to add examples of calling our API to this repository. Specifically, an example for every endpoint in [our REST reference](https://cloud.google.com/support/docs/reference/v2):

- caseClassifications.search
- cases.attachments.list
- cases.close
- cases.comments.create
- cases.comments.list
- cases.create
- cases.escalate
- cases.get
- cases.list
- cases.patch
- cases.search
- media.download
- media.upload

### Inlining examples straight in our docs.

Summary: Add a Java example inline for the docs for each of our endpoints.

Pros:

- Fastest to do.
- Don't need to keep track of a new repository.
- Don't need to work with any other teams to do.

Cons:

- Hard to read.
- Adds clutter to the docs.
- Not searchable in snippets.
- Java is very verbose, and we wouldn't have space for a verbose solution.
- Tricky to test.

Rejection reason: This would be too hard to read for our users and for us to test, and we couldn't include all the details we'd want to include because the examples would need to be so short.

### Making our own GitHub repository.

Summary: Make our own GitHub repository to place our examples in.

Pros:

- Don't need to work with any other teams to do this.
- Can choose what we merge.

Cons:

- Unknown how we'd do this, or whether we're allowed.
- Would need to structure the repo ourselves - including testing and GitHub actions.
- Not the canonical solution.

Rejection reason: It'd be a bigger lift than we'd like to set up a brand new repository. Also, I believe Google recommends that we place our examples in the current repo anyway.

## Additional context.

The examples we want to include will use client libraries generated from our discovery document.

Thanks for your time!

**Comment by veliebm** [comment]
@minherz Do we have your go-ahead to do this?

**Comment by minherz** [comment]
@veliebm thank you for feature request. While we do not have capability to cover all APIs with appropriate code samples, we recognize the importance of such samples for developers.
We do not develop generic code samples for use of the REST API. This project is mainly intended to host samples that are used in documentation to demonstrate work with APIs via client libraries. I see that there are two auto-generated client libraries in Java that expose support API:
- [googleapis/google-cloud-java](https://github.com/googleapis/google-cloud-java) exposing v2 of the API
- [googleapis/google-api-java-client-services](https://github.com/googleapis/google-api-java-client-services) exposing v2beta of the API

These libraries contain auto-generated samples. For example, users of Support API can find samples for use of the v2 API primitives in the [/samples/snippets/generated/com/google/cloud/support/v2][1] folder.

Consider providing additional information about what samples are missing and special use cases. If you are API developer, we encourage you to contribute code samples to API. If you decide to write code samples, please consult with the [contributor guide][2].

[1]: https://github.com/googleapis/google-cloud-java/tree/9ae786d1acdc7354adf86b78691570668caa293d/java-cloudsupport/samples/snippets/generated/com/google/cloud/support/v2
[2]: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/8ddd51fd8d29e118df14beef7c4008e76bd20130/CONTRIBUTING.md

**Comment by veliebm** [comment]
Closing because we've decided to just inline these instead.
