### ISSUE TITLE
ktor example using gradle instead of maven

### ISSUE THREAD

**Issue by pablichjenkov** [GoogleCloudPlatform/java-docs-samples#8716]
Is it possible to have a version of the **ktor example** with the flexible environment and using gradle?

Thanks

**Comment by minherz** [comment]
Hello @pablichjenkov , this repo hosts code samples that are used in Google public documentation and tutorials. 
Your request looks related to CI frameworks (gradle vs maven) and not to the use of Google Cloud services in Java applications. While we provide both configurations for many code samples we guarantee that at least one method to build the code is provided.
We are welcome external [contributions] and guarantee to include it into the repository if it answers all our acceptance criteria.

[contributions]: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/CONTRIBUTING.md
