### ISSUE TITLE
Client lib returns: The model "default" does not exist in the location named "global"

### ISSUE THREAD

**Issue by rterzman** [GoogleCloudPlatform/java-docs-samples#8791]
I am using lib version:
`<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-speech</artifactId>
            <version>4.22.0</version>
        </dependency>`

There is a request:

`
            // Recognition config with Auto decoding detection
            RecognitionConfig config = RecognitionConfig.newBuilder()
                    .setFeatures(RecognitionFeatures.newBuilder()
                            .setEnableAutomaticPunctuation(true)
                            .setEnableWordConfidence(true)
                            .setEnableWordTimeOffsets(true)
                            .build())
                    .setAutoDecodingConfig(AutoDetectDecodingConfig.newBuilder().build())
                    .setModel("default")
                    .addLanguageCodes("iw-IL")
                    .build();

            // Recognition audio file metadata
            BatchRecognizeFileMetadata metadata = BatchRecognizeFileMetadata.newBuilder()
                    .setUri(task.getGsFile())
                    .build();

            // Build request
            BatchRecognizeRequest request = BatchRecognizeRequest.newBuilder()
                    .setConfig(config)
                    .setRecognizer(recognizer)
                    .addFiles(metadata)
                    .setRecognitionOutputConfig(RecognitionOutputConfig.newBuilder()
                            .setInlineResponseConfig(InlineOutputConfig.newBuilder().build()))
                    .build();

            Operation operationData = client.batchRecognizeCallable().call(request);`

It returns error: 
**The model "default" does not exist in the location named "global"**

I tried to change location to "us-central-1", but error is the same:
**The model "default" does not exist in the location named "us-central1"**

**Comment by minherz** [comment]
Hello @rterzman, can you please provide the following information in additional to the issue description:

* What is the path to the code sample in the problem?
* What files did you modify if any when you reproduce the problem?

**Comment by iennae** [comment]
@rterzman following up on this 

PLEASE READ: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

The issue you're having must be related to a file in this repository. We are unable to provide assistance for issues unrelated to samples in this repository.

I'm going to go ahead and close this, please feel free to reopen with more details.
