### ISSUE TITLE
Asset inventory: searchAllResources sample not working for Bigquery Dataset

### ISSUE THREAD

**Issue by Sita04** [GoogleCloudPlatform/java-docs-samples#8798]
Related issue: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/8553

On debugging, looks like this issue is specific to Bigquery Dataset. The dataset on creation doesn't propagate to Asset Inventory within the timeout. Whereas, a Compute Instance is available via "searchAllResources" API instantly.

Further investigation should be made to identify if its WAI.

**Comment by Sita04** [comment]
@zhuocheng0202 PTAL at this issue.

**Comment by kweinmeister** [comment]
As part of this fix, the ignore should be removed. PR with the change is linked to this issue.

**Comment by minherz** [comment]
> As part of this fix, the ignore should be removed. PR with the change is linked to this issue.

What is the PR that fixes the problem? The linked #8869 adds `@Ignore` to the `SearchIT. testSearchAllResourcesExample` test method.
