### ISSUE TITLE
Keeping Instances - appengine/endpoints-frameworks-v2/backend

### ISSUE THREAD

**Issue by alistairsykes** [GoogleCloudPlatform/java-docs-samples#880]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine/endpoints-frameworks-v2/backend

### Did you change the file? If so, how?
No - except to change the project id

## Describe the issue
I ran this example project on a app engine project, and after _ah/start in order to handle my request it starts an instance. That instance never seems to stop of its own accord. I thought it was supposed to given its using the basic-scaling setting. Is there something wrong, or have I misunderstood the behaviour its supposed to exhibit.

**Comment by frankyn** [comment]
Pinging @tangiel Hey Daniel, do you know why AppEngine Standard wouldn't scale down? I'm not quite sure why it wouldn't scale down.

**Comment by tangiel** [comment]
It's a current known issue for basic scaling--background threads seem to prevent termination of instances.

**Comment by frankyn** [comment]
Is there a known workaround?

**Comment by tangiel** [comment]
You can use automatic scaling. If your traffic is extremely low, then metrics may not be totally accurate in automatic scaling, but it should allow instances to shut down.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for {days_inactive} days. You may reopen this issue if it has been closed in error.
