### ISSUE TITLE
Cloud Translation API(v3)-glossaries  Term configuration Hebrew He is not effective

### ISSUE THREAD

**Issue by devinliu1** [GoogleCloudPlatform/java-docs-samples#8933]
I have created an equivalent terminology set terminology table CSV file, which contains various corresponding relationships such as en, he, de, etc., and created terminology resources for the translate API through the API client. createGlossaryAsync(). When I call client. translateText() and set the use of glossaryConfiguration, de, and other languages before calling, it will take effect. The corresponding terms in the Hebrew he or iw columns are not effective, and the API returns a null value, May I ask what the reason is? 

Thanks!

**Comment by minherz** [comment]
Hello @devinliu1 can you please elaborate if you question relates to a particular code sample hosted in this repository and if it is then to point to the sample?
If you think an issue is within a Cloud Translation API client library, I would recommend to open a new issue in the [google-cloud-java](https://github.com/googleapis/google-cloud-java) repo.
Alternatively, you can ask a question in the [Translation AI](https://www.googlecloudcommunity.com/gc/forums/filteredbylabelpage/board-id/cloud-ai-ml/label-name/Translation%2520AI) community forum.

**Comment by devinliu1** [comment]
ok Thanks!

**Comment by minherz** [comment]
Closing this issue as addressed.
