### ISSUE TITLE
Is there any workaround way to process start up certification before I really start my recognition work

### ISSUE THREAD

**Issue by alanywlee** [GoogleCloudPlatform/java-docs-samples#905]
Dears,

I used Google speech API and found library will print two block of of message like certification
as following if I run java with option "-Dlog4j.debug=true".

```
Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256
...
```

I checked OUTBOUND time-stamp and noticed Google actually sent my speech usually 4.5 - 5.5 seconds after I called Google Speech API at the first time after application started in case of using 40~50 threads to run simultaneously.

```
2017-10-31 16:54:14,432 [DEBUG] [er-ELG-2-1] 
----------------OUTBOUND--------------------
[id: 0xe75ba63b, L:/10.137.35.174:57240 - R:speech.googleapis.com/216.58.200.42:443] SETTINGS: ack=false, settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
------------------------------------
```
My problem is the first batch of jobs always work much longer than the following batch is pretty annoying to measure recognition efficiency. Is there any workaround way to process the start up certification before I really start my recognition work.

Any suggestion is highly appreciated.
Best regards,

Alan

**Comment by lesv** [comment]
@nnegrey / @gguuss PTAL

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. You may reopen this issue if it has been closed in error.
