### ISSUE TITLE
ENDPOINTS_SERVICE_VERSION missing or is it no longer required?

### ISSUE THREAD

**Issue by william-ferguson-au** [GoogleCloudPlatform/java-docs-samples#923]
## In which file did you encounter the issue?

webapp/web-inf/appengine-web.xml

## Describe the issue

Previous doco for V2 of the Cloud Framework Java AppENgine instances referred to setting the value of
        <env-var name="ENDPOINTS_SERVICE_VERSION" value="2017-11-13r0" />
in appengine-web.xml from the API version that was returned when deploying OpenAPI.json to the server.

This seems to be omitted in the current Java Maven doco and in the sample sin this repo. But still exists in the Endpoints Framework command line doco.

Does this value need to be supplied?

It seems that the appengine instance probably needs it in order to know which APIs it should support.
But since the AppEngine instance should be able to generate and infer the OpenAPI doc itself (instead of being explicitly given it), who knows?

**Comment by frankyn** [comment]
Hi @william-ferguson-au,

Thanks for filing this issue. To answer your question, the value is optional. When a service version number isn't defined Cloud Endpoints will use the latest deployed version. This needs to be updated in documentation and I'll forward this feedback to the right person.

Thank you.
