### ISSUE TITLE
A future improvement would be to properly serialize/deserialize when we write to a real database (not the sharedpreferences, but datastore)

### ISSUE THREAD

**Issue by BornNk** [GoogleCloudPlatform/java-docs-samples#9257]
A future improvement would be to properly serialize/deserialize when we write to a real database (not the sharedpreferences, but datastore)

https://kotlinlang.org/docs/serialization.html

_Originally posted by @gdeluna-branch in https://github.com/BranchMetrics/android-branch-deep-linking-attribution/pull/1129#discussion_r1343371236_

**Comment by minherz** [comment]
Hello @BornNk , thank you for your submission. Would you mind to clarify a couple of details about it?
It is unclear which code sample or Google Cloud service you mean. If you request is applicable to the specific code sample(s), please respond with the path(s) of the sample(s) and we will review them.
Also, this repository focuses on Java code samples. While Kotlin can be seen as a Java dialect, it is a different language. I see that the original thread about serialization comes from Android branch. Would you mind to check if this request is better fitted for https://github.com/GoogleCloudPlatform/kotlin-samples repository?

Thank you,
@minherz
