### ISSUE TITLE
Payments 

### ISSUE THREAD

**Issue by BornNk** [GoogleCloudPlatform/java-docs-samples#9268]
https://github.com/GoogleCloudPlatform/java-docs-samples/blame/57373926927d0a19880c86294e0b998eab869108/auth/src/main/java/LookupApiKey.java#L24

**Comment by minherz** [comment]
Hello @BornNk, we cannot review the issue you created because it has no information besides the link to the line of the class declaration.
Please provide additional details about the issue in order for us to be able to review it.
