### ISSUE TITLE
'run' in 'groovy.lang.Closure<V>' cannot be applied to '(groovy.lang.Closure<java.lang.Integer>)'

### ISSUE THREAD

**Issue by yuriry** [GoogleCloudPlatform/java-docs-samples#948]
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/453ce56023e25fe1cf8505def01aaab43738ad73/appengine/helloworld-new-plugins/build.gradle#L47

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 546 days. You may reopen this issue if it has been closed in error.
