### ISSUE TITLE
sample does not compile with Java7

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#949]
Got 
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project appengine-helloworld: Execution default of goa
l org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-ch
eckstyle-plugin:2.17:check: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/AuditListener : Unsupported major.minor version 52.0

with a JDK 7 installation for appengine helloworld compilation

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 545 days. You may reopen this issue if it has been closed in error.
