### ISSUE TITLE
CONTRIBUTING.md tells you to contribute to an archived repo

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/java-docs-samples#9540]
## In which file did you encounter the issue?

https://github.com/hegemonic/java-docs-samples/blob/main/CONTRIBUTING.md

## Did you change the file? If so, how?

no

## Describe the issue

The `CONTRIBUTING.md` file for this repo says the following:

> If you want to contribute a full sample / tutorial, please consider contributing to our [community pages](https://cloud.google.com/community) [[How To](https://cloud.google.com/community/tutorials/write)] ([code](https://github.com/GoogleCloudPlatform/community)).

But https://github.com/GoogleCloudPlatform/community has been archived, and we no longer publish that content at https://cloud.google.com/community. We should probably just delete this sentence.

**Comment by iennae** [comment]
@hegemonic thanks for letting us know. We'll get that updated.
