### ISSUE TITLE
Incorrect dependency

### ISSUE THREAD

**Issue by yuriry** [GoogleCloudPlatform/java-docs-samples#957]
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/213532488c59d4c4ba2eae41da93ca430dd8cbef/appengine/helloworld-new-plugins/build.gradle#L40

should say:
```compile 'com.google.appengine:appengine-api-1.0-sdk:+'```

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 541 days. You may reopen this issue if it has been closed in error.
