### ISSUE TITLE
Typo in Firestore tutorial

### ISSUE THREAD

**Issue by CeH9** [GoogleCloudPlatform/java-docs-samples#991]
Seems like in [comments](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/firestore/src/main/java/com/example/firestore/snippets/References.java#L52-L53) should be "users", not "employees".

[here too](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/firestore/src/main/java/com/example/firestore/snippets/References.java#L65-L66)

[Tutorial that reffers to this code](https://firebase.google.com/docs/firestore/data-model)

**Comment by jabubake** [comment]
@campionfellin Tx for the fix !
